# Enriquecimiento de personas (dirección y guion) — corpus completo

Objetivo: obtener `sexo` y `país` para cada director/a y guionista del
corpus (~2052 películas), partiendo de `icaa_peliculas.csv`.

**Fuentes de crédito** (quién dirigió/escribió cada película):
- ICAA (`directores_icaa`/`guionistas_icaa`) — para las ~1775 películas con `icaa_id`
- TMDB directo — para las ~277 películas SIN `icaa_id` (sección aislada, no se mezcla con lo anterior)

**Fuentes de enriquecimiento de persona** (sexo/país), en cascada:
1. TMDB (`search/person` + ficha de persona)
2. Wikidata (vía el `imdb_id` que da TMDB en `external_ids`)
3. IMDb directo — solo país (campo estructurado, con respaldo de biografía en prosa)
4. Correcciones manuales (reutilizadas de la fase anterior del proyecto)

## 1. Librerías y configuración

In [2]:
import os
import re
import json
import csv
import time
import random
from pathlib import Path

import pandas as pd
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

BASE = Path("..")
CSV_DIR = BASE / "3 - csv"

TMDB_API_KEY = os.getenv("TMDB_API_KEY")
assert TMDB_API_KEY, "No se encontró TMDB_API_KEY en el .env"

print("✓ Librerías y configuración cargadas")

✓ Librerías y configuración cargadas

In [3]:
def get_session():
    s = requests.Session()
    s.headers.update({"User-Agent": "ProyectoAcademicoLatam/1.0"})
    return s

session = get_session()


def cargar_cache_json(path):
    if path.exists():
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return {}


def guardar_cache_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)


def normalizar_texto(texto):
    import unicodedata
    if not isinstance(texto, str):
        return ""
    t = unicodedata.normalize("NFKD", texto.lower())
    t = "".join(c for c in t if not unicodedata.combining(c))
    return re.sub(r"\s+", " ", t).strip()

print("✓ Utilidades de caché y normalización listas")

✓ Utilidades de caché y normalización listas

In [4]:
from selenium import webdriver
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from selenium.webdriver.firefox.service import Service as FirefoxService
from webdriver_manager.firefox import GeckoDriverManager


def iniciar_driver():
    options = FirefoxOptions()
    options.add_argument("--headless")
    driver = webdriver.Firefox(
        service=FirefoxService(GeckoDriverManager().install()),
        options=options,
    )
    driver.set_page_load_timeout(20)
    return driver

print("✓ iniciar_driver definido (Firefox headless, igual que en notebook 1)")

✓ iniciar_driver definido (Firefox headless, igual que en notebook 1)

## 2. Cargar corpus

In [5]:
icaa_peliculas = pd.read_csv(CSV_DIR / "icaa_peliculas.csv", sep=';')
print(f"Total películas: {len(icaa_peliculas)}")
print(f"Con icaa_id: {icaa_peliculas['icaa_id'].notna().sum()}")
print(f"Sin icaa_id: {icaa_peliculas['icaa_id'].isna().sum()}")
icaa_peliculas.head()

Total películas: 2052
Con icaa_id: 1775
Sin icaa_id: 277

,titulo,distribuidora_pdf_heuristica,fecha_estreno,recaudacion,espectadores,anio,anio_reposicion,titulo_busqueda,articulo,icaa_id,...,guionistas_icaa,subvenciones_icaa,subvenciones_total,empresas_productoras_icaa,recaudacion_total,espectadores_total,anios_en_cartelera,num_anios,distribuidora_final,distribuidora_fuente
0,"091, policia al habla (1960) (re)",Independent,16/05/2025,42.0,12,2025,1960.0,"091, policia al habla",NaN,NaN,...,NaN,NaN,NaN,NaN,42.0,12,2025,1,Independent,pdf_heuristica
1,Todos lo saben,Universal,14/09/2018,83.0,18,2022,NaN,Todos lo saben,NaN,100317.0,...,"[""Asghar Farhadi""]","[{""concepto"": ""Ayudas Generales para la produc...",280000.0,"[{""pais"": ""ESPAÑA"", ""porcentaje_pais"": 50.0, ""...",83.0,18,2022,1,"UNIVERSAL PICTURES INTERNATIONAL SPAIN, S.L. (...",ficha_icaa
2,"Generacion silenciosa, La",Independent,10/09/2021,129.0,35,2021,NaN,Generacion silenciosa,La,100421.0,...,"[""Ferrán Navarro-Beltrán""]",NaN,0.0,"[{""pais"": ""ESPAÑA"", ""porcentaje_pais"": 100.0, ...",129.0,35,2021,1,PELICULA SIN DISTRIBUIDORA ASIGNADA (98J000),ficha_icaa
3,Platon,Independent,08/10/2021,237.0,60,2021,NaN,Platon,NaN,100517.0,...,"[""Iván López González""]",NaN,0.0,"[{""pais"": ""ESPAÑA"", ""porcentaje_pais"": 100.0, ...",237.0,60,2021,1,PELICULA SIN DISTRIBUIDORA ASIGNADA (98J000),ficha_icaa
4,Agua,Independent,11/02/2022,1975.0,319,2022,NaN,Agua,NaN,100820.0,...,"[""Vicente Pérez Herrero"", ""Marta Martínez Rodr...",NaN,0.0,"[{""pais"": ""ESPAÑA"", ""porcentaje_pais"": 100.0, ...",2296.0,357,"2022,2023",2,LAS PRODUCCIONES DE LOS IMAGINARIOS. PRODUCCIO...,ficha_icaa

## 3. Sección aislada — créditos vía TMDB directo (solo películas sin `icaa_id`)

Estas películas no tienen `directores_icaa`/`guionistas_icaa` porque ICAA
nunca las resolvió. En vez de dejarlas fuera del análisis de personas, se
buscan directamente en TMDB por título+año, y se extraen sus créditos de
`director`/`guionista` con `person_id` ya resuelto (más fiable que buscar
por nombre, porque el endpoint de créditos da el id directo).

Se guarda en una tabla separada, marcada `fuente_credito='tmdb_directo'`,
para que no se confunda con lo verificado por ICAA.

In [6]:
sin_icaa_id = icaa_peliculas[icaa_peliculas['icaa_id'].isna()].copy()
print(f"Películas sin icaa_id a buscar en TMDB: {len(sin_icaa_id)}")
sin_icaa_id[['titulo', 'anio', 'fecha_estreno']].head()

Películas sin icaa_id a buscar en TMDB: 277

                                    titulo  anio fecha_estreno
0        091, policia al habla (1960) (re)  2025    16/05/2025
152                                    117  2025    12/06/2025
826   2 Años, 4 Meses (2 Urte, 4 Hilabete)  2021    04/09/2020
1112                  33 años de oscuridad  2022    23/05/2022
1779                           A dos velas  2025    18/02/2025

In [7]:
def buscar_pelicula_tmdb(titulo, anio, session, timeout=15):
    """
    Busca una película en TMDB por título + año, con margen de +/-1 año
    (la calificación puede caer en un año distinto al de producción,
    igual que vimos con ICAA). Devuelve (tmdb_id, titulo_tmdb) o (None, None).
    """
    url = "https://api.themoviedb.org/3/search/movie"
    intentos_anio = [anio, anio - 1, anio + 1] if pd.notna(anio) else [None]
    for anio_intento in intentos_anio:
        params = {"api_key": TMDB_API_KEY, "language": "es-ES", "query": titulo}
        if anio_intento:
            params["year"] = int(anio_intento)
        try:
            r = session.get(url, params=params, timeout=timeout)
            r.raise_for_status()
            resultados = r.json().get("results", [])
        except Exception as e:
            print(f"  Error búsqueda TMDB '{titulo}': {e}")
            continue
        if resultados:
            top = resultados[0]
            return top.get("id"), top.get("title")
    return None, None

print("✓ buscar_pelicula_tmdb definida")

✓ buscar_pelicula_tmdb definida

In [8]:
PELICULA_TMDB_SEARCH_CACHE = CSV_DIR / "pelicula_tmdb_search_cache.json"

pelicula_search_cache = cargar_cache_json(PELICULA_TMDB_SEARCH_CACHE)
print(f"Caché existente: {len(pelicula_search_cache)} películas ya buscadas")

pendientes_pelicula = [
    row for row in sin_icaa_id.itertuples()
    if row.titulo not in pelicula_search_cache
]
print(f"Pendientes: {len(pendientes_pelicula)}")

for i, row in enumerate(pendientes_pelicula, 1):
    if i % 25 == 0:
        print(f"  [{i}/{len(pendientes_pelicula)}] {row.titulo}")
    tmdb_id, titulo_tmdb = buscar_pelicula_tmdb(row.titulo, row.anio, session)
    pelicula_search_cache[row.titulo] = {"tmdb_id": tmdb_id, "titulo_tmdb": titulo_tmdb}
    if i % 25 == 0:
        guardar_cache_json(PELICULA_TMDB_SEARCH_CACHE, pelicula_search_cache)
    time.sleep(0.25)

guardar_cache_json(PELICULA_TMDB_SEARCH_CACHE, pelicula_search_cache)

sin_icaa_id['tmdb_id'] = sin_icaa_id['titulo'].map(
    lambda t: pelicula_search_cache.get(t, {}).get("tmdb_id")
)
print(f"\n✓ Con tmdb_id encontrado: {sin_icaa_id['tmdb_id'].notna().sum()} / {len(sin_icaa_id)}")

Caché existente: 0 películas ya buscadas
Pendientes: 277
  [25/277] Aun
  [50/277] Chichi y yo
  [75/277] Dies d'estiu i de pluja
  [100/277] Flores de tierra quemada. Estrategias del terror en Guatemala y España
  [125/277] Invasion pequeña
  [150/277] Metralla de amor
  [175/277] Nosotros no nos mataremos con pistolas
  [200/277] Quieres salir puedes entrar
  [225/277] Sexo, drogas, rock 'n' roll y política. Instituto Santamarca, 1975-1985
  [250/277] Tu me abrasas
  [275/277] Zoo, Sobreviure a l'incendi

✓ Con tmdb_id encontrado: 120 / 277

### Persistir `tmdb_id` en `icaa_peliculas.csv`

Así cada película queda resoluble por un identificador estable
(`icaa_id` o `tmdb_id`, nunca los dos a la vez) sin depender de volver a
buscar por título en ningún notebook posterior.

In [9]:
icaa_peliculas['tmdb_id'] = icaa_peliculas['titulo'].map(
    lambda t: pelicula_search_cache.get(t, {}).get("tmdb_id")
)
# Solo debería quedar poblado para las que no tienen icaa_id -- si alguna
# fila tiene ambos, algo salió mal en el filtro de más arriba.
ambos = icaa_peliculas[icaa_peliculas['icaa_id'].notna() & icaa_peliculas['tmdb_id'].notna()]
assert len(ambos) == 0, f"{len(ambos)} filas con icaa_id Y tmdb_id a la vez -- revisar"

icaa_peliculas.to_csv(CSV_DIR / "icaa_peliculas.csv", index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC)
print(f"✓ icaa_peliculas.csv actualizado con tmdb_id")
print(f"  Con icaa_id: {icaa_peliculas['icaa_id'].notna().sum()}")
print(f"  Con tmdb_id (sin icaa_id): {icaa_peliculas['tmdb_id'].notna().sum()}")
print(f"  Sin ninguno de los dos: {(icaa_peliculas['icaa_id'].isna() & icaa_peliculas['tmdb_id'].isna()).sum()}")

✓ icaa_peliculas.csv actualizado con tmdb_id
  Con icaa_id: 1775
  Con tmdb_id (sin icaa_id): 120
  Sin ninguno de los dos: 157

In [10]:
# También actualizar icaa_peliculas en MySQL -- si no, queda desincronizada
# con el CSV (sin tmdb_id, sin las 277 filas que ahora sí tienen identificador)
engine = create_engine(
    f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
    f"@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}"
)
icaa_peliculas.to_sql('icaa_peliculas', engine, if_exists='replace', index=False)
engine.dispose()
print("✓ icaa_peliculas actualizado en MySQL (con tmdb_id incluido)")

✓ icaa_peliculas actualizado en MySQL (con tmdb_id incluido)

In [11]:
GENERO_MAP = {0: None, 1: "mujer", 2: "hombre", 3: "no_binario"}
JOBS_GUION = {"Screenplay", "Writer", "Story", "Teleplay", "Co-Writer"}


def obtener_credits_tmdb(tmdb_id, session, timeout=15):
    url = f"https://api.themoviedb.org/3/movie/{tmdb_id}/credits"
    params = {"api_key": TMDB_API_KEY, "language": "es-ES"}
    try:
        r = session.get(url, params=params, timeout=timeout)
        r.raise_for_status()
        return r.json().get("crew", [])
    except Exception as e:
        print(f"  Error credits tmdb_id={tmdb_id}: {e}")
        return []

print("✓ obtener_credits_tmdb definida (reutilizada de la fase anterior)")

✓ obtener_credits_tmdb definida (reutilizada de la fase anterior)

In [12]:
CREDITS_TMDB_DIRECTO_CACHE = CSV_DIR / "credits_tmdb_directo_cache.csv"

if CREDITS_TMDB_DIRECTO_CACHE.exists():
    credits_tmdb_directo = pd.read_csv(CREDITS_TMDB_DIRECTO_CACHE, sep=';')
    tmdb_ids_hechos = set(credits_tmdb_directo['tmdb_id'].dropna().unique())
    print(f"Reanudando: {len(tmdb_ids_hechos)} películas ya procesadas")
else:
    credits_tmdb_directo = pd.DataFrame()
    tmdb_ids_hechos = set()
    print("Empezando desde cero")

tmdb_ids_a_consultar = sorted({
    tid for tid in sin_icaa_id['tmdb_id'].dropna().unique()
    if tid not in tmdb_ids_hechos
})
print(f"Pendientes: {len(tmdb_ids_a_consultar)}")

registros = []
for i, tmdb_id in enumerate(tmdb_ids_a_consultar, 1):
    if i % 25 == 0:
        print(f"  [{i}/{len(tmdb_ids_a_consultar)}] tmdb_id={tmdb_id}")

    crew = obtener_credits_tmdb(tmdb_id, session)
    for miembro in crew:
        department = miembro.get("department")
        job = miembro.get("job")
        if department == "Directing" and job == "Director":
            rol = "director"
        elif department == "Writing" and job in JOBS_GUION:
            rol = "guionista"
        else:
            continue
        registros.append({
            "icaa_id": None,
            "tmdb_id": tmdb_id,
            "rol": rol,
            "nombre": miembro.get("name"),
            "person_id_tmdb": miembro.get("id"),
            "fuente_credito": "tmdb_directo",
        })

    if i % 50 == 0 and registros:
        batch = pd.DataFrame(registros)
        credits_tmdb_directo = pd.concat([credits_tmdb_directo, batch], ignore_index=True)
        credits_tmdb_directo.to_csv(CREDITS_TMDB_DIRECTO_CACHE, index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC)
        registros = []
        print("  ✓ Guardado parcial")

    time.sleep(0.25)

if registros:
    batch = pd.DataFrame(registros)
    credits_tmdb_directo = pd.concat([credits_tmdb_directo, batch], ignore_index=True)
    credits_tmdb_directo.to_csv(CREDITS_TMDB_DIRECTO_CACHE, index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC)

print(f"\n✓ Créditos vía TMDB directo: {len(credits_tmdb_directo)} filas")
if len(credits_tmdb_directo):
    print(credits_tmdb_directo['rol'].value_counts())

Empezando desde cero
Pendientes: 120
  [25/120] tmdb_id=811631.0
  [50/120] tmdb_id=1033028.0
  ✓ Guardado parcial
  [75/120] tmdb_id=1229067.0
  [100/120] tmdb_id=1386565.0
  ✓ Guardado parcial

✓ Créditos vía TMDB directo: 275 filas
rol
director     145
guionista    130
Name: count, dtype: int64

## 4. Flujo principal — créditos desde ICAA (películas con `icaa_id`)

`directores_icaa`/`guionistas_icaa` vienen como listas JSON serializadas
(una por película). Se explotan a formato largo (una fila por crédito) y
se limpian los nombres antes de seguir.

In [13]:
def limpiar_nombre_credito(nombre_crudo):
    """
    Limpia un nombre tal como viene de la ficha ICAA:
    1. Quita anotaciones de segmento (": 'Título del segmento'.") --
       películas de episodios/antología con un director distinto por segmento.
    2. Separa casos donde dos personas quedaron concatenadas sin separador
       en el parser de notebook 1 ("Apellido1, Nombre1 Apellido2, Nombre2").
    3. Normaliza "Apellido, Nombre" -> "Nombre Apellido" (ICAA mezcla ambos
       formatos dentro del mismo campo, sin consistencia).
    Devuelve una LISTA de nombres limpios (normalmente 1, a veces 2 si había
    concatenación).
    """
    texto = nombre_crudo.strip()

    texto = re.sub(r":\s*['\u2018\u2019].*?['\u2018\u2019]\.?\s*$", "", texto).strip()
    texto = texto.rstrip(".").strip()

    partes_coma = texto.split(",")
    if len(partes_coma) == 3:
        apellido1 = partes_coma[0].strip()
        resto = partes_coma[1].strip().split()
        nombre2 = partes_coma[2].strip()
        if len(resto) >= 2:
            nombre1 = resto[0]
            apellido2 = " ".join(resto[1:])
            return [f"{nombre1} {apellido1}", f"{nombre2} {apellido2}"]

    if len(partes_coma) == 2:
        apellido, nombre = partes_coma[0].strip(), partes_coma[1].strip()
        return [f"{nombre} {apellido}"]

    return [texto]

print("✓ limpiar_nombre_credito definida (probada contra los ~15 casos reales detectados)")

✓ limpiar_nombre_credito definida (probada contra los ~15 casos reales detectados)

In [14]:
con_icaa_id = icaa_peliculas[icaa_peliculas['icaa_id'].notna()].copy()

registros_icaa = []
for _, row in con_icaa_id.iterrows():
    for col, rol in (('directores_icaa', 'director'), ('guionistas_icaa', 'guionista')):
        valor = row[col]
        if pd.isna(valor):
            continue
        try:
            nombres_crudos = json.loads(valor)
        except Exception:
            continue
        for nombre_crudo in nombres_crudos:
            for nombre_limpio in limpiar_nombre_credito(nombre_crudo):
                registros_icaa.append({
                    "icaa_id": row['icaa_id'],
                    "tmdb_id": None,
                    "rol": rol,
                    "nombre": nombre_limpio,
                    "person_id_tmdb": None,
                    "fuente_credito": "icaa",
                })

credits_icaa = pd.DataFrame(registros_icaa)
print(f"✓ Créditos ICAA explotados y limpiados: {len(credits_icaa)} filas")
print(credits_icaa['rol'].value_counts())
credits_icaa.head()

✓ Créditos ICAA explotados y limpiados: 4884 filas
rol
guionista    2867
director     2017
Name: count, dtype: int64

,icaa_id,tmdb_id,rol,nombre,person_id_tmdb,fuente_credito
0,100317.0,None,director,Asghar Farhadi,None,icaa
1,100317.0,None,guionista,Asghar Farhadi,None,icaa
2,100421.0,None,director,Ferrán Navarro-Beltrán,None,icaa
3,100421.0,None,guionista,Ferrán Navarro-Beltrán,None,icaa
4,100517.0,None,director,Iván López González,None,icaa

## 5. Unificar créditos (ICAA + TMDB directo)

In [15]:
credits_df = pd.concat([credits_icaa, credits_tmdb_directo], ignore_index=True)
print(f"✓ Total créditos unificados: {len(credits_df)}")
print("\nPor rol:")
print(credits_df['rol'].value_counts())
print("\nPor fuente:")
print(credits_df['fuente_credito'].value_counts())

✓ Total créditos unificados: 5159

Por rol:
rol
guionista    2997
director     2162
Name: count, dtype: int64

Por fuente:
fuente_credito
icaa            4884
tmdb_directo     275
Name: count, dtype: int64

## 6. Resolver `person_id` en TMDB

Para los créditos de ICAA (que solo traen el nombre), buscar la persona por
nombre en TMDB. Los de `tmdb_directo` ya traen `person_id_tmdb` resuelto
directamente del endpoint de créditos -- más fiable, no hace falta buscar.

In [16]:
def buscar_persona_tmdb_por_nombre(nombre, session, timeout=15):
    """Busca una persona en TMDB por nombre. Devuelve (person_id, nombre_tmdb) o (None, None)."""
    url = "https://api.themoviedb.org/3/search/person"
    params = {"api_key": TMDB_API_KEY, "language": "es-ES", "query": nombre}
    try:
        r = session.get(url, params=params, timeout=timeout)
        r.raise_for_status()
        resultados = r.json().get("results", [])
        if not resultados:
            return None, None
        top = resultados[0]
        return top.get("id"), top.get("name")
    except Exception as e:
        print(f"  Error búsqueda persona '{nombre}': {e}")
        return None, None

print("✓ buscar_persona_tmdb_por_nombre definida (reutilizada)")

✓ buscar_persona_tmdb_por_nombre definida (reutilizada)

In [17]:
PERSON_SEARCH_CACHE = CSV_DIR / "person_search_tmdb_cache.json"

person_search_cache = cargar_cache_json(PERSON_SEARCH_CACHE)

necesitan_match = credits_df[credits_df['person_id_tmdb'].isna()]
nombres_unicos = necesitan_match['nombre'].dropna().unique()
print(f"Nombres únicos a buscar en TMDB: {len(nombres_unicos)}")

pendientes_nombres = [n for n in nombres_unicos if n not in person_search_cache]
print(f"Pendientes: {len(pendientes_nombres)}")

for i, nombre in enumerate(pendientes_nombres, 1):
    if i % 25 == 0:
        print(f"  [{i}/{len(pendientes_nombres)}]")
    person_id, nombre_tmdb = buscar_persona_tmdb_por_nombre(nombre, session)
    person_search_cache[nombre] = {"person_id": person_id, "nombre_tmdb": nombre_tmdb}
    if i % 25 == 0:
        guardar_cache_json(PERSON_SEARCH_CACHE, person_search_cache)
    time.sleep(0.25)

guardar_cache_json(PERSON_SEARCH_CACHE, person_search_cache)
print("✓ Búsqueda de persona por nombre completada")

Nombres únicos a buscar en TMDB: 2591
Pendientes: 2591
  [25/2591]
  [50/2591]
  [75/2591]
  [100/2591]
  [125/2591]
  [150/2591]
  [175/2591]
  [200/2591]
  [225/2591]
  [250/2591]
  [275/2591]
  [300/2591]
  [325/2591]
  [350/2591]
  [375/2591]
  [400/2591]
  [425/2591]
  [450/2591]
  [475/2591]
  [500/2591]
  [525/2591]
  [550/2591]
  [575/2591]
  [600/2591]
  [625/2591]
  [650/2591]
  [675/2591]
  [700/2591]
  [725/2591]
  [750/2591]
  [775/2591]
  [800/2591]
  [825/2591]
  [850/2591]
  [875/2591]
  [900/2591]
  [925/2591]
  [950/2591]
  [975/2591]
  [1000/2591]
  [1025/2591]
  [1050/2591]
  [1075/2591]
  [1100/2591]
  [1125/2591]
  [1150/2591]
  [1175/2591]
  [1200/2591]
  [1225/2591]
  [1250/2591]
  [1275/2591]
  [1300/2591]
  [1325/2591]
  [1350/2591]
  [1375/2591]
  [1400/2591]
  [1425/2591]
  [1450/2591]
  [1475/2591]
  [1500/2591]
  [1525/2591]
  [1550/2591]
  [1575/2591]
  [1600/2591]
  [1625/2591]
  [1650/2591]
  [1675/2591]
  [1700/2591]
  [1725/2591]
  [1750/2591]
  [1775/2591]
  [1800/2591]
  [1825/2591]
  [1850/2591]
  [1875/2591]
  [1900/2591]
  [1925/2591]
  [1950/2591]
  [1975/2591]
  [2000/2591]
  [2025/2591]
  [2050/2591]
  [2075/2591]
  [2100/2591]
  [2125/2591]
  [2150/2591]
  [2175/2591]
  [2200/2591]
  [2225/2591]
  [2250/2591]
  [2275/2591]
  [2300/2591]
  [2325/2591]
  [2350/2591]
  [2375/2591]
  [2400/2591]
  [2425/2591]
  [2450/2591]
  [2475/2591]
  [2500/2591]
  [2525/2591]
  [2550/2591]
  [2575/2591]
✓ Búsqueda de persona por nombre completada

In [18]:
def resolver_person_id(row):
    if pd.notna(row.get('person_id_tmdb')):
        return row['person_id_tmdb'], 'directo'
    match = person_search_cache.get(row['nombre'], {})
    pid = match.get('person_id')
    if pid is None:
        return None, None
    coincide = normalizar_texto(match.get('nombre_tmdb')) == normalizar_texto(row['nombre'])
    return pid, ('busqueda_nombre_exacta' if coincide else 'busqueda_nombre_aproximada')

resueltos = credits_df.apply(resolver_person_id, axis=1, result_type='expand')
credits_df['person_id'] = resueltos[0]
credits_df['metodo_match_persona'] = resueltos[1]

print(credits_df['metodo_match_persona'].value_counts(dropna=False))
print(f"\nCréditos con person_id resuelto: {credits_df['person_id'].notna().sum()} / {len(credits_df)}")
print("⚠ Revisar manualmente los 'busqueda_nombre_aproximada' -- el match no es exacto")

metodo_match_persona
busqueda_nombre_exacta        3935
NaN                            637
busqueda_nombre_aproximada     312
directo                        275
Name: count, dtype: int64

Créditos con person_id resuelto: 4522 / 5159
⚠ Revisar manualmente los 'busqueda_nombre_aproximada' -- el match no es exacto

In [19]:
credits_df[credits_df['metodo_match_persona'] == 'busqueda_nombre_aproximada']

,icaa_id,tmdb_id,rol,nombre,person_id_tmdb,fuente_credito,person_id,metodo_match_persona
13,100920.0,None,guionista,José Ramón Fernández,None,icaa,4748222.0,busqueda_nombre_aproximada
14,101120.0,None,director,César Souto,None,icaa,2434913.0,busqueda_nombre_aproximada
15,101120.0,None,guionista,César Souto,None,icaa,2434913.0,busqueda_nombre_aproximada
16,101120.0,None,guionista,Cristina Liz,None,icaa,2434919.0,busqueda_nombre_aproximada
17,101222.0,None,director,Eloy Calvo Campos,None,icaa,2839650.0,busqueda_nombre_aproximada
...,...,...,...,...,...,...,...,...
4783,96020.0,None,guionista,Alba Cros Pellisé,None,icaa,1524680.0,busqueda_nombre_aproximada
4837,98520.0,None,director,Alejandro Alvarado Jódar,None,icaa,1172340.0,busqueda_nombre_aproximada
4838,98520.0,None,director,Concha Barquero Artés,None,icaa,1172339.0,busqueda_nombre_aproximada
4839,98520.0,None,guionista,Alejandro Alvarado Jódar,None,icaa,1172340.0,busqueda_nombre_aproximada
4840,98520.0,None,guionista,Concha Barquero Artés,None,icaa,1172339.0,busqueda_nombre_aproximada

### Revisiones manuales

In [20]:
aproximados_unicos = (
    credits_df[credits_df['metodo_match_persona'] == 'busqueda_nombre_aproximada']
    [['nombre', 'person_id']]
    .drop_duplicates()
    .sort_values('nombre')
)
print(f"# {len(aproximados_unicos)} nombres únicos con match aproximado -- rellena el person_id "
      "correcto o deja None para descartar el match (la persona queda sin sexo/país)")
print("OVERRIDES_PERSON_SEARCH = {")
for _, fila in aproximados_unicos.iterrows():
    nombre_icaa = fila['nombre']
    match = person_search_cache.get(nombre_icaa, {})
    nombre_tmdb = match.get('nombre_tmdb')
    print(f"    {nombre_icaa!r}: None,  # TMDB propuso: {nombre_tmdb!r} (person_id={int(fila['person_id'])})")
print("}")

# 192 nombres únicos con match aproximado -- rellena el person_id correcto o deja None para descartar el match (la persona queda sin sexo/país)
OVERRIDES_PERSON_SEARCH = {
    'Adolfo Dufour Andia': None,  # TMDB propuso: 'Adolfo Dufour' (person_id=1413007)
    'Agustí Villaronga Riutort': None,  # TMDB propuso: 'Agustí Villaronga' (person_id=151162)
    'Aina Calleja Cortés': None,  # TMDB propuso: 'Aina Calleja' (person_id=1182523)
    'Aitor González De Langarica': None,  # TMDB propuso: 'Aitor González de Langarica Mendizabal' (person_id=3235428)
    'Aizea Roca': None,  # TMDB propuso: 'Aizea Roca Berridi' (person_id=4999905)
    'Alba Cros Pellisé': None,  # TMDB propuso: 'Alba Cros' (person_id=1524680)
    'Albert Bertran': None,  # TMDB propuso: 'Albert Bertran Bas' (person_id=4044587)
    'Albert Solé Bruset': None,  # TMDB propuso: 'Albert Solé' (person_id=1088457)
    'Alberto Armas': None,  # TMDB propuso: 'Alberto Armas Díaz' (person_id=2998049)
    'Alberto Rodríguez': None,  # TMDB propuso: 'Alberto Mimbrera Rodríguez' (person_id=5652588)
    'Alberto Vázquez Rico': None,  # TMDB propuso: 'Alberto Vázquez' (person_id=1515828)
    'Alejandro Alvarado Jódar': None,  # TMDB propuso: 'Alejandro Alvarado' (person_id=1172340)
    'Alejandro Blasco': None,  # TMDB propuso: 'Alejandro Marzoa Blasco' (person_id=1161119)
    'Alejandro Mateos': None,  # TMDB propuso: 'Alex Mateos' (person_id=4346432)
    'Alexandre Cirici-Pellicer': None,  # TMDB propuso: 'Alexandre Cirici Pellicer' (person_id=1877869)
    'Alfonso Suarez Suarez': None,  # TMDB propuso: 'Alfonso Suárez' (person_id=1121370)
    'Alfonso Suárez Suárez': None,  # TMDB propuso: 'Alfonso Suárez' (person_id=1121370)
    'Alfred Pérez Fargas': None,  # TMDB propuso: 'Alfred Pérez-Fargas' (person_id=1489447)
    'Alfredo Carrasco': None,  # TMDB propuso: 'Alfredo Carrasco Alonso' (person_id=3574547)
    'Ana Lambarri Tellaeche': None,  # TMDB propuso: 'Ana Lambarri' (person_id=2836489)
    'Andres Koppel': None,  # TMDB propuso: 'Andrés M. Koppel' (person_id=67263)
    'Angeles González Sinde': None,  # TMDB propuso: 'Ángeles González-Sinde' (person_id=230209)
    'Antonio Gimenez-Rico': None,  # TMDB propuso: 'Antonio Giménez Rico' (person_id=565852)
    'Antonio Giménez-Rico': None,  # TMDB propuso: 'Antonio Giménez Rico' (person_id=565852)
    'Antonio Mas-Guindal': None,  # TMDB propuso: 'Antonio Mas Guindal' (person_id=1173027)
    'Antonio Mercero Santos': None,  # TMDB propuso: 'Santos Mercero' (person_id=1451411)
    'Arantxa Aguirre Carballeira': None,  # TMDB propuso: 'Arantxa Aguirre' (person_id=1047274)
    'Ariadna Fortuny Cardona': None,  # TMDB propuso: 'Ariadna Fortuny' (person_id=3960226)
    'Arturo Dueñas Herrero': None,  # TMDB propuso: 'Arturo Dueñas' (person_id=2826886)
    'Arturo Pérez Reverte': None,  # TMDB propuso: 'Arturo Pérez-Reverte' (person_id=8908)
    'Augusto Martínez Torres': None,  # TMDB propuso: 'Augusto M. Torres' (person_id=37515)
    'Azucena Rodríguez': None,  # TMDB propuso: 'Azucena Carbajosa Rodriguez' (person_id=5421335)
    'Belén Sánchez-Arévalo': None,  # TMDB propuso: 'Belén Sánchez Arévalo' (person_id=2406756)
    'Beñat Gereka': None,  # TMDB propuso: 'Beñat Gereka Bikuña' (person_id=5718669)
    'Bianca Franceza': None,  # TMDB propuso: 'Bianca Franceza Omonte' (person_id=4543717)
    'Burnin´ Percebes': None,  # TMDB propuso: "Burnin' Percebes" (person_id=1395595)
    'Carlos Marqués Marcet': None,  # TMDB propuso: 'Carlos Marques-Marcet' (person_id=1288697)
    'Carlos Therón': None,  # TMDB propuso: 'Carlos Therón Sánchez' (person_id=588816)
    'Carmen López-Areal': None,  # TMDB propuso: 'Carmen López Areal' (person_id=2033131)
    'Carmina Balaguer Montón': None,  # TMDB propuso: 'Carmina Balaguer' (person_id=3698547)
    'Casandra Macías': None,  # TMDB propuso: 'Casandra Macías Gago' (person_id=1360059)
    'Celia Rico': None,  # TMDB propuso: 'Celia Rico Clavellino' (person_id=1384823)
    'Chumilla-Carbajosa': None,  # TMDB propuso: 'Juan Manuel Chumilla-Carbajosa' (person_id=1168983)
    'Clara Martínez-Lázaro': None,  # TMDB propuso: 'Clara Martínez-Lázaro Alameda' (person_id=1521812)
    'Concha Barquero Artés': None,  # TMDB propuso: 'Concha Barquero' (person_id=1172339)
    'Cris Liz': None,  # TMDB propuso: 'Cris Lizarraga' (person_id=4266018)
    'Cristina Hernández-Carrillo': None,  # TMDB propuso: 'Cristina Hernández-Carrillo de la Higuera' (person_id=2969632)
    'Cristina Liz': None,  # TMDB propuso: 'Cristina Liz Graña' (person_id=2434919)
    'Cristina Menéndez': None,  # TMDB propuso: 'Cristina Menéndez Torralba' (person_id=5181798)
    'Cristóbal Fernández Fernández': None,  # TMDB propuso: 'Cristóbal Fernández' (person_id=1817389)
    'Curro Sánchez Varela': None,  # TMDB propuso: 'Francisco Sánchez Varela' (person_id=1373415)
    'César Souto': None,  # TMDB propuso: 'César Souto Vilanova' (person_id=2434913)
    'Dani Alonso': None,  # TMDB propuso: 'Daniel Alonso Castelo' (person_id=3343684)
    'Darío García García': None,  # TMDB propuso: 'Darío García Sanz' (person_id=5775607)
    'David Martín-Porras': None,  # TMDB propuso: 'David Martín Porras' (person_id=1264790)
    'David Orea Arribas': None,  # TMDB propuso: 'David Orea' (person_id=2747679)
    'David R. Ros': None,  # TMDB propuso: 'D. Ross Lederman' (person_id=111462)
    'Eduardo Sola': None,  # TMDB propuso: 'Eduardo Solá Franco' (person_id=1958700)
    'Elena Cid': None,  # TMDB propuso: 'Elena Cid Sebastián' (person_id=2297013)
    'Eligio Montero': None,  # TMDB propuso: 'Eligio R. Montero' (person_id=1843397)
    'Eloy Calvo Campos': None,  # TMDB propuso: 'Eloy Calvo' (person_id=2839650)
    'Emanuele Giusto': None,  # TMDB propuso: 'Emanuele Giusto Kantfish' (person_id=4980450)
    'Enrique Iznaola': None,  # TMDB propuso: 'Enrique Iznaola Gómez' (person_id=4580247)
    'Enrique Palacio': None,  # TMDB propuso: 'Carlos Enrique Palacio' (person_id=5307851)
    'Eric Navarro Serna': None,  # TMDB propuso: 'Eric Navarro' (person_id=1302760)
    'Esther Díaz': None,  # TMDB propuso: 'Esther Díaz Rey' (person_id=6389807)
    'Fernando Fernán-Gómez': None,  # TMDB propuso: 'Fernando Fernán Gómez' (person_id=965)
    'Francesca Catalá': None,  # TMDB propuso: 'Francesca Català Margarit' (person_id=2631444)
    'Francisco Vaquero': None,  # TMDB propuso: 'Francisco Vaquero Robustillo' (person_id=4056738)
    'Fèlix Colomer': None,  # TMDB propuso: 'Fèlix Colomer Vallès' (person_id=1835536)
    'Gaspar Broullón': None,  # TMDB propuso: 'Gaspar Broullón Pastoriza' (person_id=5046087)
    'Gon': None,  # TMDB propuso: 'Melo Gon' (person_id=3702941)
    'Gonzalo García Pelayo': None,  # TMDB propuso: 'Gonzalo García-Pelayo' (person_id=1152112)
    'Gonzalo Perdomo - Tafur': None,  # TMDB propuso: 'Gonzalo Perdomo-Tafur' (person_id=5052862)
    'Guillermo Guerrero Conget': None,  # TMDB propuso: 'Guillermo Guerrero' (person_id=1608135)
    'Gustau Hernández': None,  # TMDB propuso: 'Gustau Hernández Mor' (person_id=1361408)
    'Ibán Toledo': None,  # TMDB propuso: 'Iban Toledo Ibañez' (person_id=2218256)
    'Ignacio F Iquino': None,  # TMDB propuso: 'Ignacio F. Iquino' (person_id=53943)
    'Ignacio Ortega': None,  # TMDB propuso: 'Ignacio Ortega Campos' (person_id=4580248)
    'Imanol Ortiz': None,  # TMDB propuso: 'Imanol Ortiz López' (person_id=1804069)
    'Inge Mendioroz Ibáñez': None,  # TMDB propuso: 'Inge Mendioroz' (person_id=2468094)
    'Irati Gorostidi Agirretxe': None,  # TMDB propuso: 'Irati Gorostidi' (person_id=1708407)
    'Irene Gutiérrez': None,  # TMDB propuso: 'Irene Gutiérrez Caba' (person_id=548748)
    'Isabel Peña Domingo': None,  # TMDB propuso: 'Isabel Peña' (person_id=1303404)
    'Isaías Cruz': None,  # TMDB propuso: 'Isaías Cruz Irujo' (person_id=5338995)
    'Ivy Hes': None,  # TMDB propuso: 'Ivy Hesh' (person_id=5086132)
    "J. J. García Galocha 'Galo'": None,  # TMDB propuso: 'Juan Jesús García Galocha' (person_id=2044869)
    'J. L. Rojas': None,  # TMDB propuso: 'J.L. Rojas' (person_id=5252601)
    'J.A Bayona': None,  # TMDB propuso: 'J. A. Bayona' (person_id=51894)
    'Jaime Comas': None,  # TMDB propuso: 'Jaime Comas Gil' (person_id=16320)
    'Jaione Camborda Coll': None,  # TMDB propuso: 'Jaione Camborda' (person_id=1836299)
    'Javier Barreira': None,  # TMDB propuso: 'Javier López Barreira' (person_id=1133344)
    'Javier Martín Martín': None,  # TMDB propuso: 'Javier Martín' (person_id=576087)
    'Javier Martínez': None,  # TMDB propuso: 'Javier Sánchez Martínez' (person_id=5348288)
    'Jerónimo Silvio Iglesias': None,  # TMDB propuso: 'Jerónimo Silvio Iglesias Aparicio' (person_id=3511155)
    'Jone Ibarretxe': None,  # TMDB propuso: 'Jone Ibarretxe de la Cal' (person_id=4919663)
    'Jordi Morató': None,  # TMDB propuso: 'Jordi Morató Pujol' (person_id=5729075)
    'Jorge Acebo': None,  # TMDB propuso: 'Jorge Acebo Canedo' (person_id=2570550)
    'Jorge Peña': None,  # TMDB propuso: 'Jorge Peña Pezo' (person_id=5834871)
    'Jose Garci': None,  # TMDB propuso: 'José Luis Garci' (person_id=103511)
    'Jose Luis Luis Font': None,  # TMDB propuso: 'José Luis Font' (person_id=143847)
    'Jose Maria Rodriguez': None,  # TMDB propuso: 'Maria Jose Pacreu Rodriguez' (person_id=5322138)
    'Josema García-Pelayo': None,  # TMDB propuso: 'Josema García Pelayo' (person_id=3511158)
    'Josep T. París': None,  # TMDB propuso: 'Josep T.París' (person_id=5377723)
    'Joserra Halcón': None,  # TMDB propuso: 'Joserra Halcón Bejarano' (person_id=1809334)
    'José A. Torres': None,  # TMDB propuso: 'Antonio Torres Martinó' (person_id=1593605)
    'José Juan Bigas Luna': None,  # TMDB propuso: 'Bigas Luna' (person_id=37577)
    'José Ramón Fernández': None,  # TMDB propuso: 'Jose Ramón Fernández Pinazo' (person_id=4748222)
    'José Sánchez Montes': None,  # TMDB propuso: 'José Sánchez-Montes' (person_id=1065244)
    'Juan Antonio Moreno': None,  # TMDB propuso: 'Juan Antonio Moreno Amador' (person_id=1463084)
    "Juan Jesús García 'Galo'": None,  # TMDB propuso: 'Juan Jesús García Galocha' (person_id=2044869)
    'Juan Prosper': None,  # TMDB propuso: 'Juan Clemente Prosper' (person_id=1564500)
    'Juan Pérez-Fajardo': None,  # TMDB propuso: 'Juan Perez Fajardo' (person_id=3960733)
    'Juanfran Jacinto': None,  # TMDB propuso: 'Juan Fran Jacinto' (person_id=2385196)
    'Juanjo Giménez': None,  # TMDB propuso: 'Juanjo Giménez Peña' (person_id=1459948)
    'Juanma Betancort': None,  # TMDB propuso: 'Juanma Villar Betancort' (person_id=1866952)
    'Julio C. Sánchez': None,  # TMDB propuso: 'Julio César Sánchez' (person_id=2427245)
    'Julio De La Fuente': None,  # TMDB propuso: 'Julio S. de la Fuente' (person_id=4865414)
    'Leone Sergio': None,  # TMDB propuso: 'Sergio Leone' (person_id=4385)
    'Li Jianping': None,  # TMDB propuso: 'Jianping Li' (person_id=3000259)
    'Liena Cid': None,  # TMDB propuso: 'Liena Cid Navia' (person_id=5318950)
    'Lisanda López Fabé': None,  # TMDB propuso: 'Lisandra López Fabe' (person_id=2799326)
    'Lluís Miñarro': None,  # TMDB propuso: 'Luis Miñarro' (person_id=28503)
    'Lola Maldonado Salvador': None,  # TMDB propuso: 'Lola Salvador' (person_id=1871730)
    'Lola Salvador Maldonado': None,  # TMDB propuso: 'Lola Salvador' (person_id=1871730)
    'Louise Andersen': None,  # TMDB propuso: 'Louise Brix Andersen' (person_id=5228746)
    'Lucía Casañ': None,  # TMDB propuso: 'Lucía Casañ Rodríguez' (person_id=4776926)
    'Lucía Herrera Pérez': None,  # TMDB propuso: 'Lucía Herrera' (person_id=3374272)
    'Luis Acebes': None,  # TMDB propuso: 'Luis Acebes Navarro' (person_id=2710782)
    'Luis Alegre': None,  # TMDB propuso: 'Luis Alegre Saz' (person_id=1074041)
    'Luis Gabriel Beristáin': None,  # TMDB propuso: 'Gabriel Beristain' (person_id=10832)
    'Luis Garcia-Berlanga': None,  # TMDB propuso: 'Luis García Berlanga' (person_id=37493)
    'Luis Muñoz Cubillo': None,  # TMDB propuso: 'Luis (Soto) Muñoz' (person_id=3829133)
    'Luis Peñafiel': None,  # TMDB propuso: 'Chicho Ibáñez Serrador' (person_id=133004)
    'Luis Sánchez-Polack': None,  # TMDB propuso: 'Luis Sánchez Polack' (person_id=232130)
    'Luisa García Grajalva': None,  # TMDB propuso: 'Luisa García-Grajalva' (person_id=3564092)
    'Luisa Grajalva': None,  # TMDB propuso: 'Luisa García-Grajalva' (person_id=3564092)
    'Manuel Burque Hodgson': None,  # TMDB propuso: 'Manuel Burque' (person_id=1434231)
    'Manuel Cabo': None,  # TMDB propuso: 'Manuel Cabo Sánchez' (person_id=5331869)
    'Manuel Martínez Velasco': None,  # TMDB propuso: 'Manuel M. Velasco' (person_id=1195190)
    'Mar De Dios Rodríguez': None,  # TMDB propuso: 'María del Mar de Dios Rodríguez' (person_id=5122410)
    'Marc Sempere Moya': None,  # TMDB propuso: 'Marc Sempere-Moya' (person_id=3268460)
    'Margarita Ledo Andión': None,  # TMDB propuso: 'Margarita Ledo' (person_id=2348612)
    'Mariano Ozores': None,  # TMDB propuso: 'Mariano Ozores Puchol' (person_id=229765)
    'Mariano Rojo': None,  # TMDB propuso: 'Mariano Alejandro Rojo' (person_id=4475946)
    'Marta-Libertad': None,  # TMDB propuso: 'Marta-Libertad Castillo' (person_id=2654024)
    'Michael White': None,  # TMDB propuso: 'Michael Jai White' (person_id=64856)
    'Miguel Angel Trujillo': None,  # TMDB propuso: 'Miguel Angel Bonequi Trujillo' (person_id=2927784)
    'Miguel Herrero Herrero': None,  # TMDB propuso: 'Miguel Herrero' (person_id=4951153)
    'Miguel Mejías': None,  # TMDB propuso: 'Miguel A. Mejias' (person_id=2760432)
    'Miguel Ángel Barroso': None,  # TMDB propuso: 'Miguel Angel Barroso Garcia' (person_id=2764547)
    'Miguel Ángel Vivas Moreno': None,  # TMDB propuso: 'Miguel Ángel Vivas' (person_id=140396)
    'Mikel Mas': None,  # TMDB propuso: 'Mikel Mas Bilbao' (person_id=3212690)
    'Monso': None,  # TMDB propuso: 'Percy Monso' (person_id=6371154)
    'Mónica Cambra Domínguez': None,  # TMDB propuso: 'Mònica Cambra' (person_id=2661260)
    'Nicolás Muñoz Avia': None,  # TMDB propuso: 'Nicolás Muñoz' (person_id=260953)
    'Nino Fontán': None,  # TMDB propuso: 'Nino Fontán Allen' (person_id=4919676)
    'Pablo Hernando Esquisabel': None,  # TMDB propuso: 'Pablo Hernando' (person_id=1185975)
    'Pau Canivell Gámez': None,  # TMDB propuso: 'Pau Canivell' (person_id=3304976)
    'Pau García Pérez De Lara': None,  # TMDB propuso: 'Pablo García Pérez de Lara' (person_id=1013025)
    'Paul Urkijo': None,  # TMDB propuso: 'Paul Urkijo Alijo' (person_id=1428818)
    'Pawel Pawlikowski': None,  # TMDB propuso: 'Paweł Pawlikowski' (person_id=64194)
    'Pedro Martín-Calero': None,  # TMDB propuso: 'Pedro Martín Calero' (person_id=1694893)
    'Pedro Pérez-Rosado': None,  # TMDB propuso: 'Pedro Pérez Rosado' (person_id=1036769)
    'Pello Gutiérrez Peñalba': None,  # TMDB propuso: 'Pello Gutiérrez' (person_id=2261544)
    'Phil Ivanusic-Vallée': None,  # TMDB propuso: 'Phil Ivanusic' (person_id=1246601)
    'Rafael Calatayud Cano': None,  # TMDB propuso: 'Rafa Calatayud Cano' (person_id=4223120)
    'Rafael G. Sánchez': None,  # TMDB propuso: 'Rafael Sánchez G.' (person_id=4603658)
    'Rafael J Salvia': None,  # TMDB propuso: 'Rafael J. Salvia' (person_id=98499)
    'Rafael Torrecilla': None,  # TMDB propuso: 'Rafael María Torrecilla' (person_id=1269221)
    'Ray(Jorge Loriga) Loriga': None,  # TMDB propuso: 'Ray Loriga' (person_id=3790)
    'Samuel Martín Delgado': None,  # TMDB propuso: 'Samuel M. Delgado' (person_id=1539731)
    'Santos Blanco': None,  # TMDB propuso: 'Blanco Santos' (person_id=1828428)
    'Sean Patrick O´Reilly': None,  # TMDB propuso: "Sean Patrick O'Reilly" (person_id=131416)
    'Sergio Montero': None,  # TMDB propuso: 'Sergio Montero Fernández' (person_id=5070921)
    'Sergio Rodrigo': None,  # TMDB propuso: 'Sergio Rodrigo Ruiz' (person_id=5503054)
    'Stojan Ðordevic': None,  # TMDB propuso: 'Stojan Đorđević' (person_id=1593464)
    'Tabatta Salinas': None,  # TMDB propuso: 'Tabatta Salinas Caballero' (person_id=4206690)
    'Tomás Aceituno': None,  # TMDB propuso: 'Tomás Aceituno Maldonado' (person_id=1458492)
    'Venci D. Kostov': None,  # TMDB propuso: 'Venci Kostov' (person_id=2192826)
    'Víctor Alonso Berbel': None,  # TMDB propuso: 'Victor Alonso-Berbel' (person_id=2334053)
    'Wang Xianping': None,  # TMDB propuso: 'Xianping Wang' (person_id=2266640)
    'Xabier Mina': None,  # TMDB propuso: 'Xabier Mina Ederra' (person_id=5338994)
    'Xavier Esteban': None,  # TMDB propuso: 'Xavier Esteban Casas' (person_id=3947595)
    'Xavier Torres Lliteras': None,  # TMDB propuso: 'Xavi Torres' (person_id=4034117)
    'Álex O´Dogherty': None,  # TMDB propuso: "Álex O'Dogherty" (person_id=1061514)
    'Álvaro Fernández - Armero': None,  # TMDB propuso: 'Álvaro Fernández Armero' (person_id=563824)
    'Álvaro Lión-Depetre': None,  # TMDB propuso: 'Álvaro Lion Depetre' (person_id=2014388)
    'Ángel Alonso': None,  # TMDB propuso: 'Miguel Ángel Alonso' (person_id=5115816)
    'Ángel Puado': None,  # TMDB propuso: 'Ángel Puado Veloso' (person_id=2864402)
    'Ángela Gallardo': None,  # TMDB propuso: 'Ángela Gallardo Bernal' (person_id=1649980)
    'Ángeles González-Sinde Reig': None,  # TMDB propuso: 'Ángeles González-Sinde' (person_id=230209)
}

In [21]:
# 192 nombres únicos con match aproximado -- rellena el person_id correcto o deja None para descartar el match (la persona queda sin sexo/país)
OVERRIDES_PERSON_SEARCH = {
    'Adolfo Dufour Andia': None,  # TMDB propuso: 'Adolfo Dufour' (person_id=1413007)
    'Agustí Villaronga Riutort': None,  # TMDB propuso: 'Agustí Villaronga' (person_id=151162)
    'Aina Calleja Cortés': None,  # TMDB propuso: 'Aina Calleja' (person_id=1182523)
    'Aitor González De Langarica': None,  # TMDB propuso: 'Aitor González de Langarica Mendizabal' (person_id=3235428)
    'Aizea Roca': None,  # TMDB propuso: 'Aizea Roca Berridi' (person_id=4999905)
    'Alba Cros Pellisé': None,  # TMDB propuso: 'Alba Cros' (person_id=1524680)
    'Albert Bertran': None,  # TMDB propuso: 'Albert Bertran Bas' (person_id=4044587)
    'Albert Solé Bruset': None,  # TMDB propuso: 'Albert Solé' (person_id=1088457)
    'Alberto Armas': None,  # TMDB propuso: 'Alberto Armas Díaz' (person_id=2998049)
    'Alberto Rodríguez': 6521,  # TMDB propuso: 'Alberto Mimbrera Rodríguez' (person_id=5652588)
    'Alberto Vázquez Rico': None,  # TMDB propuso: 'Alberto Vázquez' (person_id=1515828)
    'Alejandro Alvarado Jódar': None,  # TMDB propuso: 'Alejandro Alvarado' (person_id=1172340)
    'Alejandro Blasco': None,  # TMDB propuso: 'Alejandro Marzoa Blasco' (person_id=1161119)
    'Alejandro Mateos': None,  # TMDB propuso: 'Alex Mateos' (person_id=4346432)
    'Alexandre Cirici-Pellicer': None,  # TMDB propuso: 'Alexandre Cirici Pellicer' (person_id=1877869)
    'Alfonso Suarez Suarez': None,  # TMDB propuso: 'Alfonso Suárez' (person_id=1121370)
    'Alfonso Suárez Suárez': None,  # TMDB propuso: 'Alfonso Suárez' (person_id=1121370)
    'Alfred Pérez Fargas': None,  # TMDB propuso: 'Alfred Pérez-Fargas' (person_id=1489447)
    'Alfredo Carrasco': None,  # TMDB propuso: 'Alfredo Carrasco Alonso' (person_id=3574547)
    'Ana Lambarri Tellaeche': None,  # TMDB propuso: 'Ana Lambarri' (person_id=2836489)
    'Andres Koppel': None,  # TMDB propuso: 'Andrés M. Koppel' (person_id=67263)
    'Angeles González Sinde': None,  # TMDB propuso: 'Ángeles González-Sinde' (person_id=230209)
    'Antonio Gimenez-Rico': None,  # TMDB propuso: 'Antonio Giménez Rico' (person_id=565852)
    'Antonio Giménez-Rico': None,  # TMDB propuso: 'Antonio Giménez Rico' (person_id=565852)
    'Antonio Mas-Guindal': None,  # TMDB propuso: 'Antonio Mas Guindal' (person_id=1173027)
    'Antonio Mercero Santos': None,  # TMDB propuso: 'Santos Mercero' (person_id=1451411)
    'Arantxa Aguirre Carballeira': None,  # TMDB propuso: 'Arantxa Aguirre' (person_id=1047274)
    'Ariadna Fortuny Cardona': None,  # TMDB propuso: 'Ariadna Fortuny' (person_id=3960226)
    'Arturo Dueñas Herrero': None,  # TMDB propuso: 'Arturo Dueñas' (person_id=2826886)
    'Arturo Pérez Reverte': None,  # TMDB propuso: 'Arturo Pérez-Reverte' (person_id=8908)
    'Augusto Martínez Torres': None,  # TMDB propuso: 'Augusto M. Torres' (person_id=37515)
    'Azucena Rodríguez': None,  # TMDB propuso: 'Azucena Carbajosa Rodriguez' (person_id=5421335)
    'Belén Sánchez-Arévalo': None,  # TMDB propuso: 'Belén Sánchez Arévalo' (person_id=2406756)
    'Beñat Gereka': None,  # TMDB propuso: 'Beñat Gereka Bikuña' (person_id=5718669)
    'Bianca Franceza': None,  # TMDB propuso: 'Bianca Franceza Omonte' (person_id=4543717)
    'Burnin´ Percebes': None,  # TMDB propuso: "Burnin' Percebes" (person_id=1395595)
    'Carlos Marqués Marcet': None,  # TMDB propuso: 'Carlos Marques-Marcet' (person_id=1288697)
    'Carlos Therón': None,  # TMDB propuso: 'Carlos Therón Sánchez' (person_id=588816)
    'Carmen López-Areal': None,  # TMDB propuso: 'Carmen López Areal' (person_id=2033131)
    'Carmina Balaguer Montón': None,  # TMDB propuso: 'Carmina Balaguer' (person_id=3698547)
    'Casandra Macías': None,  # TMDB propuso: 'Casandra Macías Gago' (person_id=1360059)
    'Celia Rico': None,  # TMDB propuso: 'Celia Rico Clavellino' (person_id=1384823)
    'Chumilla-Carbajosa': None,  # TMDB propuso: 'Juan Manuel Chumilla-Carbajosa' (person_id=1168983)
    'Clara Martínez-Lázaro': None,  # TMDB propuso: 'Clara Martínez-Lázaro Alameda' (person_id=1521812)
    'Concha Barquero Artés': None,  # TMDB propuso: 'Concha Barquero' (person_id=1172339)
    'Cris Liz': None,  # TMDB propuso: 'Cris Lizarraga' (person_id=4266018)
    'Cristina Hernández-Carrillo': None,  # TMDB propuso: 'Cristina Hernández-Carrillo de la Higuera' (person_id=2969632)
    'Cristina Liz': None,  # TMDB propuso: 'Cristina Liz Graña' (person_id=2434919)
    'Cristina Menéndez': None,  # TMDB propuso: 'Cristina Menéndez Torralba' (person_id=5181798)
    'Cristóbal Fernández Fernández': None,  # TMDB propuso: 'Cristóbal Fernández' (person_id=1817389)
    'Curro Sánchez Varela': None,  # TMDB propuso: 'Francisco Sánchez Varela' (person_id=1373415)
    'César Souto': None,  # TMDB propuso: 'César Souto Vilanova' (person_id=2434913)
    'Dani Alonso': None,  # TMDB propuso: 'Daniel Alonso Castelo' (person_id=3343684)
    'Darío García García': None,  # TMDB propuso: 'Darío García Sanz' (person_id=5775607)
    'David Martín-Porras': None,  # TMDB propuso: 'David Martín Porras' (person_id=1264790)
    'David Orea Arribas': None,  # TMDB propuso: 'David Orea' (person_id=2747679)
    'David R. Ros': None,  # TMDB propuso: 'D. Ross Lederman' (person_id=111462)
    'Eduardo Sola': None,  # TMDB propuso: 'Eduardo Solá Franco' (person_id=1958700)
    'Elena Cid': None,  # TMDB propuso: 'Elena Cid Sebastián' (person_id=2297013)
    'Eligio Montero': None,  # TMDB propuso: 'Eligio R. Montero' (person_id=1843397)
    'Eloy Calvo Campos': None,  # TMDB propuso: 'Eloy Calvo' (person_id=2839650)
    'Emanuele Giusto': None,  # TMDB propuso: 'Emanuele Giusto Kantfish' (person_id=4980450)
    'Enrique Iznaola': None,  # TMDB propuso: 'Enrique Iznaola Gómez' (person_id=4580247)
    'Enrique Palacio': None,  # TMDB propuso: 'Carlos Enrique Palacio' (person_id=5307851)
    'Eric Navarro Serna': None,  # TMDB propuso: 'Eric Navarro' (person_id=1302760)
    'Esther Díaz': None,  # TMDB propuso: 'Esther Díaz Rey' (person_id=6389807)
    'Fernando Fernán-Gómez': None,  # TMDB propuso: 'Fernando Fernán Gómez' (person_id=965)
    'Francesca Catalá': None,  # TMDB propuso: 'Francesca Català Margarit' (person_id=2631444)
    'Francisco Vaquero': None,  # TMDB propuso: 'Francisco Vaquero Robustillo' (person_id=4056738)
    'Fèlix Colomer': None,  # TMDB propuso: 'Fèlix Colomer Vallès' (person_id=1835536)
    'Gaspar Broullón': None,  # TMDB propuso: 'Gaspar Broullón Pastoriza' (person_id=5046087)
    'Gon': None,  # TMDB propuso: 'Melo Gon' (person_id=3702941)
    'Gonzalo García Pelayo': None,  # TMDB propuso: 'Gonzalo García-Pelayo' (person_id=1152112)
    'Gonzalo Perdomo - Tafur': None,  # TMDB propuso: 'Gonzalo Perdomo-Tafur' (person_id=5052862)
    'Guillermo Guerrero Conget': None,  # TMDB propuso: 'Guillermo Guerrero' (person_id=1608135)
    'Gustau Hernández': None,  # TMDB propuso: 'Gustau Hernández Mor' (person_id=1361408)
    'Ibán Toledo': None,  # TMDB propuso: 'Iban Toledo Ibañez' (person_id=2218256)
    'Ignacio F Iquino': None,  # TMDB propuso: 'Ignacio F. Iquino' (person_id=53943)
    'Ignacio Ortega': None,  # TMDB propuso: 'Ignacio Ortega Campos' (person_id=4580248)
    'Imanol Ortiz': None,  # TMDB propuso: 'Imanol Ortiz López' (person_id=1804069)
    'Inge Mendioroz Ibáñez': None,  # TMDB propuso: 'Inge Mendioroz' (person_id=2468094)
    'Irati Gorostidi Agirretxe': None,  # TMDB propuso: 'Irati Gorostidi' (person_id=1708407)
    'Irene Gutiérrez': None,  # TMDB propuso: 'Irene Gutiérrez Caba' (person_id=548748)
    'Isabel Peña Domingo': None,  # TMDB propuso: 'Isabel Peña' (person_id=1303404)
    'Isaías Cruz': None,  # TMDB propuso: 'Isaías Cruz Irujo' (person_id=5338995)
    'Ivy Hes': None,  # TMDB propuso: 'Ivy Hesh' (person_id=5086132)
    "J. J. García Galocha 'Galo'": None,  # TMDB propuso: 'Juan Jesús García Galocha' (person_id=2044869)
    'J. L. Rojas': None,  # TMDB propuso: 'J.L. Rojas' (person_id=5252601)
    'J.A Bayona': None,  # TMDB propuso: 'J. A. Bayona' (person_id=51894)
    'Jaime Comas': None,  # TMDB propuso: 'Jaime Comas Gil' (person_id=16320)
    'Jaione Camborda Coll': None,  # TMDB propuso: 'Jaione Camborda' (person_id=1836299)
    'Javier Barreira': None,  # TMDB propuso: 'Javier López Barreira' (person_id=1133344)
    'Javier Martín Martín': None,  # TMDB propuso: 'Javier Martín' (person_id=576087)
    'Javier Martínez': None,  # TMDB propuso: 'Javier Sánchez Martínez' (person_id=5348288)
    'Jerónimo Silvio Iglesias': None,  # TMDB propuso: 'Jerónimo Silvio Iglesias Aparicio' (person_id=3511155)
    'Jone Ibarretxe': None,  # TMDB propuso: 'Jone Ibarretxe de la Cal' (person_id=4919663)
    'Jordi Morató': None,  # TMDB propuso: 'Jordi Morató Pujol' (person_id=5729075)
    'Jorge Acebo': None,  # TMDB propuso: 'Jorge Acebo Canedo' (person_id=2570550)
    'Jorge Peña': None,  # TMDB propuso: 'Jorge Peña Pezo' (person_id=5834871)
    'Jose Garci': None,  # TMDB propuso: 'José Luis Garci' (person_id=103511)
    'Jose Luis Luis Font': None,  # TMDB propuso: 'José Luis Font' (person_id=143847)
    'Jose Maria Rodriguez': None,  # TMDB propuso: 'Maria Jose Pacreu Rodriguez' (person_id=5322138)
    'Josema García-Pelayo': None,  # TMDB propuso: 'Josema García Pelayo' (person_id=3511158)
    'Josep T. París': None,  # TMDB propuso: 'Josep T.París' (person_id=5377723)
    'Joserra Halcón': None,  # TMDB propuso: 'Joserra Halcón Bejarano' (person_id=1809334)
    'José A. Torres': None,  # TMDB propuso: 'Antonio Torres Martinó' (person_id=1593605)
    'José Juan Bigas Luna': None,  # TMDB propuso: 'Bigas Luna' (person_id=37577)
    'José Ramón Fernández': None,  # TMDB propuso: 'Jose Ramón Fernández Pinazo' (person_id=4748222)
    'José Sánchez Montes': None,  # TMDB propuso: 'José Sánchez-Montes' (person_id=1065244)
    'Juan Antonio Moreno': None,  # TMDB propuso: 'Juan Antonio Moreno Amador' (person_id=1463084)
    "Juan Jesús García 'Galo'": None,  # TMDB propuso: 'Juan Jesús García Galocha' (person_id=2044869)
    'Juan Prosper': None,  # TMDB propuso: 'Juan Clemente Prosper' (person_id=1564500)
    'Juan Pérez-Fajardo': None,  # TMDB propuso: 'Juan Perez Fajardo' (person_id=3960733)
    'Juanfran Jacinto': None,  # TMDB propuso: 'Juan Fran Jacinto' (person_id=2385196)
    'Juanjo Giménez': None,  # TMDB propuso: 'Juanjo Giménez Peña' (person_id=1459948)
    'Juanma Betancort': None,  # TMDB propuso: 'Juanma Villar Betancort' (person_id=1866952)
    'Julio C. Sánchez': None,  # TMDB propuso: 'Julio César Sánchez' (person_id=2427245)
    'Julio De La Fuente': None,  # TMDB propuso: 'Julio S. de la Fuente' (person_id=4865414)
    'Leone Sergio': None,  # TMDB propuso: 'Sergio Leone' (person_id=4385)
    'Li Jianping': None,  # TMDB propuso: 'Jianping Li' (person_id=3000259)
    'Liena Cid': None,  # TMDB propuso: 'Liena Cid Navia' (person_id=5318950)
    'Lisanda López Fabé': None,  # TMDB propuso: 'Lisandra López Fabe' (person_id=2799326)
    'Lluís Miñarro': None,  # TMDB propuso: 'Luis Miñarro' (person_id=28503)
    'Lola Maldonado Salvador': None,  # TMDB propuso: 'Lola Salvador' (person_id=1871730)
    'Lola Salvador Maldonado': None,  # TMDB propuso: 'Lola Salvador' (person_id=1871730)
    'Louise Andersen': None,  # TMDB propuso: 'Louise Brix Andersen' (person_id=5228746)
    'Lucía Casañ': None,  # TMDB propuso: 'Lucía Casañ Rodríguez' (person_id=4776926)
    'Lucía Herrera Pérez': None,  # TMDB propuso: 'Lucía Herrera' (person_id=3374272)
    'Luis Acebes': None,  # TMDB propuso: 'Luis Acebes Navarro' (person_id=2710782)
    'Luis Alegre': None,  # TMDB propuso: 'Luis Alegre Saz' (person_id=1074041)
    'Luis Gabriel Beristáin': None,  # TMDB propuso: 'Gabriel Beristain' (person_id=10832)
    'Luis Garcia-Berlanga': None,  # TMDB propuso: 'Luis García Berlanga' (person_id=37493)
    'Luis Muñoz Cubillo': None,  # TMDB propuso: 'Luis (Soto) Muñoz' (person_id=3829133)
    'Luis Peñafiel': None,  # TMDB propuso: 'Chicho Ibáñez Serrador' (person_id=133004)
    'Luis Sánchez-Polack': None,  # TMDB propuso: 'Luis Sánchez Polack' (person_id=232130)
    'Luisa García Grajalva': None,  # TMDB propuso: 'Luisa García-Grajalva' (person_id=3564092)
    'Luisa Grajalva': None,  # TMDB propuso: 'Luisa García-Grajalva' (person_id=3564092)
    'Manuel Burque Hodgson': None,  # TMDB propuso: 'Manuel Burque' (person_id=1434231)
    'Manuel Cabo': None,  # TMDB propuso: 'Manuel Cabo Sánchez' (person_id=5331869)
    'Manuel Martínez Velasco': None,  # TMDB propuso: 'Manuel M. Velasco' (person_id=1195190)
    'Mar De Dios Rodríguez': None,  # TMDB propuso: 'María del Mar de Dios Rodríguez' (person_id=5122410)
    'Marc Sempere Moya': None,  # TMDB propuso: 'Marc Sempere-Moya' (person_id=3268460)
    'Margarita Ledo Andión': None,  # TMDB propuso: 'Margarita Ledo' (person_id=2348612)
    'Mariano Ozores': None,  # TMDB propuso: 'Mariano Ozores Puchol' (person_id=229765)
    'Mariano Rojo': None,  # TMDB propuso: 'Mariano Alejandro Rojo' (person_id=4475946)
    'Marta-Libertad': None,  # TMDB propuso: 'Marta-Libertad Castillo' (person_id=2654024)
    'Michael White': None,  # TMDB propuso: 'Michael Jai White' (person_id=64856)
    'Miguel Angel Trujillo': None,  # TMDB propuso: 'Miguel Angel Bonequi Trujillo' (person_id=2927784)
    'Miguel Herrero Herrero': None,  # TMDB propuso: 'Miguel Herrero' (person_id=4951153)
    'Miguel Mejías': None,  # TMDB propuso: 'Miguel A. Mejias' (person_id=2760432)
    'Miguel Ángel Barroso': None,  # TMDB propuso: 'Miguel Angel Barroso Garcia' (person_id=2764547)
    'Miguel Ángel Vivas Moreno': None,  # TMDB propuso: 'Miguel Ángel Vivas' (person_id=140396)
    'Mikel Mas': None,  # TMDB propuso: 'Mikel Mas Bilbao' (person_id=3212690)
    'Monso': None,  # TMDB propuso: 'Percy Monso' (person_id=6371154)
    'Mónica Cambra Domínguez': None,  # TMDB propuso: 'Mònica Cambra' (person_id=2661260)
    'Nicolás Muñoz Avia': None,  # TMDB propuso: 'Nicolás Muñoz' (person_id=260953)
    'Nino Fontán': None,  # TMDB propuso: 'Nino Fontán Allen' (person_id=4919676)
    'Pablo Hernando Esquisabel': None,  # TMDB propuso: 'Pablo Hernando' (person_id=1185975)
    'Pau Canivell Gámez': None,  # TMDB propuso: 'Pau Canivell' (person_id=3304976)
    'Pau García Pérez De Lara': None,  # TMDB propuso: 'Pablo García Pérez de Lara' (person_id=1013025)
    'Paul Urkijo': None,  # TMDB propuso: 'Paul Urkijo Alijo' (person_id=1428818)
    'Pawel Pawlikowski': None,  # TMDB propuso: 'Paweł Pawlikowski' (person_id=64194)
    'Pedro Martín-Calero': None,  # TMDB propuso: 'Pedro Martín Calero' (person_id=1694893)
    'Pedro Pérez-Rosado': None,  # TMDB propuso: 'Pedro Pérez Rosado' (person_id=1036769)
    'Pello Gutiérrez Peñalba': None,  # TMDB propuso: 'Pello Gutiérrez' (person_id=2261544)
    'Phil Ivanusic-Vallée': None,  # TMDB propuso: 'Phil Ivanusic' (person_id=1246601)
    'Rafael Calatayud Cano': None,  # TMDB propuso: 'Rafa Calatayud Cano' (person_id=4223120)
    'Rafael G. Sánchez': None,  # TMDB propuso: 'Rafael Sánchez G.' (person_id=4603658)
    'Rafael J Salvia': None,  # TMDB propuso: 'Rafael J. Salvia' (person_id=98499)
    'Rafael Torrecilla': None,  # TMDB propuso: 'Rafael María Torrecilla' (person_id=1269221)
    'Ray(Jorge Loriga) Loriga': None,  # TMDB propuso: 'Ray Loriga' (person_id=3790)
    'Samuel Martín Delgado': None,  # TMDB propuso: 'Samuel M. Delgado' (person_id=1539731)
    'Santos Blanco': None,  # TMDB propuso: 'Blanco Santos' (person_id=1828428)
    'Sean Patrick O´Reilly': None,  # TMDB propuso: "Sean Patrick O'Reilly" (person_id=131416)
    'Sergio Montero': None,  # TMDB propuso: 'Sergio Montero Fernández' (person_id=5070921)
    'Sergio Rodrigo': None,  # TMDB propuso: 'Sergio Rodrigo Ruiz' (person_id=5503054)
    'Stojan Ðordevic': None,  # TMDB propuso: 'Stojan Đorđević' (person_id=1593464)
    'Tabatta Salinas': None,  # TMDB propuso: 'Tabatta Salinas Caballero' (person_id=4206690)
    'Tomás Aceituno': None,  # TMDB propuso: 'Tomás Aceituno Maldonado' (person_id=1458492)
    'Venci D. Kostov': None,  # TMDB propuso: 'Venci Kostov' (person_id=2192826)
    'Víctor Alonso Berbel': None,  # TMDB propuso: 'Victor Alonso-Berbel' (person_id=2334053)
    'Wang Xianping': None,  # TMDB propuso: 'Xianping Wang' (person_id=2266640)
    'Xabier Mina': None,  # TMDB propuso: 'Xabier Mina Ederra' (person_id=5338994)
    'Xavier Esteban': None,  # TMDB propuso: 'Xavier Esteban Casas' (person_id=3947595)
    'Xavier Torres Lliteras': None,  # TMDB propuso: 'Xavi Torres' (person_id=4034117)
    'Álex O´Dogherty': None,  # TMDB propuso: "Álex O'Dogherty" (person_id=1061514)
    'Álvaro Fernández - Armero': None,  # TMDB propuso: 'Álvaro Fernández Armero' (person_id=563824)
    'Álvaro Lión-Depetre': None,  # TMDB propuso: 'Álvaro Lion Depetre' (person_id=2014388)
    'Ángel Alonso': None,  # TMDB propuso: 'Miguel Ángel Alonso' (person_id=5115816)
    'Ángel Puado': None,  # TMDB propuso: 'Ángel Puado Veloso' (person_id=2864402)
    'Ángela Gallardo': None,  # TMDB propuso: 'Ángela Gallardo Bernal' (person_id=1649980)
    'Ángeles González-Sinde Reig': None,  # TMDB propuso: 'Ángeles González-Sinde' (person_id=230209)
}

In [22]:
for nombre, person_id_correcto in OVERRIDES_PERSON_SEARCH.items():
    if nombre not in person_search_cache:
        continue
    if person_id_correcto is None:
        person_search_cache[nombre] = {"person_id": None, "nombre_tmdb": None}
    else:
        person_search_cache[nombre]["person_id"] = person_id_correcto
        person_search_cache[nombre]["nombre_tmdb"] = None  # se pierde la referencia del nombre TMDB viejo, no importa

guardar_cache_json(PERSON_SEARCH_CACHE, person_search_cache)
print(f"✓ {len([v for v in OVERRIDES_PERSON_SEARCH.values() if v is not None])} overrides aplicados a la caché")

✓ 1 overrides aplicados a la caché

## 7. Enriquecimiento de persona -- fuente 1: TMDB (sexo + país)

In [23]:
def obtener_persona_tmdb(person_id, session, timeout=15):
    url = f"https://api.themoviedb.org/3/person/{person_id}"
    params = {"api_key": TMDB_API_KEY, "language": "es-ES"}
    try:
        r = session.get(url, params=params, timeout=timeout)
        r.raise_for_status()
        data = r.json()
        return {
            "person_id": person_id,
            "nombre": data.get("name"),
            "sexo": GENERO_MAP.get(data.get("gender"), None),
            "place_of_birth": data.get("place_of_birth"),
        }
    except Exception as e:
        print(f"  Error persona person_id={person_id}: {e}")
        return {"person_id": person_id, "nombre": None, "sexo": None, "place_of_birth": None}


def extraer_pais_aprox(place_of_birth):
    if not place_of_birth or not isinstance(place_of_birth, str):
        return None, "sin_dato"
    partes = [p.strip() for p in place_of_birth.split(",") if p.strip()]
    if not partes:
        return None, "sin_dato"
    return partes[-1], "heuristico"

print("✓ Funciones de enriquecimiento de persona vía TMDB listas (reutilizadas)")

✓ Funciones de enriquecimiento de persona vía TMDB listas (reutilizadas)

In [24]:
PERSONAS_CACHE = CSV_DIR / "personas_cache.csv"

if PERSONAS_CACHE.exists():
    personas_df = pd.read_csv(PERSONAS_CACHE, sep=';')
    persons_hechos = set(personas_df['person_id'].dropna().unique())
    print(f"Reanudando: {len(persons_hechos)} personas ya procesadas")
else:
    personas_df = pd.DataFrame()
    persons_hechos = set()
    print("Empezando desde cero")

person_ids_pendientes = [
    pid for pid in credits_df['person_id'].dropna().unique()
    if pid not in persons_hechos
]
print(f"Pendientes: {len(person_ids_pendientes)} personas únicas")

registros_p = []
for i, person_id in enumerate(person_ids_pendientes, 1):
    if i % 25 == 0:
        print(f"  [{i}/{len(person_ids_pendientes)}] person_id={person_id}")

    info = obtener_persona_tmdb(person_id, session)
    pais_aprox, confianza = extraer_pais_aprox(info["place_of_birth"])
    info["pais_aprox"] = pais_aprox
    info["confianza_pais"] = confianza
    registros_p.append(info)

    if i % 100 == 0:
        batch = pd.DataFrame(registros_p)
        personas_df = pd.concat([personas_df, batch], ignore_index=True)
        personas_df.to_csv(PERSONAS_CACHE, index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC)
        registros_p = []
        print("  ✓ Guardado parcial")

    time.sleep(0.25)

if registros_p:
    batch = pd.DataFrame(registros_p)
    personas_df = pd.concat([personas_df, batch], ignore_index=True)
    personas_df.to_csv(PERSONAS_CACHE, index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC)

print(f"\n✓ Personas completadas: {len(personas_df)}")
print(f"Con sexo declarado: {personas_df['sexo'].notna().sum()} / {len(personas_df)}")
print(f"Con país (heurístico): {personas_df['pais_aprox'].notna().sum()} / {len(personas_df)}")

Empezando desde cero
Pendientes: 2262 personas únicas
  [25/2262] person_id=2474255.0
  [50/2262] person_id=4237979.0
  [75/2262] person_id=3998718.0
  [100/2262] person_id=1360055.0
  ✓ Guardado parcial
  [125/2262] person_id=3959289.0
  [150/2262] person_id=2391063.0
  [175/2262] person_id=5361958.0
  [200/2262] person_id=1170687.0
  ✓ Guardado parcial
  [225/2262] person_id=589553.0
  [250/2262] person_id=1428818.0
  [275/2262] person_id=19841.0
  [300/2262] person_id=1051295.0
  ✓ Guardado parcial
  [325/2262] person_id=1838478.0
  [350/2262] person_id=2927784.0
  [375/2262] person_id=5247630.0
  [400/2262] person_id=2558765.0
  ✓ Guardado parcial
  [425/2262] person_id=2853009.0
  [450/2262] person_id=2998049.0
  [475/2262] person_id=2263746.0
  [500/2262] person_id=2545879.0
  ✓ Guardado parcial
  [525/2262] person_id=3405709.0
  [550/2262] person_id=132450.0
  [575/2262] person_id=1302077.0
  [600/2262] person_id=2046902.0
  ✓ Guardado parcial
  [625/2262] person_id=5842166.0
  [650/2262] person_id=5967557.0
  [675/2262] person_id=933308.0
  [700/2262] person_id=2897025.0
  ✓ Guardado parcial
  [725/2262] person_id=2413239.0
  [750/2262] person_id=3840554.0
  [775/2262] person_id=956692.0
  [800/2262] person_id=4766481.0
  ✓ Guardado parcial
  [825/2262] person_id=2407283.0
  [850/2262] person_id=5938497.0
  [875/2262] person_id=2700038.0
  [900/2262] person_id=225945.0
  ✓ Guardado parcial
  [925/2262] person_id=1525399.0
  [950/2262] person_id=4933579.0
  [975/2262] person_id=2247381.0
  [1000/2262] person_id=5384401.0
  ✓ Guardado parcial
  [1025/2262] person_id=2147073.0
  [1050/2262] person_id=5232889.0
  [1075/2262] person_id=4361813.0
  [1100/2262] person_id=1066930.0
  ✓ Guardado parcial
  [1125/2262] person_id=2602846.0
  [1150/2262] person_id=584191.0
  [1175/2262] person_id=1195430.0
  [1200/2262] person_id=1536696.0
  ✓ Guardado parcial
  [1225/2262] person_id=1269221.0
  [1250/2262] person_id=1192582.0
  [1275/2262] person_id=4380359.0
  [1300/2262] person_id=4648054.0
  ✓ Guardado parcial
  [1325/2262] person_id=2369120.0
  [1350/2262] person_id=4241822.0
  [1375/2262] person_id=2712188.0
  [1400/2262] person_id=4056738.0
  ✓ Guardado parcial
  [1425/2262] person_id=1073957.0
  [1450/2262] person_id=1116367.0
  [1475/2262] person_id=3497954.0
  [1500/2262] person_id=236516.0
  ✓ Guardado parcial
  [1525/2262] person_id=942161.0
  [1550/2262] person_id=5115912.0
  [1575/2262] person_id=2434915.0
  [1600/2262] person_id=37515.0
  ✓ Guardado parcial
  [1625/2262] person_id=65452.0
  [1650/2262] person_id=1019826.0
  [1675/2262] person_id=2452489.0
  [1700/2262] person_id=4426666.0
  ✓ Guardado parcial
  [1725/2262] person_id=3772681.0
  [1750/2262] person_id=1027164.0
  [1775/2262] person_id=5070916.0
  [1800/2262] person_id=8937.0
  ✓ Guardado parcial
  [1825/2262] person_id=4046621.0
  [1850/2262] person_id=1774363.0
  [1875/2262] person_id=4104754.0
  [1900/2262] person_id=1206752.0
  ✓ Guardado parcial
  [1925/2262] person_id=1835536.0
  [1950/2262] person_id=1475602.0
  [1975/2262] person_id=2875084.0
  [2000/2262] person_id=4198445.0
  ✓ Guardado parcial
  [2025/2262] person_id=6245236.0
  [2050/2262] person_id=4572706.0
  [2075/2262] person_id=2210416.0
  [2100/2262] person_id=225009.0
  ✓ Guardado parcial
  [2125/2262] person_id=2837162.0
  [2150/2262] person_id=1536852.0
  [2175/2262] person_id=3731578.0
  [2200/2262] person_id=2843637.0
  ✓ Guardado parcial
  [2225/2262] person_id=3571802.0
  [2250/2262] person_id=5345388.0

✓ Personas completadas: 2262
Con sexo declarado: 856 / 2262
Con país (heurístico): 572 / 2262

## 8. Enriquecimiento de persona -- fuente 2: Wikidata (huecos de TMDB)

Se usa el `imdb_id` que TMDB da vía `external_ids` como clave de búsqueda
en Wikidata (propiedad P345). Solo aplica a personas que TMDB sí encontró
(si TMDB no la encontró en absoluto, no hay `imdb_id` disponible por
ninguna vía -- ver aviso en la siguiente sección).

In [25]:
def obtener_imdb_id_tmdb(person_id, session, timeout=15):
    url = f"https://api.themoviedb.org/3/person/{person_id}"
    params = {"api_key": TMDB_API_KEY, "language": "es-ES", "append_to_response": "external_ids"}
    try:
        r = session.get(url, params=params, timeout=timeout)
        r.raise_for_status()
        return r.json().get("external_ids", {}).get("imdb_id")
    except Exception as e:
        print(f"  Error external_ids person_id={person_id}: {e}")
        return None

print("✓ obtener_imdb_id_tmdb definida (reutilizada)")

✓ obtener_imdb_id_tmdb definida (reutilizada)

In [26]:
WIKIDATA_SPARQL = "https://query.wikidata.org/sparql"


def consultar_wikidata_persona(imdb_id, timeout=30, reintentos=1):
    query = f"""
    SELECT ?persona ?sexoLabel ?paisLabel WHERE {{
      ?persona wdt:P345 "{imdb_id}" .
      OPTIONAL {{ ?persona wdt:P21 ?sexo . }}
      OPTIONAL {{ ?persona wdt:P27 ?pais . }}
      SERVICE wikibase:label {{ bd:serviceParam wikibase:language "es". }}
    }}
    LIMIT 1
    """
    headers = {"User-Agent": "ProyectoAcademicoLatam/1.0"}
    for intento in range(reintentos + 1):
        try:
            r = requests.get(WIKIDATA_SPARQL, params={"query": query, "format": "json"},
                              headers=headers, timeout=timeout)
            r.raise_for_status()
            bindings = r.json()["results"]["bindings"]
            if not bindings:
                return None, None, None
            b = bindings[0]
            sexo = b.get("sexoLabel", {}).get("value")
            pais = b.get("paisLabel", {}).get("value")
            persona_url = b.get("persona", {}).get("value")
            qid = persona_url.rsplit("/", 1)[-1] if persona_url else None
            return sexo, pais, qid
        except Exception as e:
            if intento < reintentos:
                time.sleep(2)
                continue
            print(f"  Error Wikidata imdb_id={imdb_id}: {e}")
            return None, None, None

print("✓ consultar_wikidata_persona definida (reutilizada)")

✓ consultar_wikidata_persona definida (reutilizada)

In [27]:
faltantes = personas_df[personas_df['sexo'].isna() | personas_df['pais_aprox'].isna()].copy()
print(f"Personas con algún dato faltante tras TMDB: {len(faltantes)} / {len(personas_df)}")

IMDB_ID_CACHE = CSV_DIR / "imdb_id_por_persona_cache.json"
imdb_id_cache = cargar_cache_json(IMDB_ID_CACHE)

for i, person_id in enumerate(faltantes['person_id'], 1):
    key = str(int(person_id))
    if key in imdb_id_cache:
        continue
    if i % 25 == 0:
        print(f"  [{i}/{len(faltantes)}] person_id={person_id}")
    imdb_id_cache[key] = obtener_imdb_id_tmdb(person_id, session)
    if i % 25 == 0:
        guardar_cache_json(IMDB_ID_CACHE, imdb_id_cache)
    time.sleep(0.25)

guardar_cache_json(IMDB_ID_CACHE, imdb_id_cache)
faltantes['imdb_id'] = faltantes['person_id'].map(lambda pid: imdb_id_cache.get(str(int(pid))))
print(f"\nCon imdb_id encontrado: {faltantes['imdb_id'].notna().sum()} / {len(faltantes)}")

Personas con algún dato faltante tras TMDB: 1706 / 2262
  [25/1706] person_id=2445361.0
  [50/1706] person_id=3998718.0
  [75/1706] person_id=3438202.0
  [100/1706] person_id=1756181.0
  [125/1706] person_id=2632890.0
  [150/1706] person_id=2225317.0
  [175/1706] person_id=1506375.0
  [200/1706] person_id=1950950.0
  [225/1706] person_id=1507365.0
  [250/1706] person_id=1304466.0
  [275/1706] person_id=1133344.0
  [300/1706] person_id=4762461.0
  [325/1706] person_id=3592180.0
  [350/1706] person_id=2545879.0
  [375/1706] person_id=2556742.0
  [400/1706] person_id=2204600.0
  [425/1706] person_id=2046902.0
  [450/1706] person_id=82726.0
  [475/1706] person_id=4796018.0
  [500/1706] person_id=5295734.0
  [525/1706] person_id=2806172.0
  [550/1706] person_id=5959830.0
  [575/1706] person_id=1368562.0
  [600/1706] person_id=1544003.0
  [625/1706] person_id=2873841.0
  [650/1706] person_id=1264790.0
  [675/1706] person_id=59144.0
  [700/1706] person_id=564076.0
  [725/1706] person_id=5384401.0
  [750/1706] person_id=2352923.0
  [775/1706] person_id=2854671.0
  [800/1706] person_id=16320.0
  [825/1706] person_id=2006688.0
  [850/1706] person_id=5659339.0
  [875/1706] person_id=3000259.0
  [900/1706] person_id=3722956.0
  [925/1706] person_id=1192582.0
  [950/1706] person_id=6377040.0
  [975/1706] person_id=4051084.0
  [1000/1706] person_id=6246497.0
  [1025/1706] person_id=5408871.0
  [1050/1706] person_id=5331869.0
  [1075/1706] person_id=3029978.0
  [1100/1706] person_id=84520.0
  [1125/1706] person_id=2865693.0
  [1150/1706] person_id=1008378.0
  [1175/1706] person_id=5674493.0
  [1200/1706] person_id=2799326.0
  [1225/1706] person_id=4547559.0
  [1250/1706] person_id=6224543.0
  [1275/1706] person_id=5208044.0
  [1300/1706] person_id=2955663.0
  [1325/1706] person_id=2394333.0
  [1350/1706] person_id=3235428.0
  [1375/1706] person_id=3684015.0
  [1400/1706] person_id=1974726.0
  [1425/1706] person_id=5152588.0
  [1450/1706] person_id=3206056.0
  [1475/1706] person_id=2294210.0
  [1500/1706] person_id=1157454.0
  [1525/1706] person_id=2309854.0
  [1550/1706] person_id=5614586.0
  [1575/1706] person_id=1211006.0
  [1600/1706] person_id=3255902.0
  [1625/1706] person_id=1373688.0
  [1650/1706] person_id=1839292.0
  [1675/1706] person_id=4785863.0
  [1700/1706] person_id=5624444.0

Con imdb_id encontrado: 516 / 1706

In [28]:
WIKIDATA_PERSONAS_CACHE = CSV_DIR / "wikidata_personas_cache.json"
wd_personas_cache = cargar_cache_json(WIKIDATA_PERSONAS_CACHE)
print(f"Caché existente: {len(wd_personas_cache)} personas")

con_imdb = faltantes[faltantes['imdb_id'].notna()]
pendientes_wd_personas = [
    fila for fila in con_imdb.itertuples() if fila.imdb_id not in wd_personas_cache
]
print(f"Pendientes: {len(pendientes_wd_personas)} / {len(con_imdb)}")

for i, fila in enumerate(pendientes_wd_personas, 1):
    if i % 25 == 0:
        print(f"  [{i}/{len(pendientes_wd_personas)}] {fila.imdb_id}")
    sexo_wd, pais_wd, qid_wd = consultar_wikidata_persona(fila.imdb_id)
    wd_personas_cache[fila.imdb_id] = {
        "person_id": fila.person_id, "sexo_wikidata": sexo_wd,
        "pais_wikidata": pais_wd, "wikidata_qid": qid_wd,
    }
    if i % 25 == 0:
        guardar_cache_json(WIKIDATA_PERSONAS_CACHE, wd_personas_cache)
        print("  ✓ Guardado parcial")
    time.sleep(0.3)

guardar_cache_json(WIKIDATA_PERSONAS_CACHE, wd_personas_cache)

wd_df = pd.DataFrame([
    {"person_id": v["person_id"], "sexo_wikidata": v["sexo_wikidata"],
     "pais_wikidata": v["pais_wikidata"], "wikidata_qid": v["wikidata_qid"]}
    for v in wd_personas_cache.values()
])
print(f"\n✓ Total en caché: {len(wd_df)}")
print(f"Con sexo desde Wikidata: {wd_df['sexo_wikidata'].notna().sum()}")
print(f"Con país desde Wikidata: {wd_df['pais_wikidata'].notna().sum()}")

Caché existente: 0 personas
Pendientes: 516 / 516
  [25/516] nm4652014
  ✓ Guardado parcial
  [50/516] nm2516950
  ✓ Guardado parcial
  [75/516] nm1141070
  ✓ Guardado parcial
  [100/516] nm4904829
  ✓ Guardado parcial
  [125/516] nm4698030
  ✓ Guardado parcial
  [150/516] nm2856376
  ✓ Guardado parcial
  [175/516] nm0293139
  ✓ Guardado parcial
  [200/516] nm0753807
  ✓ Guardado parcial
  [225/516] nm1396295
  ✓ Guardado parcial
  [250/516] nm0554693
  ✓ Guardado parcial
  [275/516] nm0765205
  ✓ Guardado parcial
  [300/516] nm5327902
  ✓ Guardado parcial
  [325/516] nm1892876
  ✓ Guardado parcial
  [350/516] nm1779829
  ✓ Guardado parcial
  [375/516] nm1147094
  ✓ Guardado parcial
  [400/516] nm1503330
  ✓ Guardado parcial
  [425/516] nm1281606
  ✓ Guardado parcial
  [450/516] nm2246351
  ✓ Guardado parcial
  [475/516] nm0753849
  ✓ Guardado parcial
  [500/516] nm0019115
  ✓ Guardado parcial

✓ Total en caché: 516
Con sexo desde Wikidata: 341
Con país desde Wikidata: 263

In [29]:
personas_df = personas_df.merge(wd_df, on='person_id', how='left')

MAPA_SEXO_WD = {"masculino": "hombre", "femenino": "mujer", "hombre": "hombre",
                 "mujer": "mujer", "no binario": "no_binario"}
personas_df['sexo_wikidata_norm'] = personas_df['sexo_wikidata'].str.lower().map(MAPA_SEXO_WD)

personas_df['sexo_final'] = personas_df['sexo'].fillna(personas_df['sexo_wikidata_norm'])
personas_df['fuente_sexo'] = personas_df['sexo'].notna().map({True: 'tmdb', False: None})
personas_df.loc[personas_df['sexo'].isna() & personas_df['sexo_wikidata_norm'].notna(), 'fuente_sexo'] = 'wikidata'

print(f"Cobertura sexo tras TMDB + Wikidata: {personas_df['sexo_final'].notna().sum()} / {len(personas_df)}")

Cobertura sexo tras TMDB + Wikidata: 1042 / 2262

## 9. Enriquecimiento de persona -- fuente 3: IMDb directo (solo país)

Para quien tenga `imdb_id` pero Wikidata tampoco tuviera el país. Se visita
la ficha de la persona en IMDb: primero se intenta el campo estructurado
`birthLocation`, y si no está, se lee la biografía en prosa (patrón
"Nació [<fecha>] en <Ciudad>, <País>").

**No se usa para sexo** -- IMDb no tiene un campo estructurado equivalente
al `gender` de TMDB, y la inferencia por pronombres en la biografía
resultó poco fiable en las pruebas.

In [30]:
def extraer_pais_de_bio_imdb(texto_bio):
    if not texto_bio:
        return None
    m = re.search(
        r"[Nn]aci[oó](?:.*?)\ben\s+[^,]+,\s*([A-ZÁÉÍÓÚÑ][\wÀ-ÿ]*(?:\s+[A-ZÁÉÍÓÚÑ][\wÀ-ÿ]*)*)",
        texto_bio
    )
    return m.group(1).strip() if m else None


def obtener_pais_imdb(imdb_id, driver):
    """
    1. birthLocation estructurado (regex sobre el HTML, el JSON embebido es
       demasiado grande/inestable para parsear entero de forma fiable)
    2. si no está, biografía en prosa (data-testid="bio-content")
    """
    try:
        driver.get(f"https://www.imdb.com/es/name/{imdb_id}/")
    except Exception as e:
        print(f"  Error cargando IMDb {imdb_id}: {e}")
        return None, None

    html = driver.page_source

    m = re.search(r'"birthLocation":\{"text":"([^"]+)"', html)
    if m:
        lugar = m.group(1)
        partes = [p.strip() for p in lugar.split(",") if p.strip()]
        if partes:
            return partes[-1], "imdb_estructurado"

    soup = BeautifulSoup(html, "html.parser")
    bio_div = soup.find(attrs={"data-testid": "bio-content"})
    texto_bio = bio_div.get_text(" ", strip=True) if bio_div else None
    pais_bio = extraer_pais_de_bio_imdb(texto_bio)
    if pais_bio:
        return pais_bio, "imdb_bio_texto"

    return None, None

print("✓ Funciones de fallback a IMDb definidas")

✓ Funciones de fallback a IMDb definidas

In [31]:
faltantes_pais_imdb = faltantes[
    faltantes['imdb_id'].notna()
    & faltantes['person_id'].isin(
        personas_df.loc[personas_df['pais_wikidata'].isna(), 'person_id']
    )
].copy()
print(f"Personas a intentar en IMDb (con imdb_id, sin país tras TMDB+Wikidata): {len(faltantes_pais_imdb)}")

IMDB_PAIS_CACHE = CSV_DIR / "imdb_pais_cache.json"
imdb_pais_cache = cargar_cache_json(IMDB_PAIS_CACHE)

driver = iniciar_driver()
try:
    for i, fila in enumerate(faltantes_pais_imdb.itertuples(), 1):
        if fila.imdb_id in imdb_pais_cache:
            continue
        if i % 20 == 0:
            print(f"  [{i}/{len(faltantes_pais_imdb)}] {fila.imdb_id}")
        pais, fuente = obtener_pais_imdb(fila.imdb_id, driver)
        imdb_pais_cache[fila.imdb_id] = {"person_id": fila.person_id, "pais": pais, "fuente": fuente}
        if i % 20 == 0:
            guardar_cache_json(IMDB_PAIS_CACHE, imdb_pais_cache)
            print("  ✓ Guardado parcial")
        time.sleep(random.uniform(2.0, 3.5))
finally:
    driver.quit()
    print("✓ Driver cerrado")

guardar_cache_json(IMDB_PAIS_CACHE, imdb_pais_cache)

imdb_pais_df = pd.DataFrame([
    {"person_id": v["person_id"], "pais_imdb": v["pais"], "fuente_pais_imdb": v["fuente"]}
    for v in imdb_pais_cache.values()
])
print(f"\n✓ Con país desde IMDb: {imdb_pais_df['pais_imdb'].notna().sum()} / {len(imdb_pais_df)}")

Personas a intentar en IMDb (con imdb_id, sin país tras TMDB+Wikidata): 253
  [20/253] nm5648314
  ✓ Guardado parcial
  [40/253] nm3324609
  ✓ Guardado parcial
  [60/253] nm3911679
  ✓ Guardado parcial
  [80/253] nm0169180
  ✓ Guardado parcial
  [100/253] nm0306443
  ✓ Guardado parcial
  [120/253] nm1511424
  ✓ Guardado parcial
  [140/253] nm2609612
  ✓ Guardado parcial
  [160/253] nm4559927
  ✓ Guardado parcial
  [180/253] nm3590688
  ✓ Guardado parcial
  [200/253] nm2330982
  ✓ Guardado parcial
  [220/253] nm5595047
  ✓ Guardado parcial
  [240/253] nm0515848
  ✓ Guardado parcial
✓ Driver cerrado

✓ Con país desde IMDb: 0 / 253

In [34]:
faltantes_pais_imdb.head()

,person_id,nombre,sexo,place_of_birth,pais_aprox,confianza_pais,imdb_id
2,1114075.0,Vicente Pérez Herrero,NaN,NaN,NaN,sin_dato,nm0701942
16,1284828.0,Juan Barrero,NaN,NaN,NaN,sin_dato,nm2209314
23,131587.0,Víctor Monigote,NaN,NaN,NaN,sin_dato,nm2857166
32,1105225.0,Héctor Claramunt,NaN,NaN,NaN,sin_dato,nm0163467
39,1063543.0,Verónica Fernández,mujer,NaN,NaN,sin_dato,nm0273784

In [35]:
driver = iniciar_driver()
try:
    imdb_id_prueba = "nm5648314"  # uno de los que falló arriba
    driver.get(f"https://www.imdb.com/es/name/{imdb_id_prueba}/")
    time.sleep(2)  # margen extra, por si acaso
    html = driver.page_source

    print("Longitud del HTML recibido:", len(html))
    print()
    print("¿Aparece 'birthLocation' en algún sitio?:", "birthLocation" in html)
    print("¿Aparece 'bio-content'?:", "bio-content" in html)
    print("¿Aparece 'captcha' o 'blocked' o 'unusual traffic'?:",
          any(p in html.lower() for p in ["captcha", "blocked", "unusual traffic", "access denied"]))
    print()
    print("Título de la página (<title>):")
    m = re.search(r"<title>(.*?)</title>", html)
    print(m.group(1) if m else "no encontrado")
    print()
    print("Primeros 1500 caracteres del HTML:")
    print(html[:1500])
finally:
    driver.quit()

Longitud del HTML recibido: 9530

¿Aparece 'birthLocation' en algún sitio?: False
¿Aparece 'bio-content'?: False
¿Aparece 'captcha' o 'blocked' o 'unusual traffic'?: True

Título de la página (<title>):
Human Verification

Primeros 1500 caracteres del HTML:
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Human Verification</title>
    <style>
        body {
            font-family: "Arial";
        }
    </style>
    <script type="text/javascript">
    window.awsWafCookieDomainList = ['imdb.com'];
    window.gokuProps = {
"key":"AQIDAHjcYu/GjX+QlghicBgQ/7bFaQZ+m5FKCMDnO+vTbNg96AGj9CNjkrHJK/VBRvomxSbuAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdM0kgGZ1rETMLYLkAgEQgDvuiNA1zhRYC/5tDKz4jcOZgCNDyskow3mcoI6luFkkNTywR1Da/3ji9w9EdfQGgLyxgN8TPxrx8XqelA==",
          "iv":"CgAGYzJCYwAAGR8L",
          "context":"qle4B/dU2g76XOjtT6bZISfPPHR8OehF+kBlpZeneEn7zdJUUy0+5KQB7kg/PT2tNzQgQ+W8Xuul54jQtByJuPOlif0curYUrZnSynfR3Q612rG/X3G231segrfdpR1Pab+b3tpgbMol3UQt/KncVruoHGsHSy6E7ccHbvMmfExRwhMBJeSYtE7ataQL3kBoZZgIdvSIZpcL+mDRqjYdVkGNO1DEBe8CIEJxnaqum8nnAIWN8TR7rBIAJdSeMUkta3fGavZf8AhKu0tOcS/YZZMZvDHAwG5xygp4eHVw6JLZ5yWU6D/VecsZzjclfHZSL940pRu+rcPUOo0ifVPE0/cHlcscVfs+HhXV3KZglf74OE1BliLmn+t1Kg=="
};
    </script>
    <script src="https://fb423e1ef94f.6277d64d.us-east-1.token.awswaf.com/fb423e1ef94f/c3382d439950/916d943f6a58/challenge.js"></script>
    <script src="https://fb423e1ef94f.6277d64d.us-east-1.captcha.awswaf.com/fb423e1ef94f/c3382d439950/916d943f6a58/captcha.js"></script>
<style>/*@font-face {
    font-family:AmazonEmber;
    src: url("https://a0.awsstatic.com/libra-css/fonts/amazon-ember/AmazonEmber_Rg.woff2") format("woff2")

### IMDb directo -- descartado (bloqueo anti-bot)

Probado contra datos reales: IMDb devuelve una página de verificación
"Human Verification" (AWS WAF Bot Control) en vez del contenido, incluso
con delays de varios segundos entre peticiones -- 0/253 personas
recuperadas en la corrida de prueba. No es un problema de regex ni de
timing, es un bloqueo activo.

**Se abandona esta fuente**, igual que ya se abandonó el matching de
Wikidata por nombre en la fase anterior del proyecto por su alta tasa de
falsos positivos -- es una limitación metodológica documentada, no un
hueco oculto. El país de estas personas queda como venga de TMDB/Wikidata
(o vacío, si ninguna de las dos lo tuvo).

In [32]:
personas_df = personas_df.merge(imdb_pais_df, on='person_id', how='left')
print("✓ País de IMDb incorporado a personas_df")

✓ País de IMDb incorporado a personas_df

## 10. Homologación de país a código ISO alpha-2

Mismo mapa curado en la fase anterior del proyecto. Se reutiliza tal cual
-- es una tabla de traducción estática, no depende del corpus. Es probable
que el corpus ampliado (~10x personas) revele nombres de país no cubiertos
todavía; el resumen final de abajo muestra cuántos quedan sin mapear.

In [36]:
MAPA_PAISES = {
    'Spain': 'ES', 'España': 'ES', 'Spagna': 'ES', 'Illas Canarias': 'ES', 'Galiza': 'ES',
    'France': 'FR', 'Danmark': 'DK', 'Brazil': 'BR', 'Brasil': 'BR',
    'Mexico': 'MX', 'México': 'MX', 'Peru': 'PE', 'Perú': 'PE',
    'Argentina': 'AR', 'Argentina.': 'AR', 'Chile': 'CL', 'Uruguay': 'UY',
    'El Salvador': 'SV', 'Guatemala': 'GT', 'Panama': 'PA', 'Puerto Rico': 'PR',
    'Costa Rica': 'CR', 'Dominican Republic': 'DO', 'Colombia': 'CO', 'Ecuador': 'EC',
    'Bolivia': 'BO', 'Cuba': 'CU', 'Paraguay': 'PY', 'Canada': 'CA', 'USA': 'US',
    'New York': 'US', 'Iran': 'IR', 'Reino de los Países Bajos': 'NL', 'Italia': 'IT',
    'Reino Unido': 'GB', 'Estados Unidos': 'US', 'Suiza': 'CH',

    # -- añadidos tras revisar el corpus ampliado --
    # Italia (variantes de idioma/erratas)
    'Italy': 'IT', 'Itally': 'IT', 'Regno Unito': 'GB', 'Firenze': 'IT',

    # España (regiones, ciudades, comunidades autónomas, variantes de idioma)
    'Euskal Herria': 'ES', 'Basque Country': 'ES', 'Valladolid - Spain': 'ES',
    'Madrid - Spain': 'ES', 'Canary Islands': 'ES', 'Barcelona': 'ES',
    'Catalunya': 'ES', 'Espagne': 'ES', 'Valencia (Spain)': 'ES',
    'Islas Baleares': 'ES', 'Spai': 'ES', 'Navarra': 'ES', 'Madrid': 'ES',

    # Reino Unido (variantes)
    'UK': 'GB', 'England': 'GB', 'London': 'GB',

    # Francia (variantes)
    'Francia': 'FR', 'Belgique': 'BE',

    # Resto de países (nombre en inglés/español/idioma nativo -> ISO)
    'Venezuela': 'VE', 'Germany': 'DE', 'Alemania': 'DE',
    'Portugal': 'PT', 'Denmark': 'DK', 'Reino de Dinamarca': 'DK',
    'Poland': 'PL', 'Polska': 'PL', 'Switzerland': 'CH', 'Australia': 'AU',
    'Sweden': 'SE', 'Hong Kong': 'HK', 'Türkiye': 'TR', 'Turquía': 'TR',
    'Serbia': 'RS', 'Finland': 'FI', 'Hungary': 'HU', 'Lithuania': 'LT',
    'Lituania': 'LT', 'Норвегия': 'NO', 'Ukraine': 'UA', 'Brasília': 'BR',
    'Belgium': 'BE', 'Afghanistan': 'AF', 'Lebanon': 'LB', 'Morocco': 'MA',
    'República Argentina': 'AR', 'Canadá': 'CA', 'Moldavia': 'MD', 'Rusia': 'RU',
    'Japón': 'JP',

    # -- deliberadamente SIN mapear (ambiguos/no son un país actual) --
    # 'USSR': disuelta en 15 países, no se puede asignar un ISO único con confianza
    # 'Yugoslavia': disuelta en varios países actuales (Serbia, Croacia, Bosnia...)
    # 'Kosovo': estatus disputado, sin ISO alpha-2 oficial universal
    # 'EU': no es un país, es la Unión Europea
}

personas_df['pais_aprox_iso'] = personas_df['pais_aprox'].map(MAPA_PAISES)
personas_df['pais_wikidata_iso'] = personas_df['pais_wikidata'].map(MAPA_PAISES)

personas_df['pais_final'] = personas_df['pais_wikidata_iso'].fillna(personas_df['pais_aprox_iso'])

personas_df['fuente_pais'] = None
personas_df.loc[personas_df['pais_aprox_iso'].notna(), 'fuente_pais'] = 'tmdb_heuristico'
personas_df.loc[personas_df['pais_wikidata_iso'].notna(), 'fuente_pais'] = 'wikidata'

print(f"Cobertura final de país (TMDB + Wikidata; IMDb descartado, ver nota anterior): "
      f"{personas_df['pais_final'].notna().sum()} / {len(personas_df)}")
print(f"\nFuente del país:\n{personas_df['fuente_pais'].value_counts(dropna=False)}")

sin_mapear = pd.concat([
    personas_df.loc[personas_df['pais_aprox'].notna() & personas_df['pais_aprox_iso'].isna(), 'pais_aprox'],
    personas_df.loc[personas_df['pais_wikidata'].notna() & personas_df['pais_wikidata_iso'].isna(), 'pais_wikidata'],
]).value_counts()
print(f"\n⚠ Valores de país sin mapear en MAPA_PAISES (añadir si aparecen aquí):")
print(sin_mapear)

Cobertura final de país (TMDB + Wikidata; IMDb descartado, ver nota anterior): 827 / 2262

Fuente del país:
fuente_pais
None               1435
tmdb_heuristico     565
wikidata            262
Name: count, dtype: int64

⚠ Valores de país sin mapear en MAPA_PAISES (añadir si aparecen aquí):
EU            1
Kosovo        1
USSR          1
Yugoslavia    1
Name: count, dtype: int64

## 11. Correcciones manuales (reutilizadas de la fase anterior)

Mismo diccionario que ya tenías, clave `person_id` de TMDB (estable entre
corridas -- no depende del corpus). Se aplica tal cual, sin tener que
volver a buscar a nadie.

In [38]:
"""
Formato: {person_id: {'sexo': ..., 'pais': ...}}
"""
CORRECCIONES_MANUALES_PERSONAS = {
    3517055: {'sexo': 'hombre', 'pais': 'ES'},
    2018522: {'sexo': 'hombre', 'pais': 'ES'},
    3962124: {'sexo': 'hombre', 'pais': 'MX'},
    1694893: {'sexo': 'hombre', 'pais': 'ES'},
    1980582: {'sexo': 'hombre', 'pais': 'UY'},
    3190577: {'sexo': 'hombre', 'pais': 'ES'},
    2628918: {'sexo': 'hombre', 'pais': 'CO'},
    2018520: {'sexo': 'mujer', 'pais': 'ES'},
    2549328: {'sexo': 'mujer', 'pais': 'ES'},
    3213575: {'pais': 'MX'},
    1115313: {'pais': 'ES'},
    1285223: {'pais': 'ES'},
    1469682: {'sexo': 'hombre', 'pais': 'AR'},
    1398043: {'sexo': 'hombre', 'pais': 'ES'},
    1525399: {'sexo': 'hombre', 'pais': 'ES'},
    3989209: {'sexo': 'hombre', 'pais': 'ES'},
    1533451: {'sexo': 'mujer', 'pais': 'NI'},
    5605266: {'sexo': 'mujer', 'pais': 'PE'},
    1091827: {'sexo': 'hombre', 'pais': 'AR'},
    2568321: {'sexo': 'mujer', 'pais': 'DO'},
    1624073: {'sexo': 'hombre', 'pais': 'EC'},
    4206690: {'sexo': 'mujer', 'pais': 'MX'},
    2662941: {'sexo': 'mujer', 'pais': 'ES'},
    1591887: {'sexo': 'hombre', 'pais': 'MX'},
    2839001: {'sexo': 'hombre', 'pais': 'ES'},
    1731588: {'pais': 'AR'},
    2282004: {'sexo': 'hombre', 'pais': 'ES'},
    4191264: {'sexo': 'mujer', 'pais': 'CO'},
    3202577: {'sexo': 'mujer', 'pais': 'AR'},
    1665562: {'sexo': 'mujer', 'pais': 'IT'},
    3044547: {'sexo': 'hombre', 'pais': 'ES'},
    1338870: {'sexo': 'hombre', 'pais': 'CU'},
    1962957: {'pais': 'ES'},
    2051782: {'pais': 'ES'},
    2472549: {'sexo': 'hombre', 'pais': 'ES'},
    5445665: {'sexo': 'mujer', 'pais': 'BO'},
    5052862: {'sexo': 'hombre', 'pais': 'CO'},
    2555139: {'sexo': 'mujer', 'pais': 'AR'},
    1789288: {'sexo': 'hombre', 'pais': 'CH'},
    2944940: {'sexo': 'hombre', 'pais': 'ES'},
    1805421: {'pais': 'ES'},
    2683614: {'sexo': 'mujer', 'pais': 'AR'},
    1184043: {'sexo': 'hombre', 'pais': 'MX'},
    2427035: {'sexo': 'mujer', 'pais': 'CO'},
    3698547: {'pais': 'ES'},
    2466544: {'sexo': 'hombre', 'pais': 'ES'},
    572115: {'pais': 'PR'},
    5549957: {'sexo': 'hombre', 'pais': 'MX'},
    589119: {'sexo': 'hombre', 'pais': 'MX'},
    1443063: {'sexo': 'hombre', 'pais': 'ES'},
    1740764: {'sexo': 'hombre', 'pais': 'AR'},
    3970485: {'sexo': 'mujer', 'pais': 'PE'},
    2475701: {'pais': 'PE'},
    5455347: {'sexo': 'mujer', 'pais': 'ES'},
    3039206: {'sexo': 'mujer', 'pais': 'ES'},
    1263590: {'sexo': 'hombre', 'pais': 'UY'}, 
    1490109: {'sexo': 'hombre', 'pais': 'ES'},
    1605611: {'sexo': 'hombre', 'pais': 'ES'},
    82726:   {'sexo': 'hombre', 'pais': 'ES'},   # Curro Velázquez
    2924495: {'sexo': 'hombre', 'pais': 'ES'},   # Benjamín Herranz
    1569540: {'sexo': 'mujer',  'pais': 'ES'},   # Bárbara Alpuente
    5727167: {'sexo': 'mujer',  'pais': None},   # Carmen López
    5739963: {'sexo': 'hombre', 'pais': 'ES'},   # Antonio Hernández Ruiz
    4223120: {'sexo': 'hombre', 'pais': 'ES'},   # Rafa Calatayud Cano
    3190577: {'sexo': 'hombre', 'pais': 'ES'},   # Jacob Santana
    4958781: {'sexo': 'hombre', 'pais': 'ES'},   # Kike Maíllo
    2654024: {'sexo': 'mujer',  'pais': 'ES'},   # Marta-Libertad Castillo
    1835761: {'sexo': 'hombre', 'pais': None},   # Gustavo Hernández
    1694893: {'sexo': 'hombre', 'pais': 'ES'},   # Pedro Martín Calero
    5455347: {'sexo': 'mujer',  'pais': 'ES'},   # Teresa Trasancos
    1980582: {'sexo': 'hombre', 'pais': 'IT'},   # Juma Fodde
    3418854: {'sexo': 'hombre', 'pais': 'ES'},   # Daniel Cebrián
    4983818: {'sexo': 'hombre', 'pais': None},   # Ángel Gómez
    1263590: {'sexo': 'hombre', 'pais': 'AR'},   # Manuel Facal
    3039206: {'sexo': 'mujer',  'pais': 'ES'},   # Sandra García Nieto
    5838939: {'sexo': 'mujer',  'pais': 'ES'},   # Marta Medina
    1317749: {'sexo': 'hombre', 'pais': 'ES'},   # David Desola
    1605611: {'sexo': 'hombre', 'pais': 'ES'},   # Marçal Cebrian
    2865703: {'sexo': 'mujer',  'pais': 'ES'},   # Ángela Obón
    4808255: {'sexo': 'mujer',  'pais': 'ES'},   # Sabina Méndez
    3962124: {'sexo': 'hombre', 'pais': 'AR'},   # Marco Lagarde
    3517055: {'sexo': 'hombre', 'pais': 'ES'},   # José Corral Llorente
    3893971: {'sexo': 'hombre', 'pais': 'ES'},   # Xabi Zabaleta
    113407:  {'sexo': 'mujer',  'pais': 'ES'},   # Arantxa Cuesta
    2103455: {'sexo': 'hombre', 'pais': 'AR'},   # Rodolfo Palacios
    4889588: {'sexo': 'hombre', 'pais': 'AR'},   # Pablo Agüero
    2480566: {'sexo': 'mujer',  'pais': 'FR'},   # Katell Guillou
    1157587: {'sexo': 'hombre', 'pais': 'ES'},   # David Baute
    4640765: {'sexo': 'mujer',       'pais': 'ES'},   # Yaiza Berrocal
    2428561: {'sexo': 'hombre',      'pais': 'ES'},   # Pau Calpe Rufat
    1876833: {'sexo': 'mujer',       'pais': 'ES'},   # Marta Grau
    3156507: {'sexo': 'hombre',      'pais': 'UY'},   # Rafael Russo
    5020311: {'sexo': 'hombre',      'pais': 'ES'},   # Samuel del Amor
    2018520: {'sexo': 'mujer',       'pais': 'ES'},   # Ángeles Hernández
    6360702: {'sexo': 'hombre',      'pais': 'ES'},   # David Matamoros Manteca
    1631846: {'sexo': 'hombre',      'pais': 'AR'},   # Álvaro Urtizberea
    1970518: {'sexo': 'mujer',       'pais': 'AR'},   # Erika Halvorsen
    2662836: {'sexo': 'no_binario',  'pais': 'ES'},   # Begoña Arostegui
    2555139: {'sexo': 'mujer',       'pais': 'AR'},   # Mariana Barassi
    31328:   {'sexo': 'hombre',      'pais': 'ES'},   # Diego Cagide
    3626927: {'sexo': 'hombre',      'pais': 'AR'},   # Diego Lucero
    4475946: {'sexo': 'hombre',      'pais': 'AR'},   # Mariano Alejandro Rojo
    5052862: {'sexo': 'hombre',      'pais': 'CO'},   # Gonzalo Perdomo-Tafur
    3530478: {'sexo': 'hombre',      'pais': 'ES'},   # Andrés Martorell
    4385976: {'sexo': 'hombre',      'pais': 'ES'},   # Javier Polo
    1608135: {'sexo': 'hombre',      'pais': 'ES'},   # Guillermo Guerrero
    1462879: {'sexo': 'hombre',      'pais': 'ES'},   # Enric Pardo
    5736743: {'sexo': 'hombre',      'pais': None},   # David Pascual
    4701879: {'sexo': 'hombre',      'pais': 'ES'},   # Ignasi Guerrero
    2472549: {'sexo': 'hombre',      'pais': 'ES'},   # Arturo Méndiz
    2522604: {'sexo': 'mujer',       'pais': 'ES'},   # Claudia Reig
    5777600: {'sexo': 'hombre',      'pais': 'ES'},   # Dani Fabra
    4506103: {'sexo': 'hombre',      'pais': 'VE'},   # Andry José Barrientos
    5232889: {'sexo': 'hombre',      'pais': 'ES'},   # Andrés Clemente
    2018522: {'sexo': 'hombre',      'pais': 'ES'},   # David Matamoros
    2661260: {'sexo': 'mujer',       'pais': 'ES'},   # Mònica Cambra
    3960226: {'sexo': 'mujer',       'pais': 'ES'},  # Ariadna Fortuny
    3960227: {'sexo': 'mujer',  'pais': 'ES'},   # Clàudia Garcia de Dios
    3374272: {'sexo': 'mujer',  'pais': None},   # Lucía Herrera
    1962957: {'sexo': 'mujer',  'pais': 'ES'},   # Meritxell Colell Aparicio
    1338870: {'sexo': 'hombre', 'pais': 'CU'},   # Pavel Giroud
    1764976: {'sexo': 'hombre', 'pais': 'AR'},   # Mariano Donoso
    2962112: {'sexo': 'hombre', 'pais': 'AR'},   # Federico Cardone
    2614503: {'sexo': 'mujer',  'pais': 'AR'},   # Mariana Guzzante
    5674493: {'sexo': 'hombre', 'pais': 'ES'},   # Jesús Caballero
    4572706: {'sexo': 'mujer',  'pais': 'ES'},   # Laura Herrero Garvín
    5548470: {'sexo': 'hombre', 'pais': 'PE'},   # Alejandro Andrade Pease
    3928504: {'sexo': 'hombre', 'pais': 'ES'},   # Armando López Muñoz
    2929692: {'sexo': 'hombre', 'pais': 'ES'},   # Jon Viar
    1731588: {'sexo': 'hombre', 'pais': 'AR'},   # Santiago Fillol
    3772682: {'sexo': 'hombre', 'pais': 'AR'},   # Lucas Vermal
    3772681: {'sexo': 'hombre', 'pais': 'AR'},   # Edgardo Dobry
    2282004: {'sexo': 'hombre', 'pais': 'ES'},   # David Berraondo
    131587:  {'sexo': 'hombre', 'pais': 'ES'},   # Víctor Monigote
    4962452: {'sexo': 'hombre', 'pais': 'AR'},   # Pablo Enrique Bossi
    5500234: {'sexo': 'mujer',  'pais': 'ES'},   # Jenifer de la Rosa Martín
    3202577: {'sexo': 'mujer',  'pais': 'AR'},   # María Zanetti
    1665562: {'sexo': 'mujer',  'pais': 'IT'},   # Maria Mauti
    4080092: {'sexo': 'mujer',  'pais': 'ES'},   # Sara Mesa
    3016177: {'sexo': 'mujer',  'pais': None},   # Mercedes Rodrigo
    5371432: {'sexo': 'mujer',  'pais': 'ES'},   # Helena Girón
    1866952: {'sexo': 'hombre', 'pais': 'ES'},   # Juanma Villar Betancort
    4318654: {'sexo': 'hombre', 'pais': 'CU'},   # Erlyn L. Borges
    4102781: {'sexo': 'hombre', 'pais': 'UY'},   # Facundo Ponce de León
    4865414: {'sexo': 'hombre', 'pais': 'ES'},   # Julio S. de la Fuente
    2239321: {'sexo': 'mujer',  'pais': 'AR'},   # Natacha Kucic
    2467723: {'sexo': 'mujer',  'pais': 'ES'},   # Patricia Pérez Fernández
    2568321: {'sexo': 'mujer',  'pais': 'DO'},   # Johanne Gómez Terrero
    2441053: {'sexo': 'mujer',  'pais': 'AR'},   # Mariana Cangas
    3536688: {'sexo': 'hombre', 'pais': 'ES'},   # Miguel García de la Calera
    4075083: {'sexo': 'mujer',  'pais': 'AR'},   # Carolina Alamino
    5456803: {'sexo': 'hombre', 'pais': 'ES'},   # José del Corral
    2422984: {'sexo': 'hombre', 'pais': 'IT'},   # Mauro Colombo
    2079453: {'sexo': 'hombre', 'pais': 'ES'},   # Andrés Garrigó
    4019154: {'sexo': 'hombre', 'pais': 'ES'},   # Josepmaria Anglès
    2079455: {'sexo': 'hombre', 'pais': 'ES'},   # Josemaría Muñoz
    3102068: {'sexo': 'mujer',  'pais': 'ES'},   # Cira Valiño
    4206690: {'sexo': 'mujer',  'pais': 'MX'},   # Tabatta Salinas Caballero
    2662941: {'sexo': 'mujer',  'pais': 'AR'},   # Andrea Gautier
    1091827: {'sexo': 'hombre', 'pais': 'AR'},   # Diego Yaker
    3632587: {'sexo': 'hombre', 'pais': 'ES'},   # José Manuel Rebollo
    1740764: {'sexo': 'hombre', 'pais': 'AR'},   # Luciano Juncos
    3006682: {'sexo': 'hombre', 'pais': 'CL'},   # Renzo Felippa
    1115313: {'sexo': 'hombre', 'pais': 'ES'},   # Javier Espada
    2799326: {'sexo': 'mujer',  'pais': 'CU'},   # Lisandra López Fabe
    1358333: {'sexo': 'hombre', 'pais': 'NL'},   # Arturo Prins
    1756181: {'sexo': 'mujer',  'pais': 'US'},   # Daresha Kyi
    1161761: {'sexo': 'mujer',  'pais': 'US'},   # Catherine Gund
    1262693: {'sexo': 'hombre', 'pais': 'BR'},   # Daniel Augusto
    4180107: {'sexo': 'hombre', 'pais': 'CU'},   # Ernesto Daranas Serrano
    1525399: {'sexo': 'hombre', 'pais': 'BO'},   # Ida Cuéllar
    2645524: {'sexo': 'hombre', 'pais': 'ES'},   # Juan Muñoz-Tébar
    5036140: {'sexo': 'hombre', 'pais': 'ES'},   # Jorge Cebrián
    5209434: {'sexo': 'hombre', 'pais': None},   # José Luis López
    589777:  {'sexo': 'hombre', 'pais': None},   # Oscar Martín
    1533451: {'sexo': 'mujer',  'pais': 'NI'},   # Laura Baumeister
    2227717: {'sexo': 'mujer',  'pais': 'FR'},   # Laure Desmazières
    3424062: {'sexo': 'hombre', 'pais': 'MX'},   # César Tejeda
    1793738: {'sexo': 'mujer',  'pais': 'ES'},    # Carmen García Rodeja
    1696632: {'sexo': 'hombre', 'pais': 'ES'},   # Eliseo Fernández
    5597231: {'sexo': 'hombre', 'pais': None},   # Diego Martínez
    2944940: {'sexo': 'hombre', 'pais': 'ES'},   # Sergio García de Leaniz
    5013620: {'sexo': 'hombre', 'pais': None},   # Vicente Pérez
    1645082: {'sexo': 'mujer',  'pais': 'MX'},   # Erika Elizalde
    1195190: {'sexo': 'hombre', 'pais': 'ES'},   # Manuel M. Velasco
    1805421: {'sexo': 'hombre', 'pais': 'ES'},   # Isaac Berrocal
    2876280: {'sexo': 'mujer',  'pais': 'ES'},   # Victoria Vázquez
    5467197: {'sexo': 'hombre', 'pais': None},   # Ignacio López
    2261043: {'sexo': 'hombre', 'pais': 'ES'},   # Diego Arjona
    2683614: {'sexo': 'mujer',  'pais': 'ES'},   # Amparo Aguilar
    2509031: {'sexo': 'hombre', 'pais': 'AR'},   # Pío Longo
    4163858: {'sexo': 'hombre', 'pais': 'PE'},   # Santiago Alvarado Ilarri
    1443072: {'sexo': 'hombre', 'pais': 'ES'},   # Ramón Salas
    3081311: {'sexo': 'hombre', 'pais': 'CO'},   # Juan A. Zapata
    5844744: {'sexo': 'hombre', 'pais': None},   # Alejandro Hernández
    3698547: {'sexo': 'mujer',  'pais': 'ES'},   # Carmina Balaguer
    572115:  {'sexo': 'hombre', 'pais': 'PR'},   # Ray Figueroa
    2427245: {'sexo': 'hombre', 'pais': 'MX'},   # Julio César Sánchez
    1634868: {'sexo': 'hombre', 'pais': 'ES'},   # José Manuel Colón
    572168:  {'sexo': 'hombre', 'pais': 'US'},   # Darren Kloomok
    1432104: {'sexo': 'hombre', 'pais': 'CO'},   # Alejandro Naranjo
    3763970: {'sexo': 'hombre', 'pais': 'ES'},   # Omar Al Abdul Razzak
    1027743: {'sexo': 'hombre', 'pais': 'ES'},   # Manuel J. García
    168769:  {'sexo': 'hombre', 'pais': 'DE'},   # Michael Maurer
    2194080: {'sexo': 'hombre', 'pais': 'US'},   # John Michael Boughn
    260267:  {'sexo': 'hombre', 'pais': 'AR'},   # Mateo Iribarren
    1184043: {'sexo': 'hombre', 'pais': 'MX'},   # Haroldo Fajardo
    1629878: {'sexo': 'mujer',  'pais': 'BR'},   # Carolina Kotscho
    1469682: {'sexo': 'hombre', 'pais': 'ES'},   # Daniel Desaloms
    1591887: {'sexo': 'hombre', 'pais': None},   # Armando López
    589119:  {'sexo': 'hombre', 'pais': 'CO'},   # Iván Ávila Dueñas
    2051782: {'sexo': 'hombre', 'pais': 'ES'},   # Xavi Sala
    2466544: {'sexo': 'hombre', 'pais': 'EC'},   # Ignacio Guarderas
    2532194: {'sexo': 'mujer',  'pais': 'ES'},   # Pilar Seijas
    2475701: {'sexo': 'hombre', 'pais': 'ES'},   # Luis Cintora
    3584087: {'sexo': 'hombre', 'pais': 'AR'},   # Camilo Zaffora
    3698687: {'sexo': 'hombre', 'pais': 'MX'},   # Carlos Aguillón
    2427035: {'sexo': 'mujer',  'pais': 'CO'},   # Yennifer Uribe Alzate
    3989209: {'sexo': 'hombre', 'pais': 'ES'},   # David Beltrán i Marí
    5054401: {'sexo': 'mujer',  'pais': 'ES'},   # Katherine Tort
    5605266: {'sexo': 'mujer',  'pais': 'PE'},   # Valeria Calmet
    2657529: {'sexo': 'mujer',  'pais': 'MX'},   # Leticia Castillo
    1649980: {'pais': 'ES'}                      # Ángela Gallardo Bernal
}

In [39]:
def aplicar_correcciones_personas_df(personas_df, correcciones_dict, verbose_aplicados=True):
    personas_df = personas_df.copy()
    aplicados, omitidos = [], []

    for person_id, valores in correcciones_dict.items():
        mask = personas_df['person_id'] == person_id
        if not mask.any():
            omitidos.append(person_id)
            continue

        if 'sexo' in valores:
            personas_df.loc[mask, 'sexo_final'] = valores['sexo']
            personas_df.loc[mask, 'fuente_sexo'] = 'manual'
        if 'pais' in valores:
            personas_df.loc[mask, 'pais_final'] = valores['pais']
            personas_df.loc[mask, 'fuente_pais'] = 'manual'

        aplicados.append(person_id)
        if verbose_aplicados:
            nombre = personas_df.loc[mask, 'nombre'].values[0]
            print(f"✓ {person_id} ({nombre}): {valores}")

    print(f"\n{len(aplicados)} correcciones aplicadas, {len(omitidos)} omitidas "
          f"(person_id no presente en este corpus)")
    return personas_df, aplicados, omitidos

if CORRECCIONES_MANUALES_PERSONAS:
    personas_df, aplicados, omitidos = aplicar_correcciones_personas_df(personas_df, CORRECCIONES_MANUALES_PERSONAS)

✓ 3517055 (José Corral Llorente): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2018522 (David Matamoros): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3962124 (Marco Lagarde): {'sexo': 'hombre', 'pais': 'AR'}
✓ 1694893 (Pedro Martín Calero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1980582 (Juma Fodde): {'sexo': 'hombre', 'pais': 'IT'}
✓ 3190577 (Jacob Santana): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2628918 (Sergio Dow): {'sexo': 'hombre', 'pais': 'CO'}
✓ 2018520 (Ángeles Hernández): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2549328 (Irene Iborra Rizo): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1115313 (Javier Espada): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1525399 (Ida Cuéllar): {'sexo': 'hombre', 'pais': 'BO'}
✓ 3989209 (David Beltrán i Marí): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1533451 (Laura Baumeister): {'sexo': 'mujer', 'pais': 'NI'}
✓ 1091827 (Diego Yaker): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2568321 (Johanne Gómez Terrero): {'sexo': 'mujer', 'pais': 'DO'}
✓ 4206690 (Tabatta Salinas Caballero): {'sexo': 'mujer', 'pais': 'MX'}
✓ 2662941 (Andrea Gautier): {'sexo': 'mujer', 'pais': 'AR'}
✓ 1731588 (Santiago Fillol): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2282004 (David Berraondo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3202577 (María Zanetti): {'sexo': 'mujer', 'pais': 'AR'}
✓ 1665562 (Maria Mauti): {'sexo': 'mujer', 'pais': 'IT'}
✓ 1338870 (Pavel Giroud): {'sexo': 'hombre', 'pais': 'CU'}
✓ 1962957 (Meritxell Colell Aparicio): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2472549 (Arturo Méndiz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5052862 (Gonzalo Perdomo-Tafur): {'sexo': 'hombre', 'pais': 'CO'}
✓ 2555139 (Mariana Barassi): {'sexo': 'mujer', 'pais': 'AR'}
✓ 1805421 (Isaac Berrocal): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2683614 (Amparo Aguilar): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2427035 (Yennifer Uribe Alzate): {'sexo': 'mujer', 'pais': 'CO'}
✓ 3698547 (Carmina Balaguer): {'sexo': 'mujer', 'pais': 'ES'}
✓ 572115 (Ray Figueroa): {'sexo': 'hombre', 'pais': 'PR'}
✓ 1740764 (Luciano Juncos): {'sexo': 'hombre', 'pais': 'AR'}
✓ 5455347 (Teresa Trasancos): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3039206 (Sandra García Nieto): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1263590 (Manuel Facal): {'sexo': 'hombre', 'pais': 'AR'}
✓ 1605611 (Marçal Cebrian): {'sexo': 'hombre', 'pais': 'ES'}
✓ 82726 (Curro Velázquez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2924495 (Benjamín Herranz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1569540 (Bárbara Alpuente): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5727167 (Carmen López): {'sexo': 'mujer', 'pais': None}
✓ 4223120 (Rafa Calatayud Cano): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4958781 (Kike Maillo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2654024 (Marta-Libertad Castillo): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1835761 (Gustavo Hernández): {'sexo': 'hombre', 'pais': None}
✓ 3418854 (Daniel Cebrián): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4983818 (Ángel Gómez): {'sexo': 'hombre', 'pais': None}
✓ 1317749 (David Desola): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2865703 (Ángela Obón): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4808255 (Sabina Méndez): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3893971 (Xabi Zabaleta): {'sexo': 'hombre', 'pais': 'ES'}
✓ 113407 (Arantxa Cuesta): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2103455 (Rodolfo Palacios): {'sexo': 'hombre', 'pais': 'AR'}
✓ 4889588 (Pablo Agüero): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2480566 (Katell Guillou): {'sexo': 'mujer', 'pais': 'FR'}
✓ 1157587 (David Baute): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4640765 (Yaiza Berrocal): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2428561 (Pau Calpe Rufat): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1876833 (Marta Grau): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3156507 (Rafael Russo): {'sexo': 'hombre', 'pais': 'UY'}
✓ 5020311 (Samuel del Amor): {'sexo': 'hombre', 'pais': 'ES'}
✓ 6360702 (David Matamoros Manteca): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1631846 (Álvaro Urtizberea): {'sexo': 'hombre', 'pais': 'AR'}
✓ 1970518 (Erika Halvorsen): {'sexo': 'mujer', 'pais': 'AR'}
✓ 2662836 (Begoña Arostegui): {'sexo': 'no_binario', 'pais': 'ES'}
✓ 31328 (Diego Cagide): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3626927 (Diego Lucero): {'sexo': 'hombre', 'pais': 'AR'}
✓ 4475946 (Mariano Alejandro Rojo): {'sexo': 'hombre', 'pais': 'AR'}
✓ 3530478 (Andrés Martorell): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4385976 (Javier Polo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1608135 (Guillermo Guerrero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1462879 (Enric Pardo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5736743 (David Pascual): {'sexo': 'hombre', 'pais': None}
✓ 4701879 (Ignasi Guerrero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2522604 (Claudia Reig): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5777600 (Dani Fabra): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4506103 (Andry José Barrientos): {'sexo': 'hombre', 'pais': 'VE'}
✓ 5232889 (Andrés Clemente): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2661260 (Mònica Cambra): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3960226 (Ariadna Fortuny): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3960227 (Clàudia Garcia de Dios): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3374272 (Lucía Herrera): {'sexo': 'mujer', 'pais': None}
✓ 1764976 (Mariano Donoso): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2962112 (Federico Cardone): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2614503 (Mariana Guzzante): {'sexo': 'mujer', 'pais': 'AR'}
✓ 5674493 (Jesus Caballero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4572706 (Laura Herrero Garvín): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5548470 (Alejandro Andrade Pease): {'sexo': 'hombre', 'pais': 'PE'}
✓ 3928504 (Armando López Muñoz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2929692 (Jon Viar): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3772682 (Lucas Vermal): {'sexo': 'hombre', 'pais': 'AR'}
✓ 3772681 (Edgardo Dobry): {'sexo': 'hombre', 'pais': 'AR'}
✓ 131587 (Víctor Monigote): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4962452 (Pablo Enrique Bossi): {'sexo': 'hombre', 'pais': 'AR'}
✓ 5500234 (Jenifer de la Rosa Martín): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4080092 (Sara Mesa): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3016177 (Mercedes Rodrigo): {'sexo': 'mujer', 'pais': None}
✓ 5371432 (Helena Girón): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1866952 (Juanma Villar Betancort): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4318654 (Erlyn L. Borges): {'sexo': 'hombre', 'pais': 'CU'}
✓ 4102781 (Facundo Ponce de León): {'sexo': 'hombre', 'pais': 'UY'}
✓ 4865414 (Julio S. de la Fuente): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2239321 (Natacha Kucic): {'sexo': 'mujer', 'pais': 'AR'}
✓ 2467723 (Patricia Pérez Fernández): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2441053 (Mariana Cangas): {'sexo': 'mujer', 'pais': 'AR'}
✓ 3536688 (Miguel García de la Calera): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4075083 (Carolina Alamino): {'sexo': 'mujer', 'pais': 'AR'}
✓ 5456803 (Josè del Corral): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2422984 (Mauro Colombo): {'sexo': 'hombre', 'pais': 'IT'}
✓ 2079453 (Andrés Garrigó): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4019154 (Josepmaria Anglès): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2079455 (Josemaría Muñoz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3102068 (Cira Valiño): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3632587 (Jose Manuel Rebollo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3006682 (Renzo Felippa): {'sexo': 'hombre', 'pais': 'CL'}
✓ 2799326 (Lisandra López Fabe): {'sexo': 'mujer', 'pais': 'CU'}
✓ 1358333 (Arturo Prins): {'sexo': 'hombre', 'pais': 'NL'}
✓ 1756181 (Daresha Kyi): {'sexo': 'mujer', 'pais': 'US'}
✓ 1161761 (Catherine Gund): {'sexo': 'mujer', 'pais': 'US'}
✓ 1262693 (Daniel Augusto): {'sexo': 'hombre', 'pais': 'BR'}
✓ 4180107 (Ernesto Daranas Serrano): {'sexo': 'hombre', 'pais': 'CU'}
✓ 2645524 (Juan Muñoz-Tébar): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5036140 (Jorge Cebrián): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5209434 (José Luis López): {'sexo': 'hombre', 'pais': None}
✓ 589777 (Oscar Martín): {'sexo': 'hombre', 'pais': None}
✓ 2227717 (Laure Desmazières): {'sexo': 'mujer', 'pais': 'FR'}
✓ 3424062 (César Tejeda): {'sexo': 'hombre', 'pais': 'MX'}
✓ 5597231 (Diego Martínez): {'sexo': 'hombre', 'pais': None}
✓ 1645082 (Erika Elizalde): {'sexo': 'mujer', 'pais': 'MX'}
✓ 1195190 (Manuel M. Velasco): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2876280 (Victoria Vázquez): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5467197 (Ignacio López): {'sexo': 'hombre', 'pais': None}
✓ 2261043 (Diego Arjona): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2509031 (Pío Longo): {'sexo': 'hombre', 'pais': 'AR'}
✓ 4163858 (Santiago Alvarado Ilarri): {'sexo': 'hombre', 'pais': 'PE'}
✓ 1443072 (Ramón Salas): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3081311 (Juan A. Zapata): {'sexo': 'hombre', 'pais': 'CO'}
✓ 5844744 (Alejandro Hernández): {'sexo': 'hombre', 'pais': None}
✓ 2427245 (Julio César Sánchez): {'sexo': 'hombre', 'pais': 'MX'}
✓ 1634868 (José Manuel Colón): {'sexo': 'hombre', 'pais': 'ES'}
✓ 572168 (Darren Kloomok): {'sexo': 'hombre', 'pais': 'US'}
✓ 1432104 (Alejandro Naranjo): {'sexo': 'hombre', 'pais': 'CO'}
✓ 3763970 (Omar Al Abdul Razzak): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1027743 (Manuel J. García): {'sexo': 'hombre', 'pais': 'ES'}
✓ 168769 (Michael Maurer): {'sexo': 'hombre', 'pais': 'DE'}
✓ 2194080 (John Michael Boughn): {'sexo': 'hombre', 'pais': 'US'}
✓ 260267 (Mateo Iribarren): {'sexo': 'hombre', 'pais': 'AR'}
✓ 5054401 (Katherine Tort): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1649980 (Ángela Gallardo Bernal): {'pais': 'ES'}

148 correcciones aplicadas, 32 omitidas (person_id no presente en este corpus)

In [42]:
pendientes = personas_df[personas_df['sexo_final'].isna() | personas_df['pais_final'].isna()].copy()
pendientes = pendientes.sort_values('nombre')

print(f"# {len(pendientes)} personas con algún dato faltante -- rellena 'sexo'/'pais' donde lo sepas, "
      "deja None donde no")
print("CORRECCIONES_MANUALES_PERSONAS_NUEVAS = {")
for _, row in pendientes.iterrows():
    pid = int(row['person_id']) if pd.notna(row['person_id']) else None
    imdb_id = imdb_id_cache.get(str(pid)) if pid is not None else None
    link_imdb = f" | imdb.com/es/name/{imdb_id}/" if imdb_id else ""
    print(f"    {pid}: {{'sexo': None, 'pais': None}},  "
          f"# {row['nombre']} (sexo={row['sexo_final']}, pais={row['pais_final']}){link_imdb}")
print("}")

# 1312 personas con algún dato faltante -- rellena 'sexo'/'pais' donde lo sepas, deja None donde no
CORRECCIONES_MANUALES_PERSONAS_NUEVAS = {
    4271430: {'sexo': None, 'pais': None},  # Abel Alfonso (sexo=nan, pais=nan)
    1049263: {'sexo': None, 'pais': None},  # Abel García Roure (sexo=nan, pais=nan) | imdb.com/es/name/nm1071819/
    2806169: {'sexo': None, 'pais': None},  # Abigail Schaaff (sexo=nan, pais=nan)
    1413007: {'sexo': None, 'pais': None},  # Adolfo Dufour (sexo=hombre, pais=nan) | imdb.com/es/name/nm1580691/
    4180516: {'sexo': None, 'pais': None},  # Adolfo Moreno (sexo=nan, pais=nan)
    4181357: {'sexo': None, 'pais': None},  # Adrian Varela (sexo=nan, pais=nan)
    3959299: {'sexo': None, 'pais': None},  # Adrià Roca (sexo=hombre, pais=nan)
    5048846: {'sexo': None, 'pais': None},  # Adrián García (sexo=nan, pais=nan)
    5686508: {'sexo': None, 'pais': None},  # Adrián Guanche (sexo=nan, pais=nan)
    1802332: {'sexo': None, 'pais': None},  # Adrián Orr (sexo=hombre, pais=nan) | imdb.com/es/name/nm3730189/
    3302464: {'sexo': None, 'pais': None},  # Agustí Franch (sexo=hombre, pais=nan)
    2234399: {'sexo': None, 'pais': None},  # Agustín Rubio (sexo=nan, pais=nan)
    5624440: {'sexo': None, 'pais': None},  # Agustín Toranzo (sexo=nan, pais=nan)
    4648054: {'sexo': None, 'pais': None},  # Ainara Fernández (sexo=nan, pais=nan)
    1624805: {'sexo': None, 'pais': None},  # Ainhoa Andraka (sexo=nan, pais=nan) | imdb.com/es/name/nm2122019/
    5544451: {'sexo': None, 'pais': None},  # Ainhoa Rodríguez (sexo=nan, pais=nan)
    2359817: {'sexo': None, 'pais': None},  # Ainhoa Urgoitia (sexo=nan, pais=nan)
    226485: {'sexo': None, 'pais': None},  # Airy Maragall (sexo=nan, pais=nan) | imdb.com/es/name/nm2253763/
    3235428: {'sexo': None, 'pais': None},  # Aitor González de Langarica Mendizabal (sexo=hombre, pais=nan)
    2359816: {'sexo': None, 'pais': None},  # Aitor López de Aberásturi (sexo=nan, pais=nan)
    4999905: {'sexo': None, 'pais': None},  # Aizea Roca Berridi (sexo=nan, pais=nan)
    127148: {'sexo': None, 'pais': None},  # Alan Freedland (sexo=hombre, pais=nan) | imdb.com/es/name/nm0293139/
    127146: {'sexo': None, 'pais': None},  # Alan R. Cohen (sexo=hombre, pais=nan) | imdb.com/es/name/nm0169180/
    4653926: {'sexo': None, 'pais': None},  # Alana S. Portero (sexo=mujer, pais=nan) | imdb.com/es/name/nm16544203/
    6024188: {'sexo': None, 'pais': None},  # Alba López (sexo=nan, pais=nan)
    5692485: {'sexo': None, 'pais': None},  # Alba López Manubens (sexo=nan, pais=nan)
    6142772: {'sexo': None, 'pais': None},  # Alba Prol Cid (sexo=nan, pais=nan)
    2856339: {'sexo': None, 'pais': None},  # Albert Badia (sexo=nan, pais=nan)
    4044587: {'sexo': None, 'pais': None},  # Albert Bertran Bas (sexo=nan, pais=nan)
    4513433: {'sexo': None, 'pais': None},  # Albert Naudín (sexo=nan, pais=nan)
    3902643: {'sexo': None, 'pais': None},  # Albert Olivé (sexo=nan, pais=nan)
    3701170: {'sexo': None, 'pais': None},  # Albert Val (sexo=nan, pais=nan)
    2998049: {'sexo': None, 'pais': None},  # Alberto Armas Díaz (sexo=nan, pais=nan)
    5909538: {'sexo': None, 'pais': None},  # Alberto Fernández Arregui (sexo=nan, pais=nan)
    6384256: {'sexo': None, 'pais': None},  # Alberto García Ortiz (sexo=nan, pais=nan)
    2349796: {'sexo': None, 'pais': None},  # Alberto Gastesi (sexo=nan, pais=nan)
    2685948: {'sexo': None, 'pais': None},  # Alberto Gracia (sexo=nan, pais=nan)
    5592585: {'sexo': None, 'pais': None},  # Alberto José Redondo Villa (sexo=nan, pais=nan)
    5702959: {'sexo': None, 'pais': None},  # Alberto Martos (sexo=nan, pais=nan)
    2903418: {'sexo': None, 'pais': None},  # Alberto Martín Menacho (sexo=nan, pais=nan)
    5652588: {'sexo': None, 'pais': None},  # Alberto Mimbrera Rodríguez (sexo=nan, pais=nan)
    3023544: {'sexo': None, 'pais': None},  # Alberto Muriel (sexo=nan, pais=nan)
    2407283: {'sexo': None, 'pais': None},  # Alberto Ortega (sexo=hombre, pais=nan) | imdb.com/es/name/nm6709466/
    2918999: {'sexo': None, 'pais': None},  # Alberto Rull (sexo=nan, pais=nan)
    2006454: {'sexo': None, 'pais': None},  # Alberto Triano (sexo=nan, pais=nan)
    1796079: {'sexo': None, 'pais': None},  # Alberto Utrera (sexo=nan, pais=nan)
    69875: {'sexo': None, 'pais': None},  # Alberto de Toro (sexo=hombre, pais=nan) | imdb.com/es/name/nm1438231/
    3631222: {'sexo': None, 'pais': None},  # Alejandra Mora (sexo=nan, pais=nan)
    1172340: {'sexo': None, 'pais': None},  # Alejandro Alvarado (sexo=nan, pais=nan) | imdb.com/es/name/nm1163032/
    5709831: {'sexo': None, 'pais': None},  # Alejandro Enríquez (sexo=nan, pais=nan)
    2095405: {'sexo': None, 'pais': None},  # Alejandro G. Salgado (sexo=nan, pais=nan)
    5844744: {'sexo': None, 'pais': None},  # Alejandro Hernández (sexo=hombre, pais=nan)
    1161119: {'sexo': None, 'pais': None},  # Alejandro Marzoa Blasco (sexo=nan, pais=nan)
    1374390: {'sexo': None, 'pais': None},  # Alejandro Millán (sexo=nan, pais=nan) | imdb.com/es/name/nm0590276/
    5399174: {'sexo': None, 'pais': None},  # Alejandro Rojas (sexo=nan, pais=nan)
    2190613: {'sexo': None, 'pais': None},  # Alejandro Toro (sexo=nan, pais=nan)
    5341468: {'sexo': None, 'pais': None},  # Alejandro Torres (sexo=nan, pais=nan)
    2928018: {'sexo': None, 'pais': None},  # Aleksandra Karczewska (sexo=nan, pais=nan)
    1904393: {'sexo': None, 'pais': None},  # Alessia Crocini (sexo=mujer, pais=nan) | imdb.com/es/name/nm8734880/
    5370042: {'sexo': None, 'pais': None},  # Alex Cuellar (sexo=nan, pais=nan)
    1510695: {'sexo': None, 'pais': None},  # Alex Guimerà (sexo=nan, pais=nan) | imdb.com/es/name/nm6807663/
    4346432: {'sexo': None, 'pais': None},  # Alex Mateos (sexo=nan, pais=nan)
    4312256: {'sexo': None, 'pais': None},  # Alex Mañas (sexo=nan, pais=nan)
    1801854: {'sexo': None, 'pais': None},  # Alex Merino (sexo=nan, pais=nan)
    2847644: {'sexo': None, 'pais': None},  # Alex Murrull (sexo=nan, pais=nan)
    5276092: {'sexo': None, 'pais': None},  # Alex Rodríguez (sexo=nan, pais=nan)
    2619632: {'sexo': None, 'pais': None},  # Alex Sardà (sexo=nan, pais=nan)
    1877869: {'sexo': None, 'pais': None},  # Alexandre Cirici Pellicer (sexo=nan, pais=nan)
    1890848: {'sexo': None, 'pais': None},  # Alexis Martinez (sexo=nan, pais=nan)
    3196456: {'sexo': None, 'pais': None},  # Alexis Vietti (sexo=nan, pais=nan)
    5800608: {'sexo': None, 'pais': None},  # Alfonso Aguado (sexo=nan, pais=nan)
    1263849: {'sexo': None, 'pais': None},  # Alfonso Amador (sexo=nan, pais=nan) | imdb.com/es/name/nm0023776/
    1131414: {'sexo': None, 'pais': None},  # Alfonso Cortés-Cavanillas (sexo=hombre, pais=nan)
    1157455: {'sexo': None, 'pais': None},  # Alfonso Domingo (sexo=nan, pais=nan)
    3574547: {'sexo': None, 'pais': None},  # Alfredo Carrasco Alonso (sexo=nan, pais=nan)
    1692922: {'sexo': None, 'pais': None},  # Alfredo Casado (sexo=nan, pais=nan)
    2352923: {'sexo': None, 'pais': None},  # Alfredo Contreras (sexo=nan, pais=nan)
    4293662: {'sexo': None, 'pais': None},  # Alfredo Picazo (sexo=nan, pais=nan)
    5039064: {'sexo': None, 'pais': None},  # Alicia Martínez (sexo=nan, pais=nan)
    1581539: {'sexo': None, 'pais': None},  # Alicia Medina (sexo=nan, pais=nan)
    5581651: {'sexo': None, 'pais': None},  # Alicia Rodríguez (sexo=nan, pais=nan)
    5720969: {'sexo': None, 'pais': None},  # Almudena Monzú (sexo=nan, pais=nan)
    2973700: {'sexo': None, 'pais': None},  # Alvaro Gurrea (sexo=nan, pais=nan)
    3433444: {'sexo': None, 'pais': None},  # Amador Prieto (sexo=nan, pais=nan)
    2112999: {'sexo': None, 'pais': None},  # Amaia Remírez (sexo=nan, pais=nan)
    3722956: {'sexo': None, 'pais': None},  # Amanda García-Tapia (sexo=nan, pais=nan)
    5361958: {'sexo': None, 'pais': None},  # Amanda Lobo (sexo=nan, pais=nan)
    3059119: {'sexo': None, 'pais': None},  # Amat Vallmajor del Pozo (sexo=nan, pais=nan)
    4382373: {'sexo': None, 'pais': None},  # Amaya Villar Navascués (sexo=nan, pais=nan)
    3303861: {'sexo': None, 'pais': None},  # Amos Milbor (sexo=nan, pais=nan)
    5502355: {'sexo': None, 'pais': None},  # Amparo Martínez Barco (sexo=nan, pais=nan)
    1211122: {'sexo': None, 'pais': None},  # Amèlia Mora (sexo=nan, pais=nan) | imdb.com/es/name/nm3306640/
    5276832: {'sexo': None, 'pais': None},  # Ana Barcos (sexo=nan, pais=nan)
    4150281: {'sexo': None, 'pais': None},  # Ana Capella (sexo=nan, pais=nan)
    3002172: {'sexo': None, 'pais': None},  # Ana Cermeño (sexo=nan, pais=nan)
    3286310: {'sexo': None, 'pais': None},  # Ana Folgueira (sexo=nan, pais=nan)
    6243133: {'sexo': None, 'pais': None},  # Ana Galán (sexo=nan, pais=nan)
    5427878: {'sexo': None, 'pais': None},  # Ana González (sexo=nan, pais=nan)
    2016984: {'sexo': None, 'pais': None},  # Ana Graciani (sexo=nan, pais=nan)
    1690566: {'sexo': None, 'pais': None},  # Ana Hurtado (sexo=nan, pais=nan)
    3108570: {'sexo': None, 'pais': None},  # Ana Inés Fernández (sexo=nan, pais=nan)
    4382575: {'sexo': None, 'pais': None},  # Ana L. Martín (sexo=nan, pais=nan)
    2836489: {'sexo': None, 'pais': None},  # Ana Lambarri (sexo=mujer, pais=nan) | imdb.com/es/name/nm3798980/
    3405709: {'sexo': None, 'pais': None},  # Ana Liébana (sexo=nan, pais=nan)
    2345832: {'sexo': None, 'pais': None},  # Ana Ramón Rubio (sexo=nan, pais=nan)
    2092671: {'sexo': None, 'pais': None},  # Ana Schulz (sexo=nan, pais=nan)
    1399736: {'sexo': None, 'pais': None},  # Ana Victoria Pérez (sexo=mujer, pais=nan) | imdb.com/es/name/nm0702096/
    2854671: {'sexo': None, 'pais': None},  # Ana Vázquez (sexo=nan, pais=nan)
    3108914: {'sexo': None, 'pais': None},  # Ana de Alva (sexo=nan, pais=nan)
    1447517: {'sexo': None, 'pais': None},  # Ander Iriarte (sexo=hombre, pais=nan) | imdb.com/es/name/nm5214716/
    1672990: {'sexo': None, 'pais': None},  # Andoni Canela (sexo=nan, pais=nan)
    1695424: {'sexo': None, 'pais': None},  # Andoni de Carlos (sexo=nan, pais=nan)
    2419790: {'sexo': None, 'pais': None},  # Andrea Queralt (sexo=nan, pais=nan)
    3964968: {'sexo': None, 'pais': None},  # Andrea Sebastiá (sexo=nan, pais=nan)
    8452: {'sexo': None, 'pais': None},  # Andrei Tarkovsky (sexo=hombre, pais=nan)
    1636516: {'sexo': None, 'pais': None},  # Andrew Nethery (sexo=nan, pais=nan)
    2422664: {'sexo': None, 'pais': None},  # Andrés Daniel Sainz (sexo=nan, pais=nan)
    1087095: {'sexo': None, 'pais': None},  # Andrés Laszlo (sexo=nan, pais=nan) | imdb.com/es/name/nm0493917/
    1157454: {'sexo': None, 'pais': None},  # Andrés Linares (sexo=nan, pais=nan)
    67263: {'sexo': None, 'pais': None},  # Andrés M. Koppel (sexo=hombre, pais=nan) | imdb.com/es/name/nm1048541/
    2452476: {'sexo': None, 'pais': None},  # Andrés Sanz Vicente (sexo=hombre, pais=nan)
    2434977: {'sexo': None, 'pais': None},  # Angel Codón (sexo=nan, pais=nan)
    6059594: {'sexo': None, 'pais': None},  # Anna M. Bofarull (sexo=nan, pais=nan)
    1562783: {'sexo': None, 'pais': None},  # Anna R. Costa (sexo=nan, pais=nan) | imdb.com/es/name/nm2265852/
    3105484: {'sexo': None, 'pais': None},  # Anna Surinyach (sexo=nan, pais=nan)
    2573595: {'sexo': None, 'pais': None},  # Anna Tusell (sexo=nan, pais=nan)
    4169011: {'sexo': None, 'pais': None},  # Antonina Obrador (sexo=nan, pais=nan)
    1468122: {'sexo': None, 'pais': None},  # Antonio Aguilar Vicente (sexo=nan, pais=nan) | imdb.com/es/name/nm0013470/
    3263007: {'sexo': None, 'pais': None},  # Antonio Bonilla (sexo=nan, pais=nan)
    2535053: {'sexo': None, 'pais': None},  # Antonio Donaire (sexo=nan, pais=nan)
    4180694: {'sexo': None, 'pais': None},  # Antonio Díaz Pérez (sexo=nan, pais=nan)
    2845690: {'sexo': None, 'pais': None},  # Antonio Escámez (sexo=nan, pais=nan)
    2853009: {'sexo': None, 'pais': None},  # Antonio Fernández Torres (sexo=nan, pais=nan)
    2428296: {'sexo': None, 'pais': None},  # Antonio García Jimenez (sexo=nan, pais=nan)
    3630012: {'sexo': None, 'pais': None},  # Antonio Gil Aparicio (sexo=nan, pais=nan)
    2438991: {'sexo': None, 'pais': None},  # Antonio Llamas (sexo=hombre, pais=nan) | imdb.com/es/name/nm10984862/
    1777512: {'sexo': None, 'pais': None},  # Antonio Manuel (sexo=nan, pais=nan)
    4808400: {'sexo': None, 'pais': None},  # Antonio Martín (sexo=nan, pais=nan)
    1173027: {'sexo': None, 'pais': None},  # Antonio Mas Guindal (sexo=hombre, pais=nan) | imdb.com/es/name/nm0555990/
    6320671: {'sexo': None, 'pais': None},  # Antonio Morales (sexo=nan, pais=nan)
    1474206: {'sexo': None, 'pais': None},  # Antonio Ojeda (sexo=nan, pais=nan)
    4990465: {'sexo': None, 'pais': None},  # Antonio R. Cabal (sexo=nan, pais=nan)
    5152588: {'sexo': None, 'pais': None},  # Antonio Sánchez (sexo=nan, pais=nan)
    4839826: {'sexo': None, 'pais': None},  # Antón Álvarez (sexo=nan, pais=nan)
    3840554: {'sexo': None, 'pais': None},  # Araceli Gonda (sexo=nan, pais=nan)
    5220528: {'sexo': None, 'pais': None},  # Arantzazu Gomez Bayon (sexo=nan, pais=nan)
    2799615: {'sexo': None, 'pais': None},  # Area Erina (sexo=nan, pais=nan)
    2072469: {'sexo': None, 'pais': None},  # Ariadna Relea (sexo=nan, pais=nan)
    3774887: {'sexo': None, 'pais': None},  # Ariadna Ulldemolins Abad (sexo=nan, pais=nan)
    3615853: {'sexo': None, 'pais': None},  # Ariadna Vázquez (sexo=nan, pais=nan)
    4431351: {'sexo': None, 'pais': None},  # Arianne Cristiel Dapena (sexo=nan, pais=nan)
    4010268: {'sexo': None, 'pais': None},  # Ariel Castro (sexo=nan, pais=nan)
    5421685: {'sexo': None, 'pais': None},  # Aritz Gorostiaga Eskubi (sexo=nan, pais=nan)
    2053703: {'sexo': None, 'pais': None},  # Armando Ravelo (sexo=hombre, pais=nan)
    3004580: {'sexo': None, 'pais': None},  # Arnau Vilaró (sexo=nan, pais=nan)
    3593301: {'sexo': None, 'pais': None},  # Arturo Andújar (sexo=nan, pais=nan)
    1442310: {'sexo': None, 'pais': None},  # Arturo Menor (sexo=nan, pais=nan)
    3615048: {'sexo': None, 'pais': None},  # Arturo Mombiedro (sexo=nan, pais=nan)
    1368562: {'sexo': None, 'pais': None},  # Arturo Ruiz Serrano (sexo=hombre, pais=nan) | imdb.com/es/name/nm1182332/
    5408871: {'sexo': None, 'pais': None},  # Aser Álvarez González (sexo=nan, pais=nan)
    4426666: {'sexo': None, 'pais': None},  # Asier Andueza (sexo=nan, pais=nan)
    5002083: {'sexo': None, 'pais': None},  # Asier Guerricaechebarría (sexo=nan, pais=nan)
    1820703: {'sexo': None, 'pais': None},  # Asier Urbieta (sexo=nan, pais=nan)
    5070916: {'sexo': None, 'pais': None},  # Asur Fuente (sexo=nan, pais=nan)
    37515: {'sexo': None, 'pais': None},  # Augusto M. Torres (sexo=hombre, pais=nan) | imdb.com/es/name/nm0554937/
    3341404: {'sexo': None, 'pais': None},  # Aurelio Domínguez (sexo=nan, pais=nan)
    4461570: {'sexo': None, 'pais': None},  # Aurimas Valujavičius (sexo=nan, pais=nan)
    1464940: {'sexo': None, 'pais': None},  # Aurora Sulli (sexo=nan, pais=nan) | imdb.com/es/name/nm2609612/
    5421335: {'sexo': None, 'pais': None},  # Azucena Carbajosa Rodriguez (sexo=nan, pais=nan)
    1902030: {'sexo': None, 'pais': None},  # Beatrice Fulconis (sexo=nan, pais=nan)
    2881252: {'sexo': None, 'pais': None},  # Beatriz Alba (sexo=nan, pais=nan)
    4886267: {'sexo': None, 'pais': None},  # Beatriz Carretero (sexo=nan, pais=nan)
    4547559: {'sexo': None, 'pais': None},  # Beatriz Herzog (sexo=nan, pais=nan)
    3195500: {'sexo': None, 'pais': None},  # Beatriz Iznaola (sexo=nan, pais=nan)
    3731035: {'sexo': None, 'pais': None},  # Bego Zubia Gallastegi (sexo=nan, pais=nan)
    4149531: {'sexo': None, 'pais': None},  # Begoña Soler (sexo=nan, pais=nan)
    1435759: {'sexo': None, 'pais': None},  # Beli Martínez (sexo=nan, pais=nan)
    1857851: {'sexo': None, 'pais': None},  # Belén López Albert (sexo=nan, pais=nan)
    1175887: {'sexo': None, 'pais': None},  # Belén Santos (sexo=nan, pais=nan)
    2406756: {'sexo': None, 'pais': None},  # Belén Sánchez Arévalo (sexo=mujer, pais=nan)
    2801723: {'sexo': None, 'pais': None},  # Belén Verdugo (sexo=nan, pais=nan)
    2729812: {'sexo': None, 'pais': None},  # Benet Rosell (sexo=nan, pais=nan)
    5337383: {'sexo': None, 'pais': None},  # Benjamín Lorenzo (sexo=nan, pais=nan)
    2429078: {'sexo': None, 'pais': None},  # Bernabé Bulnes (sexo=nan, pais=nan)
    1566441: {'sexo': None, 'pais': None},  # Bernardo Hernández (sexo=nan, pais=nan)
    1840534: {'sexo': None, 'pais': None},  # Bernardo Sánchez (sexo=nan, pais=nan)
    4073101: {'sexo': None, 'pais': None},  # Bernat Jordà (sexo=nan, pais=nan)
    1168568: {'sexo': None, 'pais': None},  # Bertha Gaztelumendi (sexo=nan, pais=nan) | imdb.com/es/name/nm5296849/
    5718669: {'sexo': None, 'pais': None},  # Beñat Gereka Bikuña (sexo=nan, pais=nan)
    2334966: {'sexo': None, 'pais': None},  # Beñat Iturrioz (sexo=nan, pais=nan)
    4543717: {'sexo': None, 'pais': None},  # Bianca Franceza Omonte (sexo=nan, pais=nan)
    5624444: {'sexo': None, 'pais': None},  # Bibiana Baxevanos (sexo=nan, pais=nan)
    2402950: {'sexo': None, 'pais': None},  # Bibiana Monje (sexo=nan, pais=nan)
    4682724: {'sexo': None, 'pais': None},  # Biel Macià (sexo=nan, pais=nan)
    1828428: {'sexo': None, 'pais': None},  # Blanco Santos (sexo=nan, pais=nan)
    2119721: {'sexo': None, 'pais': None},  # Boris Grgurović (sexo=nan, pais=nan)
    2452490: {'sexo': None, 'pais': None},  # Borja Figuerola (sexo=nan, pais=nan)
    2682372: {'sexo': None, 'pais': None},  # Borja González Santaolalla (sexo=hombre, pais=nan) | imdb.com/es/name/nm2170367/
    4700662: {'sexo': None, 'pais': None},  # Borja Zavala (sexo=nan, pais=nan)
    3022884: {'sexo': None, 'pais': None},  # Borja de la Vega (sexo=nan, pais=nan)
    1179829: {'sexo': None, 'pais': None},  # Bruce Thierry Cheung (sexo=hombre, pais=nan) | imdb.com/es/name/nm2814914/
    4046621: {'sexo': None, 'pais': None},  # Bruno Arias (sexo=nan, pais=nan)
    2873841: {'sexo': None, 'pais': None},  # Bruno Martín (sexo=nan, pais=nan)
    1395595: {'sexo': None, 'pais': None},  # Burnin' Percebes (sexo=nan, pais=nan)
    2374719: {'sexo': None, 'pais': None},  # Bárbara Díez (sexo=nan, pais=nan)
    1180121: {'sexo': None, 'pais': None},  # Camilo Murillo (sexo=nan, pais=nan) | imdb.com/es/name/nm0613915/
    2568717: {'sexo': None, 'pais': None},  # Camilo Villaverde (sexo=nan, pais=nan)
    4710480: {'sexo': None, 'pais': None},  # Candela Izquierdo (sexo=nan, pais=nan)
    1741528: {'sexo': None, 'pais': None},  # Candice Vernon (sexo=nan, pais=nan)
    5949603: {'sexo': None, 'pais': None},  # Carla Calvo (sexo=nan, pais=nan)
    5948658: {'sexo': None, 'pais': None},  # Carla Pereira (sexo=nan, pais=nan)
    3774844: {'sexo': None, 'pais': None},  # Carla Sánchez (sexo=nan, pais=nan)
    1839307: {'sexo': None, 'pais': None},  # Carles Bover Martínez (sexo=nan, pais=nan)
    5368505: {'sexo': None, 'pais': None},  # Carles Cúbos Serra (sexo=nan, pais=nan)
    5061066: {'sexo': None, 'pais': None},  # Carlos Aceituno (sexo=nan, pais=nan)
    1987707: {'sexo': None, 'pais': None},  # Carlos C. Tomé (sexo=hombre, pais=nan)
    5307851: {'sexo': None, 'pais': None},  # Carlos Enrique Palacio (sexo=nan, pais=nan)
    2875833: {'sexo': None, 'pais': None},  # Carlos Essmann (sexo=nan, pais=nan)
    6162301: {'sexo': None, 'pais': None},  # Carlos Giménez (sexo=nan, pais=nan)
    2302227: {'sexo': None, 'pais': None},  # Carlos Langa (sexo=nan, pais=nan)
    5224609: {'sexo': None, 'pais': None},  # Carlos López Olano (sexo=nan, pais=nan)
    3255932: {'sexo': None, 'pais': None},  # Carlos Marbán (sexo=hombre, pais=nan)
    4358732: {'sexo': None, 'pais': None},  # Carlos Mera (sexo=nan, pais=nan)
    3950767: {'sexo': None, 'pais': None},  # Carlos Montes (sexo=nan, pais=nan)
    2294210: {'sexo': None, 'pais': None},  # Carlos Mora (sexo=nan, pais=nan)

In [43]:
PAISES_LATAM_NOMBRES = {
    'México', 'Argentina', 'Brasil', 'Chile', 'Colombia', 'Perú', 'Venezuela',
    'Uruguay', 'Paraguay', 'Bolivia', 'Ecuador', 'Costa Rica', 'Panamá',
    'Guatemala', 'Honduras', 'El Salvador', 'Nicaragua', 'República Dominicana',
    'Cuba', 'Puerto Rico',
}

def extraer_paises_icaa(nacionalidad_str):
    if pd.isna(nacionalidad_str) or not nacionalidad_str:
        return []
    return [re.sub(r'\s*\([\d.]+%\)\s*$', '', p).strip() for p in nacionalidad_str.split(';')]

def tiene_pais_latam_icaa(nacionalidad_str):
    return bool(set(extraer_paises_icaa(nacionalidad_str)) & PAISES_LATAM_NOMBRES)


icaa_peliculas['es_latam'] = icaa_peliculas['nacionalidad_paises_icaa'].apply(tiene_pais_latam_icaa)
peliculas_latam_ids = set(icaa_peliculas.loc[icaa_peliculas['es_latam'], 'icaa_id'].dropna())

person_ids_latam = set(
    credits_df.loc[credits_df['icaa_id'].isin(peliculas_latam_ids), 'person_id'].dropna()
)

print(f"Películas LATAM: {len(peliculas_latam_ids)} / {icaa_peliculas['icaa_id'].notna().sum()}")
print(f"Personas relevantes a LATAM: {len(person_ids_latam)}")

Películas LATAM: 144 / 1775
Personas relevantes a LATAM: 247

In [44]:
pendientes_latam = personas_df[
    (personas_df['sexo_final'].isna() | personas_df['pais_final'].isna())
    & personas_df['person_id'].isin(person_ids_latam)
].copy().sort_values('nombre')

print(f"# {len(pendientes_latam)} personas LATAM con algún dato faltante "
      f"(de {(personas_df['sexo_final'].isna() | personas_df['pais_final'].isna()).sum()} totales) "
      "-- rellena 'sexo'/'pais' donde lo sepas, deja None donde no")
print("CORRECCIONES_MANUALES_PERSONAS_NUEVAS = {")
for _, row in pendientes_latam.iterrows():
    pid = int(row['person_id']) if pd.notna(row['person_id']) else None
    imdb_id = imdb_id_cache.get(str(pid)) if pid is not None else None
    link_imdb = f" | imdb.com/es/name/{imdb_id}/" if imdb_id else ""
    print(f"    {pid}: {{'sexo': None, 'pais': None}},  "
          f"# {row['nombre']} (sexo={row['sexo_final']}, pais={row['pais_final']}){link_imdb}")
print("}")

# 29 personas LATAM con algún dato faltante (de 1312 totales) -- rellena 'sexo'/'pais' donde lo sepas, deja None donde no
CORRECCIONES_MANUALES_PERSONAS_NUEVAS = {
    5844744: {'sexo': None, 'pais': None},  # Alejandro Hernández (sexo=hombre, pais=nan)
    3108914: {'sexo': None, 'pais': None},  # Ana de Alva (sexo=nan, pais=nan)
    3840554: {'sexo': None, 'pais': None},  # Araceli Gonda (sexo=nan, pais=nan)
    3195500: {'sexo': None, 'pais': None},  # Beatriz Iznaola (sexo=nan, pais=nan)
    5727167: {'sexo': None, 'pais': None},  # Carmen López (sexo=mujer, pais=nan)
    3212692: {'sexo': None, 'pais': None},  # Cristina Broquetas (sexo=nan, pais=nan)
    2852263: {'sexo': None, 'pais': None},  # Daniel Monedero (sexo=nan, pais=nan)
    5736743: {'sexo': None, 'pais': None},  # David Pascual (sexo=hombre, pais=nan)
    5597231: {'sexo': None, 'pais': None},  # Diego Martínez (sexo=hombre, pais=nan)
    2865693: {'sexo': None, 'pais': None},  # Francisco Arnal (sexo=nan, pais=nan)
    1835761: {'sexo': None, 'pais': None},  # Gustavo Hernández (sexo=hombre, pais=nan)
    3276081: {'sexo': None, 'pais': None},  # Haizea Pastor (sexo=nan, pais=nan)
    4954090: {'sexo': None, 'pais': None},  # Iker Álvarez (sexo=nan, pais=nan)
    5295734: {'sexo': None, 'pais': None},  # Ingride Santos (sexo=nan, pais=nan)
    2437353: {'sexo': None, 'pais': None},  # Inés Silva (sexo=nan, pais=nan)
    4076684: {'sexo': None, 'pais': None},  # José Ortuño (sexo=nan, pais=nan)
    4916124: {'sexo': None, 'pais': None},  # José Pérez (sexo=nan, pais=nan)
    1564500: {'sexo': None, 'pais': None},  # Juan Clemente Prosper (sexo=nan, pais=nan)
    1097734: {'sexo': None, 'pais': None},  # Juan Luis de No (sexo=nan, pais=nan) | imdb.com/es/name/nm1907971/
    3862769: {'sexo': None, 'pais': None},  # Liliana Torres (sexo=mujer, pais=nan)
    3374272: {'sexo': None, 'pais': None},  # Lucía Herrera (sexo=mujer, pais=nan)
    2915542: {'sexo': None, 'pais': None},  # Lula Gómez (sexo=nan, pais=nan)
    5065139: {'sexo': None, 'pais': None},  # Matías Goldberg (sexo=nan, pais=nan)
    3016177: {'sexo': None, 'pais': None},  # Mercedes Rodrigo (sexo=mujer, pais=nan)
    2494026: {'sexo': None, 'pais': None},  # Pepa G. Ramos (sexo=nan, pais=nan)
    2915538: {'sexo': None, 'pais': None},  # Susana Guardiola (sexo=nan, pais=nan)
    2075885: {'sexo': None, 'pais': None},  # Tirma Pérez (sexo=nan, pais=nan)
    4534713: {'sexo': None, 'pais': None},  # Yurre Ugarte (sexo=nan, pais=nan)
    4983818: {'sexo': None, 'pais': None},  # Ángel Gómez (sexo=hombre, pais=nan)
}

In [ ]:
# 29 personas LATAM con algún dato faltante (de 1312 totales) -- rellena 'sexo'/'pais' donde lo sepas, deja None donde no
CORRECCIONES_MANUALES_PERSONAS_NUEVAS = {
    5844744: {'sexo': 'hombre', 'pais': 'CU'},  # Alejandro Hernández (sexo=hombre, pais=nan)
    3108914: {'sexo': 'mujer', 'pais': 'ES'},  # Ana de Alva (sexo=nan, pais=nan)
    3840554: {'sexo': 'mujer', 'pais': 'ES'},  # Araceli Gonda (sexo=nan, pais=nan)
    3195500: {'sexo': 'mujer', 'pais': 'ES'},  # Beatriz Iznaola (sexo=nan, pais=nan)
    5727167: {'sexo': 'mujer', 'pais': 'ES'},  # Carmen López (sexo=mujer, pais=nan)
    3212692: {'sexo': 'mujer', 'pais': 'ES'},  # Cristina Broquetas (sexo=nan, pais=nan)
    2852263: {'sexo': 'hombre', 'pais': 'ES'},  # Daniel Monedero (sexo=nan, pais=nan)
    5736743: {'sexo': 'hombre', 'pais': 'ES'},  # David Pascual (sexo=hombre, pais=nan)
    5597231: {'sexo': 'hombre', 'pais': 'ES'},  # Diego Martínez (sexo=hombre, pais=nan)
    2865693: {'sexo': 'hombre', 'pais': 'ES'},  # Francisco Arnal (sexo=nan, pais=nan)
    1835761: {'sexo': 'hombre', 'pais': 'UY'},  # Gustavo Hernández (sexo=hombre, pais=nan)
    3276081: {'sexo': 'mujer', 'pais': 'ES'},  # Haizea Pastor (sexo=nan, pais=nan)
    4954090: {'sexo': 'hombre', 'pais': 'ES'},  # Iker Álvarez (sexo=nan, pais=nan)
    5295734: {'sexo': 'mujer', 'pais': 'ES'},  # Ingride Santos (sexo=nan, pais=nan)
    2437353: {'sexo': 'mujer', 'pais': 'ES'},  # Inés Silva (sexo=nan, pais=nan)
    4076684: {'sexo': 'hombre', 'pais': 'ES'},  # José Ortuño (sexo=nan, pais=nan)
    4916124: {'sexo': 'hombre', 'pais': 'ES'},  # José Pérez (sexo=nan, pais=nan)
    1564500: {'sexo': None, 'pais': None},  # Juan Clemente Prosper (sexo=nan, pais=nan)
    1097734: {'sexo': 'hombre', 'pais': 'ES'},  # Juan Luis de No (sexo=nan, pais=nan) | imdb.com/es/name/nm1907971/
    3862769: {'sexo': None, 'pais': None},  # Liliana Torres (sexo=mujer, pais=nan)
    3374272: {'sexo': 'mujer', 'pais': 'ES'},  # Lucía Herrera (sexo=mujer, pais=nan)
    2915542: {'sexo': 'mujer', 'pais': 'ES'},  # Lula Gómez (sexo=nan, pais=nan)
    5065139: {'sexo': 'hombre', 'pais': 'AR'},  # Matías Goldberg (sexo=nan, pais=nan)
    3016177: {'sexo': 'mujer', 'pais': 'ES'},  # Mercedes Rodrigo (sexo=mujer, pais=nan)
    2494026: {'sexo': 'mujer', 'pais': 'ES'},  # Pepa G. Ramos (sexo=nan, pais=nan)
    2915538: {'sexo': 'mujer', 'pais': 'ES'},  # Susana Guardiola (sexo=nan, pais=nan)
    2075885: {'sexo': 'mujer', 'pais': 'ES'},  # Tirma Pérez (sexo=nan, pais=nan)
    4534713: {'sexo': 'mujer', 'pais': 'ES'},  # Yurre Ugarte (sexo=nan, pais=nan)
    4983818: {'sexo': 'hombre', 'pais': 'ES'},  # Ángel Gómez (sexo=hombre, pais=nan)
}

Juan Prosper no es Juan Clemente Prosper (1564500) - Eliminar

In [47]:
person_search_cache['Juan Prosper'] = {"person_id": None, "nombre_tmdb": None}
guardar_cache_json(PERSON_SEARCH_CACHE, person_search_cache)

In [49]:
pendientes_latam = personas_df[
    (personas_df['sexo_final'].isna() | personas_df['pais_final'].isna())
    & personas_df['person_id'].isin(person_ids_latam)
].copy().sort_values('nombre')

print(f"# {len(pendientes_latam)} personas LATAM con algún dato faltante "
      f"(de {(personas_df['sexo_final'].isna() | personas_df['pais_final'].isna()).sum()} totales) "
      "-- rellena 'sexo'/'pais' donde lo sepas, deja None donde no")
print("CORRECCIONES_MANUALES_PERSONAS_NUEVAS = {")
for _, row in pendientes_latam.iterrows():
    pid = int(row['person_id']) if pd.notna(row['person_id']) else None
    imdb_id = imdb_id_cache.get(str(pid)) if pid is not None else None
    link_imdb = f" | imdb.com/es/name/{imdb_id}/" if imdb_id else ""
    print(f"    {pid}: {{'sexo': None, 'pais': None}},  "
          f"# {row['nombre']} (sexo={row['sexo_final']}, pais={row['pais_final']}){link_imdb}")
print("}")

# 2 personas LATAM con algún dato faltante (de 1285 totales) -- rellena 'sexo'/'pais' donde lo sepas, deja None donde no
CORRECCIONES_MANUALES_PERSONAS_NUEVAS = {
    1564500: {'sexo': None, 'pais': None},  # Juan Clemente Prosper (sexo=nan, pais=nan)
    3862769: {'sexo': None, 'pais': None},  # Liliana Torres (sexo=mujer, pais=nan)
}

Update

In [46]:
CORRECCIONES_MANUALES_PERSONAS.update({
    pid: {k: v for k, v in valores.items() if v is not None}
    for pid, valores in CORRECCIONES_MANUALES_PERSONAS_NUEVAS.items()
    if any(v is not None for v in valores.values())
})

personas_df, aplicados, omitidos = aplicar_correcciones_personas_df(personas_df, CORRECCIONES_MANUALES_PERSONAS)

✓ 3517055 (José Corral Llorente): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2018522 (David Matamoros): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3962124 (Marco Lagarde): {'sexo': 'hombre', 'pais': 'AR'}
✓ 1694893 (Pedro Martín Calero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1980582 (Juma Fodde): {'sexo': 'hombre', 'pais': 'IT'}
✓ 3190577 (Jacob Santana): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2628918 (Sergio Dow): {'sexo': 'hombre', 'pais': 'CO'}
✓ 2018520 (Ángeles Hernández): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2549328 (Irene Iborra Rizo): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1115313 (Javier Espada): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1525399 (Ida Cuéllar): {'sexo': 'hombre', 'pais': 'BO'}
✓ 3989209 (David Beltrán i Marí): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1533451 (Laura Baumeister): {'sexo': 'mujer', 'pais': 'NI'}
✓ 1091827 (Diego Yaker): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2568321 (Johanne Gómez Terrero): {'sexo': 'mujer', 'pais': 'DO'}
✓ 4206690 (Tabatta Salinas Caballero): {'sexo': 'mujer', 'pais': 'MX'}
✓ 2662941 (Andrea Gautier): {'sexo': 'mujer', 'pais': 'AR'}
✓ 1731588 (Santiago Fillol): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2282004 (David Berraondo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3202577 (María Zanetti): {'sexo': 'mujer', 'pais': 'AR'}
✓ 1665562 (Maria Mauti): {'sexo': 'mujer', 'pais': 'IT'}
✓ 1338870 (Pavel Giroud): {'sexo': 'hombre', 'pais': 'CU'}
✓ 1962957 (Meritxell Colell Aparicio): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2472549 (Arturo Méndiz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5052862 (Gonzalo Perdomo-Tafur): {'sexo': 'hombre', 'pais': 'CO'}
✓ 2555139 (Mariana Barassi): {'sexo': 'mujer', 'pais': 'AR'}
✓ 1805421 (Isaac Berrocal): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2683614 (Amparo Aguilar): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2427035 (Yennifer Uribe Alzate): {'sexo': 'mujer', 'pais': 'CO'}
✓ 3698547 (Carmina Balaguer): {'sexo': 'mujer', 'pais': 'ES'}
✓ 572115 (Ray Figueroa): {'sexo': 'hombre', 'pais': 'PR'}
✓ 1740764 (Luciano Juncos): {'sexo': 'hombre', 'pais': 'AR'}
✓ 5455347 (Teresa Trasancos): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3039206 (Sandra García Nieto): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1263590 (Manuel Facal): {'sexo': 'hombre', 'pais': 'AR'}
✓ 1605611 (Marçal Cebrian): {'sexo': 'hombre', 'pais': 'ES'}
✓ 82726 (Curro Velázquez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2924495 (Benjamín Herranz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1569540 (Bárbara Alpuente): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5727167 (Carmen López): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4223120 (Rafa Calatayud Cano): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4958781 (Kike Maillo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2654024 (Marta-Libertad Castillo): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1835761 (Gustavo Hernández): {'sexo': 'hombre', 'pais': 'UY'}
✓ 3418854 (Daniel Cebrián): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4983818 (Ángel Gómez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1317749 (David Desola): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2865703 (Ángela Obón): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4808255 (Sabina Méndez): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3893971 (Xabi Zabaleta): {'sexo': 'hombre', 'pais': 'ES'}
✓ 113407 (Arantxa Cuesta): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2103455 (Rodolfo Palacios): {'sexo': 'hombre', 'pais': 'AR'}
✓ 4889588 (Pablo Agüero): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2480566 (Katell Guillou): {'sexo': 'mujer', 'pais': 'FR'}
✓ 1157587 (David Baute): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4640765 (Yaiza Berrocal): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2428561 (Pau Calpe Rufat): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1876833 (Marta Grau): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3156507 (Rafael Russo): {'sexo': 'hombre', 'pais': 'UY'}
✓ 5020311 (Samuel del Amor): {'sexo': 'hombre', 'pais': 'ES'}
✓ 6360702 (David Matamoros Manteca): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1631846 (Álvaro Urtizberea): {'sexo': 'hombre', 'pais': 'AR'}
✓ 1970518 (Erika Halvorsen): {'sexo': 'mujer', 'pais': 'AR'}
✓ 2662836 (Begoña Arostegui): {'sexo': 'no_binario', 'pais': 'ES'}
✓ 31328 (Diego Cagide): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3626927 (Diego Lucero): {'sexo': 'hombre', 'pais': 'AR'}
✓ 4475946 (Mariano Alejandro Rojo): {'sexo': 'hombre', 'pais': 'AR'}
✓ 3530478 (Andrés Martorell): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4385976 (Javier Polo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1608135 (Guillermo Guerrero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1462879 (Enric Pardo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5736743 (David Pascual): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4701879 (Ignasi Guerrero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2522604 (Claudia Reig): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5777600 (Dani Fabra): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4506103 (Andry José Barrientos): {'sexo': 'hombre', 'pais': 'VE'}
✓ 5232889 (Andrés Clemente): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2661260 (Mònica Cambra): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3960226 (Ariadna Fortuny): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3960227 (Clàudia Garcia de Dios): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3374272 (Lucía Herrera): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1764976 (Mariano Donoso): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2962112 (Federico Cardone): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2614503 (Mariana Guzzante): {'sexo': 'mujer', 'pais': 'AR'}
✓ 5674493 (Jesus Caballero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4572706 (Laura Herrero Garvín): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5548470 (Alejandro Andrade Pease): {'sexo': 'hombre', 'pais': 'PE'}
✓ 3928504 (Armando López Muñoz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2929692 (Jon Viar): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3772682 (Lucas Vermal): {'sexo': 'hombre', 'pais': 'AR'}
✓ 3772681 (Edgardo Dobry): {'sexo': 'hombre', 'pais': 'AR'}
✓ 131587 (Víctor Monigote): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4962452 (Pablo Enrique Bossi): {'sexo': 'hombre', 'pais': 'AR'}
✓ 5500234 (Jenifer de la Rosa Martín): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4080092 (Sara Mesa): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3016177 (Mercedes Rodrigo): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5371432 (Helena Girón): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1866952 (Juanma Villar Betancort): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4318654 (Erlyn L. Borges): {'sexo': 'hombre', 'pais': 'CU'}
✓ 4102781 (Facundo Ponce de León): {'sexo': 'hombre', 'pais': 'UY'}
✓ 4865414 (Julio S. de la Fuente): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2239321 (Natacha Kucic): {'sexo': 'mujer', 'pais': 'AR'}
✓ 2467723 (Patricia Pérez Fernández): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2441053 (Mariana Cangas): {'sexo': 'mujer', 'pais': 'AR'}
✓ 3536688 (Miguel García de la Calera): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4075083 (Carolina Alamino): {'sexo': 'mujer', 'pais': 'AR'}
✓ 5456803 (Josè del Corral): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2422984 (Mauro Colombo): {'sexo': 'hombre', 'pais': 'IT'}
✓ 2079453 (Andrés Garrigó): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4019154 (Josepmaria Anglès): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2079455 (Josemaría Muñoz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3102068 (Cira Valiño): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3632587 (Jose Manuel Rebollo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3006682 (Renzo Felippa): {'sexo': 'hombre', 'pais': 'CL'}
✓ 2799326 (Lisandra López Fabe): {'sexo': 'mujer', 'pais': 'CU'}
✓ 1358333 (Arturo Prins): {'sexo': 'hombre', 'pais': 'NL'}
✓ 1756181 (Daresha Kyi): {'sexo': 'mujer', 'pais': 'US'}
✓ 1161761 (Catherine Gund): {'sexo': 'mujer', 'pais': 'US'}
✓ 1262693 (Daniel Augusto): {'sexo': 'hombre', 'pais': 'BR'}
✓ 4180107 (Ernesto Daranas Serrano): {'sexo': 'hombre', 'pais': 'CU'}
✓ 2645524 (Juan Muñoz-Tébar): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5036140 (Jorge Cebrián): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5209434 (José Luis López): {'sexo': 'hombre', 'pais': None}
✓ 589777 (Oscar Martín): {'sexo': 'hombre', 'pais': None}
✓ 2227717 (Laure Desmazières): {'sexo': 'mujer', 'pais': 'FR'}
✓ 3424062 (César Tejeda): {'sexo': 'hombre', 'pais': 'MX'}
✓ 5597231 (Diego Martínez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1645082 (Erika Elizalde): {'sexo': 'mujer', 'pais': 'MX'}
✓ 1195190 (Manuel M. Velasco): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2876280 (Victoria Vázquez): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5467197 (Ignacio López): {'sexo': 'hombre', 'pais': None}
✓ 2261043 (Diego Arjona): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2509031 (Pío Longo): {'sexo': 'hombre', 'pais': 'AR'}
✓ 4163858 (Santiago Alvarado Ilarri): {'sexo': 'hombre', 'pais': 'PE'}
✓ 1443072 (Ramón Salas): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3081311 (Juan A. Zapata): {'sexo': 'hombre', 'pais': 'CO'}
✓ 5844744 (Alejandro Hernández): {'sexo': 'hombre', 'pais': 'CU'}
✓ 2427245 (Julio César Sánchez): {'sexo': 'hombre', 'pais': 'MX'}
✓ 1634868 (José Manuel Colón): {'sexo': 'hombre', 'pais': 'ES'}
✓ 572168 (Darren Kloomok): {'sexo': 'hombre', 'pais': 'US'}
✓ 1432104 (Alejandro Naranjo): {'sexo': 'hombre', 'pais': 'CO'}
✓ 3763970 (Omar Al Abdul Razzak): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1027743 (Manuel J. García): {'sexo': 'hombre', 'pais': 'ES'}
✓ 168769 (Michael Maurer): {'sexo': 'hombre', 'pais': 'DE'}
✓ 2194080 (John Michael Boughn): {'sexo': 'hombre', 'pais': 'US'}
✓ 260267 (Mateo Iribarren): {'sexo': 'hombre', 'pais': 'AR'}
✓ 5054401 (Katherine Tort): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1649980 (Ángela Gallardo Bernal): {'pais': 'ES'}
✓ 3108914 (Ana de Alva): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3840554 (Araceli Gonda): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3195500 (Beatriz Iznaola): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3212692 (Cristina Broquetas): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2852263 (Daniel Monedero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2865693 (Francisco Arnal): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3276081 (Haizea Pastor): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4954090 (Iker Álvarez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5295734 (Ingride Santos): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2437353 (Inés Silva): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4076684 (José Ortuño): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4916124 (José Pérez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1097734 (Juan Luis de No): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2915542 (Lula Gómez): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5065139 (Matías Goldberg): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2494026 (Pepa G. Ramos): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2915538 (Susana Guardiola): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2075885 (Tirma Pérez): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4534713 (Yurre Ugarte): {'sexo': 'mujer', 'pais': 'ES'}

167 correcciones aplicadas, 32 omitidas (person_id no presente en este corpus)

In [50]:
# 2 personas LATAM con algún dato faltante (de 1285 totales) -- rellena 'sexo'/'pais' donde lo sepas, deja None donde no
CORRECCIONES_MANUALES_PERSONAS_NUEVAS = {
    3862769: {'sexo': 'mujer', 'pais': 'ES'},  # Liliana Torres (sexo=mujer, pais=nan)
}

In [51]:
CORRECCIONES_MANUALES_PERSONAS.update({
    pid: {k: v for k, v in valores.items() if v is not None}
    for pid, valores in CORRECCIONES_MANUALES_PERSONAS_NUEVAS.items()
    if any(v is not None for v in valores.values())
})

personas_df, aplicados, omitidos = aplicar_correcciones_personas_df(personas_df, CORRECCIONES_MANUALES_PERSONAS)

✓ 3517055 (José Corral Llorente): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2018522 (David Matamoros): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3962124 (Marco Lagarde): {'sexo': 'hombre', 'pais': 'AR'}
✓ 1694893 (Pedro Martín Calero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1980582 (Juma Fodde): {'sexo': 'hombre', 'pais': 'IT'}
✓ 3190577 (Jacob Santana): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2628918 (Sergio Dow): {'sexo': 'hombre', 'pais': 'CO'}
✓ 2018520 (Ángeles Hernández): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2549328 (Irene Iborra Rizo): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1115313 (Javier Espada): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1525399 (Ida Cuéllar): {'sexo': 'hombre', 'pais': 'BO'}
✓ 3989209 (David Beltrán i Marí): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1533451 (Laura Baumeister): {'sexo': 'mujer', 'pais': 'NI'}
✓ 1091827 (Diego Yaker): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2568321 (Johanne Gómez Terrero): {'sexo': 'mujer', 'pais': 'DO'}
✓ 4206690 (Tabatta Salinas Caballero): {'sexo': 'mujer', 'pais': 'MX'}
✓ 2662941 (Andrea Gautier): {'sexo': 'mujer', 'pais': 'AR'}
✓ 1731588 (Santiago Fillol): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2282004 (David Berraondo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3202577 (María Zanetti): {'sexo': 'mujer', 'pais': 'AR'}
✓ 1665562 (Maria Mauti): {'sexo': 'mujer', 'pais': 'IT'}
✓ 1338870 (Pavel Giroud): {'sexo': 'hombre', 'pais': 'CU'}
✓ 1962957 (Meritxell Colell Aparicio): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2472549 (Arturo Méndiz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5052862 (Gonzalo Perdomo-Tafur): {'sexo': 'hombre', 'pais': 'CO'}
✓ 2555139 (Mariana Barassi): {'sexo': 'mujer', 'pais': 'AR'}
✓ 1805421 (Isaac Berrocal): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2683614 (Amparo Aguilar): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2427035 (Yennifer Uribe Alzate): {'sexo': 'mujer', 'pais': 'CO'}
✓ 3698547 (Carmina Balaguer): {'sexo': 'mujer', 'pais': 'ES'}
✓ 572115 (Ray Figueroa): {'sexo': 'hombre', 'pais': 'PR'}
✓ 1740764 (Luciano Juncos): {'sexo': 'hombre', 'pais': 'AR'}
✓ 5455347 (Teresa Trasancos): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3039206 (Sandra García Nieto): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1263590 (Manuel Facal): {'sexo': 'hombre', 'pais': 'AR'}
✓ 1605611 (Marçal Cebrian): {'sexo': 'hombre', 'pais': 'ES'}
✓ 82726 (Curro Velázquez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2924495 (Benjamín Herranz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1569540 (Bárbara Alpuente): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5727167 (Carmen López): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4223120 (Rafa Calatayud Cano): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4958781 (Kike Maillo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2654024 (Marta-Libertad Castillo): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1835761 (Gustavo Hernández): {'sexo': 'hombre', 'pais': 'UY'}
✓ 3418854 (Daniel Cebrián): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4983818 (Ángel Gómez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1317749 (David Desola): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2865703 (Ángela Obón): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4808255 (Sabina Méndez): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3893971 (Xabi Zabaleta): {'sexo': 'hombre', 'pais': 'ES'}
✓ 113407 (Arantxa Cuesta): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2103455 (Rodolfo Palacios): {'sexo': 'hombre', 'pais': 'AR'}
✓ 4889588 (Pablo Agüero): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2480566 (Katell Guillou): {'sexo': 'mujer', 'pais': 'FR'}
✓ 1157587 (David Baute): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4640765 (Yaiza Berrocal): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2428561 (Pau Calpe Rufat): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1876833 (Marta Grau): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3156507 (Rafael Russo): {'sexo': 'hombre', 'pais': 'UY'}
✓ 5020311 (Samuel del Amor): {'sexo': 'hombre', 'pais': 'ES'}
✓ 6360702 (David Matamoros Manteca): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1631846 (Álvaro Urtizberea): {'sexo': 'hombre', 'pais': 'AR'}
✓ 1970518 (Erika Halvorsen): {'sexo': 'mujer', 'pais': 'AR'}
✓ 2662836 (Begoña Arostegui): {'sexo': 'no_binario', 'pais': 'ES'}
✓ 31328 (Diego Cagide): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3626927 (Diego Lucero): {'sexo': 'hombre', 'pais': 'AR'}
✓ 4475946 (Mariano Alejandro Rojo): {'sexo': 'hombre', 'pais': 'AR'}
✓ 3530478 (Andrés Martorell): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4385976 (Javier Polo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1608135 (Guillermo Guerrero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1462879 (Enric Pardo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5736743 (David Pascual): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4701879 (Ignasi Guerrero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2522604 (Claudia Reig): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5777600 (Dani Fabra): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4506103 (Andry José Barrientos): {'sexo': 'hombre', 'pais': 'VE'}
✓ 5232889 (Andrés Clemente): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2661260 (Mònica Cambra): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3960226 (Ariadna Fortuny): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3960227 (Clàudia Garcia de Dios): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3374272 (Lucía Herrera): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1764976 (Mariano Donoso): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2962112 (Federico Cardone): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2614503 (Mariana Guzzante): {'sexo': 'mujer', 'pais': 'AR'}
✓ 5674493 (Jesus Caballero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4572706 (Laura Herrero Garvín): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5548470 (Alejandro Andrade Pease): {'sexo': 'hombre', 'pais': 'PE'}
✓ 3928504 (Armando López Muñoz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2929692 (Jon Viar): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3772682 (Lucas Vermal): {'sexo': 'hombre', 'pais': 'AR'}
✓ 3772681 (Edgardo Dobry): {'sexo': 'hombre', 'pais': 'AR'}
✓ 131587 (Víctor Monigote): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4962452 (Pablo Enrique Bossi): {'sexo': 'hombre', 'pais': 'AR'}
✓ 5500234 (Jenifer de la Rosa Martín): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4080092 (Sara Mesa): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3016177 (Mercedes Rodrigo): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5371432 (Helena Girón): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1866952 (Juanma Villar Betancort): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4318654 (Erlyn L. Borges): {'sexo': 'hombre', 'pais': 'CU'}
✓ 4102781 (Facundo Ponce de León): {'sexo': 'hombre', 'pais': 'UY'}
✓ 4865414 (Julio S. de la Fuente): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2239321 (Natacha Kucic): {'sexo': 'mujer', 'pais': 'AR'}
✓ 2467723 (Patricia Pérez Fernández): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2441053 (Mariana Cangas): {'sexo': 'mujer', 'pais': 'AR'}
✓ 3536688 (Miguel García de la Calera): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4075083 (Carolina Alamino): {'sexo': 'mujer', 'pais': 'AR'}
✓ 5456803 (Josè del Corral): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2422984 (Mauro Colombo): {'sexo': 'hombre', 'pais': 'IT'}
✓ 2079453 (Andrés Garrigó): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4019154 (Josepmaria Anglès): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2079455 (Josemaría Muñoz): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3102068 (Cira Valiño): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3632587 (Jose Manuel Rebollo): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3006682 (Renzo Felippa): {'sexo': 'hombre', 'pais': 'CL'}
✓ 2799326 (Lisandra López Fabe): {'sexo': 'mujer', 'pais': 'CU'}
✓ 1358333 (Arturo Prins): {'sexo': 'hombre', 'pais': 'NL'}
✓ 1756181 (Daresha Kyi): {'sexo': 'mujer', 'pais': 'US'}
✓ 1161761 (Catherine Gund): {'sexo': 'mujer', 'pais': 'US'}
✓ 1262693 (Daniel Augusto): {'sexo': 'hombre', 'pais': 'BR'}
✓ 4180107 (Ernesto Daranas Serrano): {'sexo': 'hombre', 'pais': 'CU'}
✓ 2645524 (Juan Muñoz-Tébar): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5036140 (Jorge Cebrián): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5209434 (José Luis López): {'sexo': 'hombre', 'pais': None}
✓ 589777 (Oscar Martín): {'sexo': 'hombre', 'pais': None}
✓ 2227717 (Laure Desmazières): {'sexo': 'mujer', 'pais': 'FR'}
✓ 3424062 (César Tejeda): {'sexo': 'hombre', 'pais': 'MX'}
✓ 5597231 (Diego Martínez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1645082 (Erika Elizalde): {'sexo': 'mujer', 'pais': 'MX'}
✓ 1195190 (Manuel M. Velasco): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2876280 (Victoria Vázquez): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5467197 (Ignacio López): {'sexo': 'hombre', 'pais': None}
✓ 2261043 (Diego Arjona): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2509031 (Pío Longo): {'sexo': 'hombre', 'pais': 'AR'}
✓ 4163858 (Santiago Alvarado Ilarri): {'sexo': 'hombre', 'pais': 'PE'}
✓ 1443072 (Ramón Salas): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3081311 (Juan A. Zapata): {'sexo': 'hombre', 'pais': 'CO'}
✓ 5844744 (Alejandro Hernández): {'sexo': 'hombre', 'pais': 'CU'}
✓ 2427245 (Julio César Sánchez): {'sexo': 'hombre', 'pais': 'MX'}
✓ 1634868 (José Manuel Colón): {'sexo': 'hombre', 'pais': 'ES'}
✓ 572168 (Darren Kloomok): {'sexo': 'hombre', 'pais': 'US'}
✓ 1432104 (Alejandro Naranjo): {'sexo': 'hombre', 'pais': 'CO'}
✓ 3763970 (Omar Al Abdul Razzak): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1027743 (Manuel J. García): {'sexo': 'hombre', 'pais': 'ES'}
✓ 168769 (Michael Maurer): {'sexo': 'hombre', 'pais': 'DE'}
✓ 2194080 (John Michael Boughn): {'sexo': 'hombre', 'pais': 'US'}
✓ 260267 (Mateo Iribarren): {'sexo': 'hombre', 'pais': 'AR'}
✓ 5054401 (Katherine Tort): {'sexo': 'mujer', 'pais': 'ES'}
✓ 1649980 (Ángela Gallardo Bernal): {'pais': 'ES'}
✓ 3108914 (Ana de Alva): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3840554 (Araceli Gonda): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3195500 (Beatriz Iznaola): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3212692 (Cristina Broquetas): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2852263 (Daniel Monedero): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2865693 (Francisco Arnal): {'sexo': 'hombre', 'pais': 'ES'}
✓ 3276081 (Haizea Pastor): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4954090 (Iker Álvarez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 5295734 (Ingride Santos): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2437353 (Inés Silva): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4076684 (José Ortuño): {'sexo': 'hombre', 'pais': 'ES'}
✓ 4916124 (José Pérez): {'sexo': 'hombre', 'pais': 'ES'}
✓ 1097734 (Juan Luis de No): {'sexo': 'hombre', 'pais': 'ES'}
✓ 2915542 (Lula Gómez): {'sexo': 'mujer', 'pais': 'ES'}
✓ 5065139 (Matías Goldberg): {'sexo': 'hombre', 'pais': 'AR'}
✓ 2494026 (Pepa G. Ramos): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2915538 (Susana Guardiola): {'sexo': 'mujer', 'pais': 'ES'}
✓ 2075885 (Tirma Pérez): {'sexo': 'mujer', 'pais': 'ES'}
✓ 4534713 (Yurre Ugarte): {'sexo': 'mujer', 'pais': 'ES'}
✓ 3862769 (Liliana Torres): {'sexo': 'mujer', 'pais': 'ES'}

168 correcciones aplicadas, 32 omitidas (person_id no presente en este corpus)

In [52]:
print(f"Cobertura final tras correcciones manuales:")
print(f"Sexo: {personas_df['sexo_final'].notna().sum()} / {len(personas_df)}")
print(f"País: {personas_df['pais_final'].notna().sum()} / {len(personas_df)}")
print(f"\nFuente del dato de sexo:\n{personas_df['fuente_sexo'].value_counts(dropna=False)}")
print(f"\nFuente del dato de país:\n{personas_df['fuente_pais'].value_counts(dropna=False)}")

Cobertura final tras correcciones manuales:
Sexo: 1173 / 2262
País: 988 / 2262

Fuente del dato de sexo:
fuente_sexo
NaN         1089
tmdb         829
wikidata     177
manual       167
Name: count, dtype: int64

Fuente del dato de país:
fuente_pais
None               1271
tmdb_heuristico     561
wikidata            262
manual              168
Name: count, dtype: int64

In [53]:
def personas_df_pendientes(personas_df):
    pendientes = personas_df[personas_df['sexo_final'].isna() | personas_df['pais_final'].isna()]
    print(f"{len(pendientes)} personas con algún dato faltante de {len(personas_df)} totales")
    for _, row in pendientes.iterrows():
        print(f"  person_id={row['person_id']}: {row['nombre']} "
              f"(sexo={row['sexo_final']}, pais={row['pais_final']})")
    return pendientes

pendientes_personas = personas_df_pendientes(personas_df)

1284 personas con algún dato faltante de 2262 totales
  person_id=1930872.0: Ferrán Navarro-Beltrán (sexo=hombre, pais=nan)
  person_id=1114075.0: Vicente Pérez Herrero (sexo=nan, pais=nan)
  person_id=4748222.0: Jose Ramón Fernández Pinazo (sexo=nan, pais=nan)
  person_id=2434913.0: César Souto Vilanova (sexo=nan, pais=nan)
  person_id=2434919.0: Cristina Liz Graña (sexo=nan, pais=nan)
  person_id=5349292.0: Ramón Pineda (sexo=nan, pais=nan)
  person_id=2522953.0: Patricia Franquesa (sexo=nan, pais=nan)
  person_id=1284828.0: Juan Barrero (sexo=nan, pais=nan)
  person_id=5955689.0: Moisés Garrido (sexo=nan, pais=nan)
  person_id=3567270.0: Evgeny Yablokov (sexo=nan, pais=nan)
  person_id=3778185.0: Nick Igea (sexo=nan, pais=nan)
  person_id=1624337.0: Pau Faus (sexo=nan, pais=nan)
  person_id=3884067.0: Júlia R. Aymar (sexo=nan, pais=nan)
  person_id=4382575.0: Ana L. Martín (sexo=nan, pais=nan)
  person_id=5694090.0: Marta García (sexo=nan, pais=nan)
  person_id=1105225.0: Héctor Claramunt (sexo=hombre, pais=nan)
  person_id=2445361.0: Valeriano López (sexo=nan, pais=nan)
  person_id=5702959.0: Alberto Martos (sexo=nan, pais=nan)
  person_id=1063543.0: Verónica Fernández (sexo=mujer, pais=nan)
  person_id=3324578.0: Xiana do Teixeiro (sexo=nan, pais=nan)
  person_id=17000.0: Elena Manrique (sexo=mujer, pais=nan)
  person_id=3217186.0: Chiara Avesani (sexo=nan, pais=nan)
  person_id=2349411.0: Matteo Delbò (sexo=nan, pais=nan)
  person_id=3538411.0: Lluís Sellarès (sexo=hombre, pais=nan)
  person_id=2372329.0: Pere Altimira (sexo=nan, pais=nan)
  person_id=4237979.0: Coré Ruiz (sexo=nan, pais=nan)
  person_id=4442477.0: Raquel Herrera (sexo=nan, pais=nan)
  person_id=3960733.0: Juan Perez Fajardo (sexo=nan, pais=nan)
  person_id=1641338.0: David Calle (sexo=hombre, pais=nan)
  person_id=1121668.0: Germán Roda (sexo=nan, pais=nan)
  person_id=1909488.0: José Manuel Gómez Vidal (sexo=nan, pais=nan)
  person_id=3811620.0: José Manuel Rodríguez Calvo (sexo=nan, pais=nan)
  person_id=6346352.0: Sandra Romero (sexo=nan, pais=nan)
  person_id=5308218.0: Sandra Román (sexo=nan, pais=nan)
  person_id=1331228.0: David Pantaleón (sexo=nan, pais=nan)
  person_id=3303861.0: Amos Milbor (sexo=nan, pais=nan)
  person_id=4081519.0: Joaquín Carmona Hidalgo (sexo=nan, pais=nan)
  person_id=2587719.0: Juan Potau (sexo=nan, pais=nan)
  person_id=3998718.0: Laura Ferrero (sexo=nan, pais=nan)
  person_id=4152418.0: Manuel Rossell (sexo=nan, pais=nan)
  person_id=2856339.0: Albert Badia (sexo=nan, pais=nan)
  person_id=4776926.0: Lucía Casañ Rodríguez (sexo=nan, pais=nan)
  person_id=4896283.0: Itsaso Arana (sexo=nan, pais=nan)
  person_id=2610510.0: Larraitz Zuazo (sexo=nan, pais=nan)
  person_id=2584715.0: Zuri Goikoetxea (sexo=nan, pais=nan)
  person_id=1624805.0: Ainhoa Andraka (sexo=nan, pais=nan)
  person_id=1049263.0: Abel García Roure (sexo=nan, pais=nan)
  person_id=2095830.0: Vicente Arlandis (sexo=nan, pais=nan)
  person_id=3184568.0: Manu Trillo (sexo=nan, pais=nan)
  person_id=5775607.0: Darío García Sanz (sexo=nan, pais=nan)
  person_id=2631444.0: Francesca Català Margarit (sexo=nan, pais=nan)
  person_id=1788543.0: Carmen Fernández Villalba (sexo=nan, pais=nan)
  person_id=1809110.0: Rafa Alberola (sexo=nan, pais=nan)
  person_id=2617011.0: Daniel Luna (sexo=nan, pais=nan)
  person_id=3438202.0: María Luisa Calderón (sexo=nan, pais=nan)
  person_id=1908907.0: Montse Ganges (sexo=nan, pais=nan)
  person_id=5646425.0: Patricia Pérez (sexo=nan, pais=nan)
  person_id=5318950.0: Liena Cid Navia (sexo=nan, pais=nan)
  person_id=3022884.0: Borja de la Vega (sexo=nan, pais=nan)
  person_id=6088764.0: Laia Soler Aragonés (sexo=nan, pais=nan)
  person_id=3262866.0: Ekain Albite (sexo=hombre, pais=nan)
  person_id=3959299.0: Adrià Roca (sexo=hombre, pais=nan)
  person_id=3959300.0: Nicolau Mallofré (sexo=hombre, pais=nan)
  person_id=3959289.0: Mikel Ibarguren (sexo=hombre, pais=nan)
  person_id=2046903.0: Magda Calabrese (sexo=nan, pais=nan)
  person_id=2767302.0: María Gisele Royo (sexo=nan, pais=nan)
  person_id=2494000.0: Julia de Castro (sexo=nan, pais=nan)
  person_id=570219.0: Manuel Serrano (sexo=hombre, pais=nan)
  person_id=4633425.0: Francisco R. Tejedor (sexo=nan, pais=nan)
  person_id=5181798.0: Cristina Menéndez Torralba (sexo=nan, pais=nan)
  person_id=1669189.0: Valentina Viso (sexo=nan, pais=nan)
  person_id=1388779.0: Ramon Luque (sexo=nan, pais=nan)
  person_id=2806169.0: Abigail Schaaff (sexo=nan, pais=nan)
  person_id=4511432.0: Èric Moral (sexo=nan, pais=nan)
  person_id=4342635.0: Núria Velasco (sexo=nan, pais=nan)
  person_id=3702941.0: Melo Gon (sexo=mujer, pais=nan)
  person_id=4149569.0: Moisés Martín (sexo=hombre, pais=nan)
  person_id=2189495.0: Gemma Blasco (sexo=mujer, pais=nan)
  person_id=2391063.0: Eva Pauné (sexo=nan, pais=nan)
  person_id=3365472.0: Rocío Martín (sexo=mujer, pais=nan)
  person_id=2168024.0: José Luis García Cossío (sexo=nan, pais=nan)
  person_id=2018521.0: Miguel Ibáñez Monroy (sexo=nan, pais=nan)
  person_id=1578295.0: Ignasi Rubio (sexo=nan, pais=nan)
  person_id=1778368.0: Fran Carballal (sexo=nan, pais=nan)
  person_id=3255932.0: Carlos Marbán (sexo=hombre, pais=nan)
  person_id=1012214.0: José Antonio Hergueta (sexo=nan, pais=nan)
  person_id=5834871.0: Jorge Peña Pezo (sexo=nan, pais=nan)
  person_id=2950177.0: Leticia Salvago (sexo=nan, pais=nan)
  person_id=5326801.0: Luis C. Lagos (sexo=nan, pais=nan)
  person_id=5337383.0: Benjamín Lorenzo (sexo=nan, pais=nan)
  person_id=2760432.0: Miguel A. Mejias (sexo=nan, pais=nan)
  person_id=5361958.0: Amanda Lobo (sexo=nan, pais=nan)
  person_id=2632890.0: Marina Parés (sexo=nan, pais=nan)
  person_id=4460475.0: Elisa Múgica (sexo=nan, pais=nan)
  person_id=2203960.0: Rafa Molés (sexo=hombre, pais=nan)
  person_id=2203959.0: Pepe Andreu (sexo=nan, pais=nan)
  person_id=1183079.0: Ólafur Rögnvaldsson (sexo=hombre, pais=nan)
  person_id=5370042.0: Alex Cuellar (sexo=nan, pais=nan)
  person_id=4603658.0: Rafael Sánchez G. (sexo=nan, pais=nan)
  person_id=2163917.0: Héctor Escandell (sexo=nan, pais=nan)
  person_id=932841.0: Francisco Prada (sexo=nan, pais=nan)
  person_id=2461318.0: Mamen Díaz (sexo=mujer, pais=nan)
  person_id=1668830.0: Violeta Rodríguez (sexo=mujer, pais=nan)
  person_id=1768555.0: Ivan Ruiz Flores (sexo=nan, pais=nan)
  person_id=5427878.0: Ana González (sexo=nan, pais=nan)
  person_id=3149032.0: Marina Rodríguez Colás (sexo=nan, pais=nan)
  person_id=1764966.0: Marisa Crespo (sexo=nan, pais=nan)
  person_id=1828428.0: Blanco Santos (sexo=nan, pais=nan)
  person_id=833156.0: Javier Lorenzo (sexo=hombre, pais=nan)
  person_id=2225317.0: Nacho Blasco (sexo=nan, pais=nan)
  person_id=5981442.0: Francesc Xavier Manuel (sexo=nan, pais=nan)
  person_id=2781728.0: Jaume Claret Muxart (sexo=nan, pais=nan)
  person_id=1147996.0: Fernando Merinero (sexo=nan, pais=nan)
  person_id=5217820.0: David Arnanz (sexo=nan, pais=nan)
  person_id=3059119.0: Amat Vallmajor del Pozo (sexo=nan, pais=nan)
  person_id=6389083.0: José Victor Fuentes (sexo=nan, pais=nan)
  person_id=5011589.0: Fernando Alcántara (sexo=nan, pais=nan)
  person_id=1679853.0: Fernando González Gómez (sexo=nan, pais=nan)
  person_id=3607097.0: Rubén Sánchez Trigos (sexo=nan, pais=nan)
  person_id=3099796.0: Javier Trigales (sexo=nan, pais=nan)
  person_id=1726169.0: Miquel Sanz (sexo=nan, pais=nan)
  person_id=1348362.0: Juan Francisco Viruega (sexo=nan, pais=nan)
  person_id=1543018.0: Álvaro de la Hoz (sexo=nan, pais=nan)
  person_id=2095405.0: Alejandro G. Salgado (sexo=nan, pais=nan)
  person_id=6033605.0: Marta Sánchez (sexo=nan, pais=nan)
  person_id=2619632.0: Alex Sardà (sexo=nan, pais=nan)
  person_id=2682878.0: Paco Mateo (sexo=hombre, pais=nan)
  person_id=5644533.0: Luis Santana Déniz (sexo=nan, pais=nan)
  person_id=2524429.0: Isabel Fernández (sexo=nan, pais=nan)
  person_id=1957068.0: Teresa Bellón (sexo=nan, pais=nan)
  person_id=1957066.0: César F. Calvillo (sexo=nan, pais=nan)
  person_id=6362320.0: Josu Martínez (sexo=nan, pais=nan)
  person_id=1077643.0: Regina Alvarez (sexo=nan, pais=nan)
  person_id=1820703.0: Asier Urbieta (sexo=nan, pais=nan)
  person_id=1695424.0: Andoni de Carlos (sexo=nan, pais=nan)
  person_id=6163639.0: Paula Ortiz (sexo=nan, pais=nan)
  person_id=3629503.0: Victòria Morell Salom (sexo=mujer, pais=nan)
  person_id=5364688.0: Guillermo Galoe (sexo=nan, pais=nan)
  person_id=2373399.0: Polo Menárguez (sexo=nan, pais=nan)
  person_id=260953.0: Nicolás Muñoz (sexo=hombre, pais=nan)
  person_id=3389899.0: Raphaëlle Perez (sexo=nan, pais=FR)
  person_id=1167112.0: David S. Olivas (sexo=hombre, pais=nan)
  person_id=4086869.0: Claire Ducreux (sexo=nan, pais=nan)
  person_id=4638503.0: Patricia de Luna (sexo=nan, pais=nan)
  person_id=2577039.0: Laura Sisteró (sexo=nan, pais=nan)
  person_id=5425079.0: Juan Pablo Mejía Caicedo (sexo=nan, pais=nan)
  person_id=2805759.0: Jorge Bartolomé (sexo=nan, pais=nan)
  person_id=5399174.0: Alejandro Rojas (sexo=nan, pais=nan)
  person_id=1950950.0: Juan Sebastián Vásquez (sexo=hombre, pais=nan)
  person_id=2044765.0: Xavier Baig (sexo=nan, pais=nan)
  person_id=589505.0: Oscar Moreno (sexo=hombre, pais=nan)
  person_id=2773693.0: Víctor Luengo (sexo=nan, pais=nan)
  person_id=1814108.0: Virginia Díaz (sexo=nan, pais=nan)
  person_id=2896953.0: Javier Tolentino (sexo=nan, pais=nan)
  person_id=3631222.0: Alejandra Mora (sexo=nan, pais=nan)
  person_id=2896955.0: Doriam Alonso (sexo=nan, pais=nan)
  person_id=1890848.0: Alexis Martinez (sexo=nan, pais=nan)
  person_id=1695482.0: Kurro González (sexo=nan, pais=nan)
  person_id=5276832.0: Ana Barcos (sexo=nan, pais=nan)
  person_id=3574547.0: Alfredo Carrasco Alonso (sexo=nan, pais=nan)
  person_id=2406756.0: Belén Sánchez Arévalo (sexo=mujer, pais=nan)
  person_id=1581539.0: Alicia Medina (sexo=nan, pais=nan)
  person_id=2244942.0: Marc Serena (sexo=nan, pais=nan)
  person_id=1270701.0: J.J. Winlove (sexo=nan, pais=nan)
  person_id=4162971.0: Noel Gálvez (sexo=hombre, pais=nan)
  person_id=3290639.0: Irene Niubó (sexo=nan, pais=nan)
  person_id=1507365.0: Luis E. Parés (sexo=nan, pais=nan)
  person_id=2350322.0: Juan Palacios (sexo=nan, pais=nan)
  person_id=1463084.0: Juan Antonio Moreno Amador (sexo=hombre, pais=nan)
  person_id=5524932.0: Claudia Clemente (sexo=nan, pais=nan)
  person_id=2918999.0: Alberto Rull (sexo=nan, pais=nan)
  person_id=4346432.0: Alex Mateos (sexo=nan, pais=nan)
  person_id=3844697.0: Julio Martín Alarcón (sexo=nan, pais=nan)
  person_id=6142772.0: Alba Prol Cid (sexo=nan, pais=nan)
  person_id=4736109.0: Raúl García (sexo=nan, pais=nan)
  person_id=2801723.0: Belén Verdugo (sexo=nan, pais=nan)
  person_id=2592415.0: José María Izquierdo (sexo=nan, pais=nan)
  person_id=1149065.0: Raúl Santos (sexo=hombre, pais=nan)
  person_id=3072665.0: Javier Ramírez (sexo=nan, pais=nan)
  person_id=2927784.0: Miguel Angel Bonequi Trujillo (sexo=nan, pais=nan)
  person_id=6243133.0: Ana Galán (sexo=nan, pais=nan)
  person_id=5593416.0: Jordi Torra (sexo=nan, pais=nan)
  person_id=1414901.0: Fin Edquist (sexo=hombre, pais=nan)
  person_id=1932129.0: Domingo J. González (sexo=nan, pais=nan)
  person_id=5444595.0: Elena de Vera (sexo=nan, pais=nan)
  person_id=2205048.0: Víctor Escribano (sexo=nan, pais=nan)
  person_id=3106232.0: David Riaño (sexo=nan, pais=nan)
  person_id=2038507.0: Raúl Jiménez Pastor (sexo=nan, pais=nan)
  person_id=2915594.0: Víctor Cerdán (sexo=nan, pais=nan)
  person_id=1367435.0: Luis Tinoco (sexo=hombre, pais=nan)
  person_id=2725314.0: Ricard Peitx (sexo=nan, pais=nan)
  person_id=2468094.0: Inge Mendioroz (sexo=nan, pais=nan)
  person_id=5657782.0: Idoia Garzes Aldazabal (sexo=nan, pais=nan)
  person_id=5247630.0: Gerard Peris (sexo=nan, pais=nan)
  person_id=68234.0: Ezekiel Montes (sexo=hombre, pais=nan)
  person_id=2257939.0: Javier Jauregui (sexo=nan, pais=nan)
  person_id=3081963.0: Víctor García (sexo=nan, pais=nan)
  person_id=1799272.0: Guillem Clua (sexo=nan, pais=nan)
  person_id=2006454.0: Alberto Triano (sexo=nan, pais=nan)
  person_id=1133344.0: Javier López Barreira (sexo=nan, pais=nan)
  person_id=1857851.0: Belén López Albert (sexo=nan, pais=nan)
  person_id=992040.0: Olga Iglesias (sexo=mujer, pais=nan)
  person_id=2558765.0: Juan Antonio Chavero (sexo=nan, pais=nan)
  person_id=3055331.0: Yolanda Centeno (sexo=nan, pais=nan)
  person_id=3055337.0: Jesús Luque (sexo=nan, pais=nan)
  person_id=1185966.0: Lorena Iglesias (sexo=mujer, pais=nan)
  person_id=5935015.0: Juan González (sexo=nan, pais=nan)
  person_id=3127416.0: Juan Gamero (sexo=nan, pais=nan)
  person_id=2796656.0: Carmen Rodríguez (sexo=nan, pais=nan)
  person_id=1399736.0: Ana Victoria Pérez (sexo=mujer, pais=nan)
  person_id=2443976.0: María José Moreno (sexo=nan, pais=nan)
  person_id=2525261.0: Shadi Adib (sexo=nan, pais=nan)
  person_id=4745815.0: Xavier Romero (sexo=nan, pais=nan)
  person_id=1082714.0: Miguel Barros (sexo=hombre, pais=nan)
  person_id=1724318.0: Ángeles Huerta (sexo=mujer, pais=nan)
  person_id=1070463.0: Manuel H. Martín (sexo=nan, pais=nan)
  person_id=2853009.0: Antonio Fernández Torres (sexo=nan, pais=nan)
  person_id=4762461.0: Salvador Calvo (sexo=nan, pais=nan)
  person_id=2928016.0: Luís Gibert (sexo=nan, pais=nan)
  person_id=3484808.0: Eva Veiga (sexo=nan, pais=nan)
  person_id=4030050.0: José Gasset (sexo=nan, pais=nan)
  person_id=6264805.0: Eloy Enciso Cachafeiro (sexo=nan, pais=nan)
  person_id=4065553.0: Pablo Riesgo (sexo=nan, pais=nan)
  person_id=1266452.0: Jose Val Bal (sexo=nan, pais=nan)
  person_id=3304948.0: Pol Rodríguez (sexo=nan, pais=nan)
  person_id=2998049.0: Alberto Armas Díaz (sexo=nan, pais=nan)
  person_id=2333553.0: Víctor Conde (sexo=hombre, pais=nan)
  person_id=5224596.0: Felipe Villaplana (sexo=nan, pais=nan)
  person_id=5224609.0: Carlos López Olano (sexo=nan, pais=nan)
  person_id=2836489.0: Ana Lambarri (sexo=mujer, pais=nan)
  person_id=1438827.0: Vicent Monsonís (sexo=hombre, pais=nan)
  person_id=1826479.0: Marga Melià (sexo=nan, pais=nan)
  person_id=1958700.0: Eduardo Solá Franco (sexo=nan, pais=nan)
  person_id=2839663.0: Mireia Llinàs (sexo=nan, pais=nan)
  person_id=1074001.0: Jorge Laplace (sexo=hombre, pais=nan)
  person_id=2478401.0: Santiago Requejo (sexo=hombre, pais=nan)
  person_id=3592180.0: Juan A. Anguita (sexo=nan, pais=nan)
  person_id=1672995.0: Unai Canela (sexo=nan, pais=nan)
  person_id=1672990.0: Andoni Canela (sexo=nan, pais=nan)
  person_id=1413007.0: Adolfo Dufour (sexo=hombre, pais=nan)
  person_id=2263746.0: Fernando Vera (sexo=nan, pais=nan)
  person_id=5644505.0: Jesús Ponce (sexo=nan, pais=nan)
  person_id=5270914.0: Nuria Martín Esteban (sexo=nan, pais=nan)
  person_id=5503054.0: Sergio Rodrigo Ruiz (sexo=nan, pais=nan)
  person_id=1024687.0: Gemma Ventura (sexo=mujer, pais=nan)
  person_id=2016984.0: Ana Graciani (sexo=nan, pais=nan)
  person_id=1187864.0: José Ángel Esteban (sexo=nan, pais=nan)
  person_id=4424916.0: Marta Espar (sexo=nan, pais=ES)
  person_id=4424914.0: Maiol Virgili (sexo=nan, pais=nan)
  person_id=1131414.0: Alfonso Cortés-Cavanillas (sexo=hombre, pais=nan)
  person_id=3512702.0: Jorge Navarro de Lemus (sexo=nan, pais=nan)
  person_id=2435292.0: Nerea Castro (sexo=nan, pais=nan)
  person_id=3233145.0: Iker Elorrieta (sexo=nan, pais=nan)
  person_id=2648709.0: Flora González Villanueva (sexo=nan, pais=nan)
  person_id=1635445.0: Celia Novis (sexo=nan, pais=nan)
  person_id=2545879.0: Patxi Uriz (sexo=nan, pais=nan)
  person_id=2545881.0: Jordi Matas (sexo=nan, pais=nan)
  person_id=2374150.0: Tatiana Rodríguez (sexo=nan, pais=nan)
  person_id=2885188.0: Javier Chacártegui (sexo=nan, pais=nan)
  person_id=4881904.0: Rylend Grant (sexo=nan, pais=nan)
  person_id=5790674.0: Eva Montoya (sexo=nan, pais=nan)
  person_id=4580493.0: José Cabanach (sexo=nan, pais=nan)
  person_id=225972.0: Jon Sagalá (sexo=nan, pais=nan)
  person_id=3701720.0: Paula Labordeta (sexo=nan, pais=nan)
  person_id=3979041.0: Miguel Mena (sexo=nan, pais=nan)
  person_id=4813064.0: Ángela Labordeta (sexo=nan, pais=nan)
  person_id=5421335.0: Azucena Carbajosa Rodriguez (sexo=nan, pais=nan)
  person_id=5421103.0: Ramón Lara (sexo=nan, pais=nan)
  person_id=1261502.0: Màrius Sánchez (sexo=hombre, pais=nan)
  person_id=2448460.0: Silvia Merino (sexo=nan, pais=nan)
  person_id=2348064.0: Hugo de la Riva (sexo=nan, pais=nan)
  person_id=3405709.0: Ana Liébana (sexo=nan, pais=nan)
  person_id=2256047.0: Javier Fernández Vázquez (sexo=nan, pais=nan)
  person_id=4470945.0: Elisa Marinas (sexo=nan, pais=nan)
  person_id=2556742.0: Luis Mancha (sexo=nan, pais=nan)
  person_id=1895984.0: Néstor F. Dennis (sexo=hombre, pais=nan)
  person_id=1851075.0: Ivan Zekić (sexo=hombre, pais=nan)
  person_id=5332377.0: Vukasin Soc (sexo=nan, pais=nan)
  person_id=1416286.0: Mateja Popović (sexo=hombre, pais=nan)
  person_id=2135546.0: Petar Mihajlović (sexo=nan, pais=nan)
  person_id=2119721.0: Boris Grgurović (sexo=nan, pais=nan)
  person_id=5332384.0: Jelena Andelovski (sexo=nan, pais=nan)
  person_id=3615048.0: Arturo Mombiedro (sexo=nan, pais=nan)
  person_id=2213460.0: Pep Bonet (sexo=nan, pais=nan)
  person_id=5299192.0: Catalina Solivellas (sexo=nan, pais=nan)
  person_id=1322494.0: César del Álamo (sexo=nan, pais=nan)
  person_id=5040794.0: Lorenzo Sanz Fernández (sexo=nan, pais=nan)
  person_id=589777.0: Oscar Martín (sexo=hombre, pais=nan)
  person_id=5640808.0: Irene Bailo Carramiñana (sexo=nan, pais=nan)
  person_id=2945902.0: Celine Ducreux (sexo=nan, pais=nan)
  person_id=2204600.0: Senén Fernández (sexo=nan, pais=nan)
  person_id=4923208.0: Toni Andújar (sexo=nan, pais=nan)
  person_id=4923210.0: Erick Straver (sexo=nan, pais=nan)
  person_id=3196456.0: Alexis Vietti (sexo=nan, pais=nan)
  person_id=2941579.0: Regina Álvarez Lorenzo (sexo=mujer, pais=nan)
  person_id=1482515.0: Olatz Arroyo (sexo=nan, pais=nan)
  person_id=3127742.0: Cesar Vallejo (sexo=nan, pais=nan)
  person_id=1063315.0: David Esteban Cubero (sexo=nan, pais=nan)
  person_id=2560104.0: Eduardo Navarro (sexo=nan, pais=nan)
  person_id=4276328.0: Octavio Lasheras (sexo=nan, pais=nan)
  person_id=4543767.0: Matías Boero Lutz (sexo=nan, pais=nan)
  person_id=4282773.0: Raúl Capdevila (sexo=nan, pais=nan)
  person_id=1185970.0: Miguel Esteban (sexo=nan, pais=nan)
  person_id=1396455.0: Claro García (sexo=nan, pais=nan)
  person_id=2426873.0: David Muñoz (sexo=hombre, pais=nan)
  person_id=2258086.0: Javier García Arredondo (sexo=nan, pais=nan)
  person_id=4772220.0: Juan Mayorga (sexo=nan, pais=nan)
  person_id=2046902.0: Richard Zubelzu (sexo=nan, pais=nan)
  person_id=4416357.0: Gabriel Chicano (sexo=nan, pais=nan)
  person_id=5376528.0: Javier Canales Sepúlveda (sexo=nan, pais=nan)
  person_id=2297013.0: Elena Cid Sebastián (sexo=nan, pais=nan)
  person_id=5048846.0: Adrián García (sexo=nan, pais=nan)
  person_id=1211122.0: Amèlia Mora (sexo=nan, pais=nan)
  person_id=4577431.0: Jaime Noguera (sexo=nan, pais=nan)
  person_id=2289823.0: Eric du Bellay (sexo=nan, pais=nan)
  person_id=2706985.0: Mario Parra (sexo=nan, pais=nan)
  person_id=5934164.0: Juan San Martín (sexo=nan, pais=nan)
  person_id=2264685.0: Carolina Bassecourt (sexo=nan, pais=nan)
  person_id=5842166.0: Sandra García Bueno (sexo=nan, pais=nan)
  person_id=2555250.0: Toni Escandell (sexo=nan, pais=nan)
  person_id=2555252.0: Marina Seguí (sexo=nan, pais=nan)
  person_id=2124703.0: Marta Armengol (sexo=mujer, pais=nan)
  person_id=967367.0: Cristina Campos (sexo=mujer, pais=nan)
  person_id=2453244.0: Olga Mansilla (sexo=nan, pais=nan)
  person_id=1902030.0: Beatrice Fulconis (sexo=nan, pais=nan)
  person_id=1795939.0: Inés Acebes (sexo=nan, pais=nan)
  person_id=4316906.0: Marta Ruiz de Viñaspre (sexo=nan, pais=nan)
  person_id=5406230.0: Jesús García (sexo=nan, pais=nan)
  person_id=2269274.0: Roberto Bueso (sexo=nan, pais=nan)
  person_id=1799781.0: Javier González (sexo=hombre, pais=nan)

## 12. Construcción final -- solo dimensiones (`direccion`, `guion`)

Aquí SÍ se puede finalizar: `direccion`/`guion` son tablas de personas con
`sexo`/`país`, no dependen de `pelicula_id`. Lo que NO se construye todavía
son `direccion_peliculas`/`guion_peliculas` -- esas referencian películas,
y `pelicula_id` (la clave surrogada real) todavía no existe; se asigna en
el notebook de tablas finales. Construirlas aquí con `icaa_id`/`tmdb_id`
como referencia temporal sería una capa de indirección frágil que habría
que deshacer después.

In [54]:
def construir_dim_personas(rol, prefijo):
    creditos_rol = credits_df[credits_df['rol'] == rol].copy()

    con_id = creditos_rol[creditos_rol['person_id'].notna()].drop_duplicates(subset=['person_id'])
    sin_id = creditos_rol[creditos_rol['person_id'].isna()].drop_duplicates(subset=['nombre'])

    personas_unicas = (
        con_id[['person_id']]
        .merge(
            personas_df[['person_id', 'nombre', 'sexo_final', 'fuente_sexo',
                         'pais_final', 'fuente_pais']],
            on='person_id', how='left', validate='many_to_one'
        )
    )
    personas_unicas['nombre_credito_original'] = None

    personas_sin_match = (
        sin_id[['nombre']].rename(columns={'nombre': 'nombre_credito_original'})
    )
    personas_sin_match['person_id'] = None
    personas_sin_match['nombre'] = personas_sin_match['nombre_credito_original']
    personas_sin_match['sexo_final'] = None
    personas_sin_match['fuente_sexo'] = None
    personas_sin_match['pais_final'] = None
    personas_sin_match['fuente_pais'] = None

    dim = pd.concat([personas_unicas, personas_sin_match], ignore_index=True).reset_index(drop=True)
    ids_generados = [f"{prefijo}_{i:04d}" for i in range(1, len(dim) + 1)]
    dim.insert(0, f"{prefijo}_id", ids_generados)
    dim = dim.rename(columns={'sexo_final': 'sexo', 'pais_final': 'pais'})
    return dim


direccion = construir_dim_personas('director', 'dir')
guion = construir_dim_personas('guionista', 'gui')

print(f"direccion: {len(direccion)} personas únicas")
print(f"guion: {len(guion)} personas únicas")

direccion: 1649 personas únicas
guion: 2323 personas únicas

### Correcciones manuales -- personas sin `person_id`

Igual que antes, pero ahora la clave es `dir_id`/`gui_id` en vez de
`person_id`, porque estas personas no tienen `person_id` en absoluto
(TMDB nunca las encontró).

In [60]:
def personas_pendientes(dim_df, prefijo):
    pendientes = dim_df[dim_df['sexo'].isna() | dim_df['pais'].isna()]
    print(f"{prefijo}: {len(pendientes)} personas con algún dato faltante de {len(dim_df)} totales")
    for _, row in pendientes.iterrows():
        nombre = row['nombre'] if pd.notna(row['nombre']) else row.get('nombre_credito_original')
        print(f"  {row[f'{prefijo}_id']}: {nombre} (sexo={row['sexo']}, pais={row['pais']}, person_id={row['person_id']})")
    return pendientes

print("=== DIRECCIÓN ===")
pendientes_direccion = personas_pendientes(direccion, 'dir')
print("\n=== GUION ===")
pendientes_guion = personas_pendientes(guion, 'gui')

=== DIRECCIÓN ===
dir: 954 personas con algún dato faltante de 1649 totales
  dir_0002: Ferrán Navarro-Beltrán (sexo=hombre, pais=nan, person_id=1930872.0)
  dir_0003: Vicente Pérez Herrero (sexo=nan, pais=nan, person_id=1114075.0)
  dir_0006: César Souto Vilanova (sexo=nan, pais=nan, person_id=2434913.0)
  dir_0008: Patricia Franquesa (sexo=nan, pais=nan, person_id=2522953.0)
  dir_0012: Evgeny Yablokov (sexo=nan, pais=nan, person_id=3567270.0)
  dir_0013: Nick Igea (sexo=nan, pais=nan, person_id=3778185.0)
  dir_0016: Pau Faus (sexo=nan, pais=nan, person_id=1624337.0)
  dir_0017: Ana L. Martín (sexo=nan, pais=nan, person_id=4382575.0)
  dir_0018: Héctor Claramunt (sexo=hombre, pais=nan, person_id=1105225.0)
  dir_0019: Valeriano López (sexo=nan, pais=nan, person_id=2445361.0)
  dir_0021: Alberto Martos (sexo=nan, pais=nan, person_id=5702959.0)
  dir_0023: Elena Manrique (sexo=mujer, pais=nan, person_id=17000.0)
  dir_0024: Chiara Avesani (sexo=nan, pais=nan, person_id=3217186.0)
  dir_0025: Matteo Delbò (sexo=nan, pais=nan, person_id=2349411.0)
  dir_0029: Coré Ruiz (sexo=nan, pais=nan, person_id=4237979.0)
  dir_0030: Juan Perez Fajardo (sexo=nan, pais=nan, person_id=3960733.0)
  dir_0032: Germán Roda (sexo=nan, pais=nan, person_id=1121668.0)
  dir_0034: José Manuel Gómez Vidal (sexo=nan, pais=nan, person_id=1909488.0)
  dir_0035: Sandra Romero (sexo=nan, pais=nan, person_id=6346352.0)
  dir_0037: Sandra Román (sexo=nan, pais=nan, person_id=5308218.0)
  dir_0043: David Pantaleón (sexo=nan, pais=nan, person_id=1331228.0)
  dir_0044: Joaquín Carmona Hidalgo (sexo=nan, pais=nan, person_id=4081519.0)
  dir_0048: Manuel Rossell (sexo=nan, pais=nan, person_id=4152418.0)
  dir_0050: Albert Badia (sexo=nan, pais=nan, person_id=2856339.0)
  dir_0051: Lucía Casañ Rodríguez (sexo=nan, pais=nan, person_id=4776926.0)
  dir_0052: Itsaso Arana (sexo=nan, pais=nan, person_id=4896283.0)
  dir_0055: Larraitz Zuazo (sexo=nan, pais=nan, person_id=2610510.0)
  dir_0056: Zuri Goikoetxea (sexo=nan, pais=nan, person_id=2584715.0)
  dir_0057: Ainhoa Andraka (sexo=nan, pais=nan, person_id=1624805.0)
  dir_0058: Abel García Roure (sexo=nan, pais=nan, person_id=1049263.0)
  dir_0059: Manu Trillo (sexo=nan, pais=nan, person_id=3184568.0)
  dir_0061: Francesca Català Margarit (sexo=nan, pais=nan, person_id=2631444.0)
  dir_0064: Daniel Luna (sexo=nan, pais=nan, person_id=2617011.0)
  dir_0071: Patricia Pérez (sexo=nan, pais=nan, person_id=5646425.0)
  dir_0072: Liena Cid Navia (sexo=nan, pais=nan, person_id=5318950.0)
  dir_0074: Borja de la Vega (sexo=nan, pais=nan, person_id=3022884.0)
  dir_0076: Ekain Albite (sexo=hombre, pais=nan, person_id=3262866.0)
  dir_0077: Adrià Roca (sexo=hombre, pais=nan, person_id=3959299.0)
  dir_0078: Nicolau Mallofré (sexo=hombre, pais=nan, person_id=3959300.0)
  dir_0079: Mikel Ibarguren (sexo=hombre, pais=nan, person_id=3959289.0)
  dir_0080: Magda Calabrese (sexo=nan, pais=nan, person_id=2046903.0)
  dir_0081: María Gisele Royo (sexo=nan, pais=nan, person_id=2767302.0)
  dir_0082: Julia de Castro (sexo=nan, pais=nan, person_id=2494000.0)
  dir_0083: Manuel Serrano (sexo=hombre, pais=nan, person_id=570219.0)
  dir_0085: Ramon Luque (sexo=nan, pais=nan, person_id=1388779.0)
  dir_0091: Abigail Schaaff (sexo=nan, pais=nan, person_id=2806169.0)
  dir_0092: Melo Gon (sexo=mujer, pais=nan, person_id=3702941.0)
  dir_0093: Moisés Martín (sexo=hombre, pais=nan, person_id=4149569.0)
  dir_0095: Gemma Blasco (sexo=mujer, pais=nan, person_id=2189495.0)
  dir_0096: Rocío Martín (sexo=mujer, pais=nan, person_id=3365472.0)
  dir_0097: José Luis García Cossío (sexo=nan, pais=nan, person_id=2168024.0)
  dir_0100: Carlos Marbán (sexo=hombre, pais=nan, person_id=3255932.0)
  dir_0101: José Antonio Hergueta (sexo=nan, pais=nan, person_id=1012214.0)
  dir_0106: Luis C. Lagos (sexo=nan, pais=nan, person_id=5326801.0)
  dir_0109: Miguel A. Mejias (sexo=nan, pais=nan, person_id=2760432.0)
  dir_0114: Rafa Molés (sexo=hombre, pais=nan, person_id=2203960.0)
  dir_0115: Pepe Andreu (sexo=nan, pais=nan, person_id=2203959.0)
  dir_0116: Alex Cuellar (sexo=nan, pais=nan, person_id=5370042.0)
  dir_0117: Rafael Sánchez G. (sexo=nan, pais=nan, person_id=4603658.0)
  dir_0118: Héctor Escandell (sexo=nan, pais=nan, person_id=2163917.0)
  dir_0122: Mamen Díaz (sexo=mujer, pais=nan, person_id=2461318.0)
  dir_0124: Ivan Ruiz Flores (sexo=nan, pais=nan, person_id=1768555.0)
  dir_0126: Marisa Crespo (sexo=nan, pais=nan, person_id=1764966.0)
  dir_0128: Blanco Santos (sexo=nan, pais=nan, person_id=1828428.0)
  dir_0134: Jaume Claret Muxart (sexo=nan, pais=nan, person_id=2781728.0)
  dir_0136: Fernando Merinero (sexo=nan, pais=nan, person_id=1147996.0)
  dir_0138: Amat Vallmajor del Pozo (sexo=nan, pais=nan, person_id=3059119.0)
  dir_0139: José Victor Fuentes (sexo=nan, pais=nan, person_id=6389083.0)
  dir_0141: Fernando González Gómez (sexo=nan, pais=nan, person_id=1679853.0)
  dir_0144: Juan Francisco Viruega (sexo=nan, pais=nan, person_id=1348362.0)
  dir_0146: Álvaro de la Hoz (sexo=nan, pais=nan, person_id=1543018.0)
  dir_0147: Alejandro G. Salgado (sexo=nan, pais=nan, person_id=2095405.0)
  dir_0149: Alex Sardà (sexo=nan, pais=nan, person_id=2619632.0)
  dir_0151: Isabel Fernández (sexo=nan, pais=nan, person_id=2524429.0)
  dir_0153: Teresa Bellón (sexo=nan, pais=nan, person_id=1957068.0)
  dir_0154: César F. Calvillo (sexo=nan, pais=nan, person_id=1957066.0)
  dir_0155: Josu Martínez (sexo=nan, pais=nan, person_id=6362320.0)
  dir_0159: Asier Urbieta (sexo=nan, pais=nan, person_id=1820703.0)
  dir_0162: Paula Ortiz (sexo=nan, pais=nan, person_id=6163639.0)
  dir_0165: Victòria Morell Salom (sexo=mujer, pais=nan, person_id=3629503.0)
  dir_0168: Guillermo Galoe (sexo=nan, pais=nan, person_id=5364688.0)
  dir_0169: Polo Menárguez (sexo=nan, pais=nan, person_id=2373399.0)
  dir_0171: Nicolás Muñoz (sexo=hombre, pais=nan, person_id=260953.0)
  dir_0177: Patricia de Luna (sexo=nan, pais=nan, person_id=4638503.0)
  dir_0179: Laura Sisteró (sexo=nan, pais=nan, person_id=2577039.0)
  dir_0180: Juan Pablo Mejía Caicedo (sexo=nan, pais=nan, person_id=5425079.0)
  dir_0183: Alejandro Rojas (sexo=nan, pais=nan, person_id=5399174.0)
  dir_0184: Juan Sebastián Vásquez (sexo=hombre, pais=nan, person_id=1950950.0)
  dir_0185: Xavier Baig (sexo=nan, pais=nan, person_id=2044765.0)
  dir_0186: Víctor Luengo (sexo=nan, pais=nan, person_id=2773693.0)
  dir_0189: Javier Tolentino (sexo=nan, pais=nan, person_id=2896953.0)
  dir_0192: Kurro González (sexo=nan, pais=nan, person_id=1695482.0)
  dir_0194: Alfredo Carrasco Alonso (sexo=nan, pais=nan, person_id=3574547.0)
  dir_0200: Marc Serena (sexo=nan, pais=nan, person_id=2244942.0)
  dir_0202: J.J. Winlove (sexo=nan, pais=nan, person_id=1270701.0)
  dir_0203: Noel Gálvez (sexo=hombre, pais=nan, person_id=4162971.0)
  dir_0205: Luis E. Parés (sexo=nan, pais=nan, person_id=1507365.0)
  dir_0206: Juan Palacios (sexo=nan, pais=nan, person_id=2350322.0)
  dir_0208: Juan Antonio Moreno Amador (sexo=hombre, pais=nan, person_id=1463084.0)
  dir_0214: Alberto Rull (sexo=nan, pais=nan, person_id=2918999.0)
  dir_0215: Alba Prol Cid (sexo=nan, pais=nan, person_id=6142772.0)
  dir_0216: Raúl García (sexo=nan, pais=nan, person_id=4736109.0)
  dir_0218: Belén Verdugo (sexo=nan, pais=nan, person_id=2801723.0)
  dir_0222: Miguel Angel Bonequi Trujillo (sexo=nan, pais=nan, person_id=2927784.0)
  dir_0224: Jordi Torra (sexo=nan, pais=nan, person_id=5593416.0)
  dir_0226: Domingo J. González (sexo=nan, pais=nan, person_id=1932129.0)
  dir_0227: Víctor Escribano (sexo=nan, pais=nan, person_id=2205048.0)
  dir_0230: Víctor Cerdán (sexo=nan, pais=nan, person_id=2915594.0)
  dir_0232: Luis Tinoco (sexo=hombre, pais=nan, person_id=1367435.0)
  dir_0233: Ricard Peitx (sexo=nan, pais=nan, person_id=2725314.0)
  dir_0235: Inge Mendioroz (sexo=nan, pais=nan, person_id=2468094.0)
  dir_0237: Gerard Peris (sexo=nan, pais=nan, person_id=5247630.0)
  dir_0238: Ezekiel Montes (sexo=hombre, pais=nan, person_id=68234.0)
  dir_0241: Víctor García (sexo=nan, pais=nan, person_id=3081963.0)
  dir_0246: Alberto Triano (sexo=nan, pais=nan, person_id=2006454.0)
  dir_0250: Belén López Albert (sexo=nan, pais=nan, person_id=1857851.0)
  dir_0253: Juan Antonio Chavero (sexo=nan, pais=nan, person_id=2558765.0)
  dir_0254: Yolanda Centeno (sexo=nan, pais=nan, person_id=3055331.0)
  dir_0258: Juan Gamero (sexo=nan, pais=nan, person_id=3127416.0)
  dir_0259: Ana Victoria Pérez (sexo=mujer, pais=nan, person_id=1399736.0)
  dir_0261: Shadi Adib (sexo=nan, pais=nan, person_id=2525261.0)
  dir_0264: Ángeles Huerta (sexo=mujer, pais=nan, person_id=1724318.0)
  dir_0265: Manuel H. Martín (sexo=nan, pais=nan, person_id=1070463.0)
  dir_0268: Salvador Calvo (sexo=nan, pais=nan, person_id=4762461.0)
  dir_0269: Luís Gibert (sexo=nan, pais=nan, person_id=2928016.0)
  dir_0276: José Gasset (sexo=nan, pais=nan, person_id=4030050.0)
  dir_0277: Eloy Enciso Cachafeiro (sexo=nan, pais=nan, person_id=6264805.0)
  dir_0279: Pablo Riesgo (sexo=nan, pais=nan, person_id=4065553.0)
  dir_0280: Jose Val Bal (sexo=nan, pais=nan, person_id=1266452.0)
  dir_0282: Pol Rodríguez (sexo=nan, pais=nan, person_id=3304948.0)
  dir_0286: Alberto Armas Díaz (sexo=nan, pais=nan, person_id=2998049.0)
  dir_0287: Víctor Conde (sexo=hombre, pais=nan, person_id=2333553.0)
  dir_0288: Felipe Villaplana (sexo=nan, pais=nan, person_id=5224596.0)
  dir_0291: Ana Lambarri (sexo=mujer, pais=nan, person_id=2836489.0)
  dir_0292: Vicent Monsonís (sexo=hombre, pais=nan, person_id=1438827.0)
  dir_0293: Marga Melià (sexo=nan, pais=nan, person_id=1826479.0)
  dir_0296: Santiago Requejo (sexo=hombre, pais=nan, person_id=2478401.0)
  dir_0298: Juan A. Anguita (sexo=nan, pais=nan, person_id=3592180.0)
  dir_0299: Unai Canela (sexo=nan, pais=nan, person_id=1672995.0)
  dir_0300: Adolfo Dufour (sexo=hombre, pais=nan, person_id=1413007.0)
  dir_0302: Fernando Vera (sexo=nan, pais=nan, person_id=2263746.0)
  dir_0303: Jesús Ponce (sexo=nan, pais=nan, person_id=5644505.0)
  dir_0308: Sergio Rodrigo Ruiz (sexo=nan, pais=nan, person_id=5503054.0)
  dir_0311: Marta Espar (sexo=nan, pais=ES, person_id=4424916.0)
  dir_0312: Maiol Virgili (sexo=nan, pais=nan, person_id=4424914.0)
  dir_0313: Alfonso Cortés-Cavanillas (sexo=hombre, pais=nan, person_id=1131414.0)
  dir_0316: Iker Elorrieta (sexo=nan, pais=nan, person_id=3233145.0)
  dir_0318: Celia Novis (sexo=nan, pais=nan, person_id=1635445.0)
  dir_0319: Patxi Uriz (sexo=nan, pais=nan, person_id=2545879.0)
  dir_0320: Carmen Rodríguez (sexo=nan, pais=nan, person_id=2796656.0)
  dir_0323: José Cabanach (sexo=nan, pais=nan, person_id=4580493.0)
  dir_0327: Paula Labordeta (sexo=nan, pais=nan, person_id=3701720.0)
  dir_0328: Azucena Carbajosa Rodriguez (sexo=nan, pais=nan, person_id=5421335.0)
  dir_0330: Ramón Lara (sexo=nan, pais=nan, person_id=5421103.0)
  dir_0331: Hugo de la Riva (sexo=nan, pais=nan, person_id=2348064.0)
  dir_0332: Javier Fernández Vázquez (sexo=nan, pais=nan, person_id=2256047.0)
  dir_0338: Luis Mancha (sexo=nan, pais=nan, person_id=2556742.0)
  dir_0339: Néstor F. Dennis (sexo=hombre, pais=nan, person_id=1895984.0)
  dir_0342: Arturo Mombiedro (sexo=nan, pais=nan, person_id=3615048.0)
  dir_0343: Pep Bonet (sexo=nan, pais=nan, person_id=2213460.0)
  dir_0351: Lorenzo Sanz Fernández (sexo=nan, pais=nan, person_id=5040794.0)
  dir_0352: Oscar Martín (sexo=hombre, pais=nan, person_id=589777.0)
  dir_0353: Irene Bailo Carramiñana (sexo=nan, pais=nan, person_id=5640808.0)
  dir_0354: Senén Fernández (sexo=nan, pais=nan, person_id=2204600.0)
  dir_0355: Toni Andújar (sexo=nan, pais=nan, person_id=4923208.0)
  dir_0360: Cesar Vallejo (sexo=nan, pais=nan, person_id=3127742.0)
  dir_0362: Octavio Lasheras (sexo=nan, pais=nan, person_id=4276328.0)
  dir_0363: Matías Boero Lutz (sexo=nan, pais=nan, person_id=4543767.0)
  dir_0364: Raúl Capdevila (sexo=nan, pais=nan, person_id=4282773.0)
  dir_0370: Richard Zubelzu (sexo=nan, pais=nan, person_id=2046902.0)
  dir_0372: Gabriel Chicano (sexo=nan, pais=nan, person_id=4416357.0)
  dir_0373: Javier Canales Sepúlveda (sexo=nan, pais=nan, person_id=5376528.0)
  dir_0374: Elena Cid Sebastián (sexo=nan, pais=nan, person_id=2297013.0)
  dir_0375: Adrián García (sexo=nan, pais=nan, person_id=5048846.0)
  dir_0380: Eric du Bellay (sexo=nan, pais=nan, person_id=2289823.0)
  dir_0382: Juan San Martín (sexo=nan, pais=nan, person_id=5934164.0)
  dir_0383: Carolina Bassecourt (sexo=nan, pais=nan, person_id=2264685.0)
  dir_0385: Sandra García Bueno (sexo=nan, pais=nan, person_id=5842166.0)
  dir_0387: Toni Escandell (sexo=nan, pais=nan, person_id=2555250.0)
  dir_0388: Marina Seguí (sexo=nan, pais=nan, person_id=2555252.0)
  dir_0394: Jesús García (sexo=nan, pais=nan, person_id=5406230.0)
  dir_0397: Roberto Bueso (sexo=nan, pais=nan, person_id=2269274.0)
  dir_0398: Luis Navarrete (sexo=nan, pais=nan, person_id=5967557.0)
  dir_0400: Antonio Donaire (sexo=nan, pais=nan, person_id=2535053.0)
  dir_0401: Javier Morales Pérez (sexo=nan, pais=nan, person_id=3683806.0)
  dir_0404: Alberto Mimbrera Rodríguez (sexo=nan, pais=nan, person_id=5652588.0)
  dir_0405: Jesús Eguía Armenteros (sexo=nan, pais=nan, person_id=3139891.0)
  dir_0406: Patricia Font (sexo=nan, pais=nan, person_id=3699683.0)
  dir_0407: Samantha López Speranza (sexo=nan, pais=nan, person_id=3104885.0)
  dir_0408: Alex Murrull (sexo=nan, pais=nan, person_id=2847644.0)
  dir_0412: Elvira Lindo (sexo=mujer, pais=nan, person_id=278087.0)
  dir_0414: Sergi Pitarch Garrido (sexo=nan, pais=nan, person_id=4266108.0)
  dir_0416: Giampaolo Manfreda (sexo=nan, pais=nan, person_id=3435792.0)
  dir_0417: Iván Roiz (sexo=nan, pais=nan, person_id=2261583.0)
  dir_0418: Álvaro Priante (sexo=nan, pais=nan, person_id=2261582.0)
  dir_0419: David Martín de los Santos (sexo=hombre, pais=nan, person_id=1493049.0)
  dir_0423: Fran Torres (sexo=hombre, pais=nan, person_id=1042761.0)
  dir_0424: Jacobo Martínez (sexo=nan, pais=nan, person_id=1441961.0)
  dir_0429: Rubén Capilla (sexo=nan, pais=nan, person_id=5641009.0)
  dir_0430: Alex Rodríguez (sexo=nan, pais=nan, person_id=5276092.0)
  dir_0432: Juanjo Castro (sexo=nan, pais=nan, person_id=2367863.0)
  dir_0434: Manu Gómez (sexo=nan, pais=nan, person_id=1784530.0)
  dir_0441: Jordi Sánchez (sexo=nan, pais=nan, person_id=5775340.0)
  dir_0449: Ángeles Reiné (sexo=mujer, pais=nan, person_id=2264674.0)
  dir_0450: Mar Olid (sexo=mujer, pais=nan, person_id=2806172.0)
  dir_0452: Nando Caballero (sexo=nan, pais=nan, person_id=3669411.0)
  dir_0455: Rubén Burén (sexo=nan, pais=nan, person_id=2759690.0)
  dir_0456: José María Zavala (sexo=hombre, pais=nan, person_id=2180969.0)
  dir_0457: Ignacio Benedeti (sexo=nan, pais=nan, person_id=1806051.0)
  dir_0458: Miguel Herrero (sexo=nan, pais=nan, person_id=4951153.0)
  dir_0459: J. Alberto Andrés Lacasta (sexo=nan, pais=nan, person_id=4160275.0)
  dir_0460: Celia Giraldo (sexo=mujer, pais=nan, person_id=2270965.0)
  dir_0463: Jérémie Degruson (sexo=hombre, pais=nan, person_id=1324172.0)
  dir_0464: More Raça (sexo=mujer, pais=nan, person_id=1392412.0)
  dir_0466: Xesús Ron (sexo=nan, pais=nan, person_id=2574131.0)
  dir_0470: Ángel Holgado (sexo=nan, pais=nan, person_id=3793844.0)
  dir_0471: Joan Frank Charansonnet (sexo=nan, pais=nan, person_id=5959830.0)
  dir_0473: J.L. Rojas (sexo=nan, pais=nan, person_id=5252601.0)
  dir_0477: Zaida Carmona (sexo=nan, pais=nan, person_id=2207591.0)
  dir_0478: Hèctor Romance (sexo=hombre, pais=nan, person_id=2285247.0)
  dir_0479: David M. Mateo (sexo=nan, pais=ES, person_id=4277755.0)
  dir_0480: Miguel Angel Barroso Garcia (sexo=nan, pais=nan, person_id=2764547.0)
  dir_0481: Darío Autrán (sexo=nan, pais=nan, person_id=1741791.0)
  dir_0484: Kevin Castellano (sexo=nan, pais=nan, person_id=1842346.0)
  dir_0485: Edu Hirschfeld (sexo=nan, pais=nan, person_id=3490020.0)
  dir_0489: Iván Karras (sexo=nan, pais=nan, person_id=3168014.0)
  dir_0490: Carolina África (sexo=nan, pais=nan, person_id=2022341.0)
  dir_0491: Pilar Ordóñez (sexo=mujer, pais=nan, person_id=1072835.0)
  dir_0492: David Ruiz (sexo=nan, pais=nan, person_id=6149474.0)
  dir_0493: Pitu González (sexo=nan, pais=nan, person_id=4308395.0)
  dir_0494: Carlos Giménez (sexo=nan, pais=nan, person_id=6162301.0)
  dir_0495: Nina Solà (sexo=mujer, pais=nan, person_id=3644479.0)
  dir_0497: Francisco Sánchez (sexo=nan, pais=nan, person_id=5466763.0)
  dir_0498: Iñaki Peña (sexo=nan, pais=nan, person_id=6332299.0)
  dir_0500: Percy Monso (sexo=nan, pais=nan, person_id=6371154.0)
  dir_0501: Manuel Nector Yáñez (sexo=nan, pais=nan, person_id=3669393.0)
  dir_0503: Alberto Ortega (sexo=hombre, pais=nan, person_id=2407283.0)
  dir_0504: Ángel González (sexo=nan, pais=nan, person_id=6363870.0)
  dir_0505: Javi Camino (sexo=nan, pais=nan, person_id=2108770.0)
  dir_0506: Tommy Llorens (sexo=nan, pais=nan, person_id=4026096.0)
  dir_0507: Pablo Romero-Fresco (sexo=nan, pais=nan, person_id=1797508.0)
  dir_0508: Julio Mazarico (sexo=nan, pais=nan, person_id=1672993.0)
  dir_0509: Narciso Ibáñez Serrador (sexo=nan, pais=nan, person_id=5345510.0)
  dir_0511: Martín Soto (sexo=nan, pais=nan, person_id=4764008.0)
  dir_0512: Xuban Intxausti (sexo=nan, pais=nan, person_id=3489419.0)
  dir_0513: Nicole Betancourt (sexo=nan, pais=nan, person_id=1658534.0)
  dir_0515: Javier Aguirre (sexo=nan, pais=nan, person_id=5626806.0)
  dir_0516: Julio Soto Gurpide (sexo=hombre, pais=nan, person_id=1580840.0)
  dir_0517: David Andrade (sexo=nan, pais=nan, person_id=5938497.0)
  dir_0518: Alberto Utrera (sexo=nan, pais=nan, person_id=1796079.0)
  dir_0519: Javier Martín-Domínguez (sexo=nan, pais=nan, person_id=4833291.0)
  dir_0520: Antonio Aguilar Vicente (sexo=nan, pais=nan, person_id=1468122.0)
  dir_0521: Carlos Aceituno (sexo=nan, pais=nan, person_id=5061066.0)
  dir_0522: Marc Fàbregas (sexo=hombre, pais=nan, person_id=1364092.0)
  dir_0523: Bertha Gaztelumendi (sexo=nan, pais=nan, person_id=1168568.0)
  dir_0524: Rosa Zufía (sexo=nan, pais=nan, person_id=4250005.0)
  dir_0525: Rogelio Enríquez Soto (sexo=nan, pais=nan, person_id=5116594.0)
  dir_0529: Javier Salvador (sexo=nan, pais=nan, person_id=5470289.0)
  dir_0531: Jaime Murciego (sexo=nan, pais=nan, person_id=2558738.0)
  dir_0532: Pablo Iraburu (sexo=hombre, pais=nan, person_id=1119623.0)
  dir_0535: Bruno Martín (sexo=nan, pais=nan, person_id=2873841.0)
  dir_0538: Mohamed El Badaoui (sexo=nan, pais=nan, person_id=2881144.0)
  dir_0539: Bernardo Hernández (sexo=nan, pais=nan, person_id=1566441.0)
  dir_0542: Mario Hernández (sexo=nan, pais=nan, person_id=3952402.0)
  dir_0543: Raimundo García (sexo=nan, pais=nan, person_id=1028828.0)
  dir_0545: Belén Santos (sexo=nan, pais=nan, person_id=1175887.0)
  dir_0546: Esaú Dharma (sexo=nan, pais=nan, person_id=1066407.0)
  dir_0547: Pablo Vara (sexo=nan, pais=nan, person_id=1170972.0)
  dir_0550: Esther Yañez (sexo=nan, pais=nan, person_id=3936156.0)
  dir_0555: Luis Roca (sexo=nan, pais=nan, person_id=1640298.0)
  dir_0561: Gaspar Broullón Pastoriza (sexo=nan, pais=nan, person_id=5046087.0)
  dir_0562: Felipe Pinzón Barbosa (sexo=nan, pais=nan, person_id=4936570.0)
  dir_0563: Juan Antonio Rodríguez Llano (sexo=nan, pais=nan, person_id=2453874.0)
  dir_0565: David Casals-Roma (sexo=nan, pais=nan, person_id=2503583.0)
  dir_0566: Marta Romero (sexo=nan, pais=nan, person_id=2270970.0)
  dir_0570: Natxo Leuza (sexo=nan, pais=nan, person_id=2697139.0)
  dir_0572: Ángel Tirado (sexo=nan, pais=ES, person_id=2428295.0)
  dir_0573: Diego Lodeiros (sexo=nan, pais=nan, person_id=3567372.0)
  dir_0574: Antón Álvarez (sexo=nan, pais=nan, person_id=4839826.0)
  dir_0575: Santos Bacana (sexo=nan, pais=nan, person_id=3193916.0)
  dir_0576: Cris Trenas (sexo=nan, pais=nan, person_id=4272320.0)
  dir_0577: Rogelio González (sexo=nan, pais=nan, person_id=3009003.0)

In [62]:
correccion = {
    'nombre': 'Juan Prosper',
    'person_id': None,
    'sexo': 'hombre',
    'fuente_sexo': 'manual',
    'pais': 'MX',
    'fuente_pais': 'manual',
}

mask = guion['gui_id'] == 'gui_1440'
for columna, valor in correccion.items():
    guion.loc[mask, columna] = valor

In [63]:
"""
Formato: {id: {'sexo': 'mujer'/'hombre'/'no_binario', 'pais': 'XX' (ISO alpha-2)}
"""

CORRECCIONES_MANUALES_DIR_GUI = {
    # 'dir_0007': {'sexo': 'mujer', 'pais': 'AR'},
    # 'gui_0012': {'pais': 'MX'},
}


def aplicar_correcciones_dim(dim_df, prefijo, correcciones_dict):
    dim_df = dim_df.copy()
    id_col = f"{prefijo}_id"
    aplicados = []
    for id_persona, valores in correcciones_dict.items():
        if id_persona not in dim_df[id_col].values:
            print(f"⚠ {id_persona} no encontrado en la tabla, se omite")
            continue
        mask = dim_df[id_col] == id_persona
        if 'sexo' in valores:
            dim_df.loc[mask, 'sexo'] = valores['sexo']
            dim_df.loc[mask, 'fuente_sexo'] = 'manual'
        if 'pais' in valores:
            dim_df.loc[mask, 'pais'] = valores['pais']
            dim_df.loc[mask, 'fuente_pais'] = 'manual'
        aplicados.append(id_persona)
    print(f"{len(aplicados)} correcciones aplicadas de {len(correcciones_dict)}")
    return dim_df


if CORRECCIONES_MANUALES_DIR_GUI:
    direccion = aplicar_correcciones_dim(direccion, 'dir', CORRECCIONES_MANUALES_DIR_GUI)
    guion = aplicar_correcciones_dim(guion, 'gui', CORRECCIONES_MANUALES_DIR_GUI)

## 13. Créditos intermedios (para el notebook de tablas finales)

Tabla puente **provisional**: `icaa_id`/`tmdb_id` (referencia a película,
resoluble vía `icaa_peliculas.csv` ya actualizado) + `dir_id`/`gui_id`
(referencia a persona). El notebook de tablas finales la lee, asigna
`pelicula_id` real (uniendo por `icaa_id`/`tmdb_id`) y con eso construye
`direccion_peliculas`/`guion_peliculas` definitivas -- esta tabla no se
sube a MySQL, es solo un CSV de paso.

In [64]:
def construir_creditos_intermedios(rol, prefijo, dim):
    creditos_rol = credits_df[credits_df['rol'] == rol].copy()

    con_id = creditos_rol[creditos_rol['person_id'].notna()].drop_duplicates(
        subset=['icaa_id', 'tmdb_id', 'person_id']
    )
    sin_id = creditos_rol[creditos_rol['person_id'].isna()].drop_duplicates(
        subset=['icaa_id', 'tmdb_id', 'nombre']
    )

    con_id = con_id.merge(
        dim[dim['person_id'].notna()][[f"{prefijo}_id", 'person_id']],
        on='person_id', how='left', validate='many_to_one'
    )
    sin_id = sin_id.merge(
        dim[dim['person_id'].isna()][[f"{prefijo}_id", 'nombre_credito_original']],
        left_on='nombre', right_on='nombre_credito_original', how='left'
    )

    creditos = pd.concat([con_id, sin_id], ignore_index=True)[
        ['icaa_id', 'tmdb_id', f"{prefijo}_id", 'fuente_credito', 'metodo_match_persona']
    ].reset_index(drop=True)
    return creditos


creditos_direccion_intermedio = construir_creditos_intermedios('director', 'dir', direccion)
creditos_guion_intermedio = construir_creditos_intermedios('guionista', 'gui', guion)

print(f"creditos_direccion_intermedio: {len(creditos_direccion_intermedio)} filas")
print(f"creditos_guion_intermedio: {len(creditos_guion_intermedio)} filas")

revisar_matches = pd.concat([creditos_direccion_intermedio, creditos_guion_intermedio])
revisar_matches = revisar_matches[revisar_matches['metodo_match_persona'] == 'busqueda_nombre_aproximada']
print(f"\n⚠ Créditos a revisar por match aproximado (nombre no coincide exacto): {len(revisar_matches)}")

creditos_direccion_intermedio: 2159 filas
creditos_guion_intermedio: 2992 filas

⚠ Créditos a revisar por match aproximado (nombre no coincide exacto): 310

## 14. Exportar

In [65]:
# direccion/guion sí van a MySQL -- son tablas finales, no dependen de pelicula_id
engine = create_engine(
    f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
    f"@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}"
)
direccion.to_sql('direccion', engine, if_exists='replace', index=False)
guion.to_sql('guion', engine, if_exists='replace', index=False)
print("✓ Exportado a MySQL: direccion, guion")
engine.dispose()
print("MySQL conexión cerrada.")

✓ Exportado a MySQL: direccion, guion
MySQL conexión cerrada.

In [66]:
direccion.to_csv(CSV_DIR / "direccion.csv", index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC)
guion.to_csv(CSV_DIR / "guion.csv", index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC)

# Créditos intermedios -- SOLO CSV, no van a MySQL todavía (esquema no final)
creditos_direccion_intermedio.to_csv(CSV_DIR / "creditos_direccion_intermedio.csv", index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC)
creditos_guion_intermedio.to_csv(CSV_DIR / "creditos_guion_intermedio.csv", index=False, sep=';', quoting=csv.QUOTE_NONNUMERIC)

print("✓ Exportado a CSV:")
for nombre in ['direccion', 'guion', 'creditos_direccion_intermedio', 'creditos_guion_intermedio']:
    ruta = CSV_DIR / f"{nombre}.csv"
    print(f"  {ruta} ({ruta.stat().st_size / 1024:.1f} KB)")

✓ Exportado a CSV:
  ..\3 - csv\direccion.csv (111.0 KB)
  ..\3 - csv\guion.csv (154.0 KB)
  ..\3 - csv\creditos_direccion_intermedio.csv (112.0 KB)
  ..\3 - csv\creditos_guion_intermedio.csv (153.3 KB)